/**
 * Continuous Deployment Pipeline V1 — bounds and pass token.
 */

export const CONTINUOUS_DEPLOYMENT_PIPELINE_V1_PASS_TOKEN =
  'CONTINUOUS_DEPLOYMENT_PIPELINE_V1_PASS';

export const CONTINUOUS_DEPLOYMENT_PIPELINE_V1_FAIL_TOKEN =
  'CONTINUOUS_DEPLOYMENT_PIPELINE_V1_FAIL';

export const CONTINUOUS_DEPLOYMENT_PIPELINE_V1_REPORT_TITLE =
  'CONTINUOUS_DEPLOYMENT_PIPELINE_V1_REPORT.md';

export const CONTINUOUS_DEPLOYMENT_PIPELINE_V1_ARTIFACT_DIR =
  '.continuous-deployment-pipeline-v1';

export const MAX_DEPLOYMENT_HISTORY_SIZE = 1000;

export const MIN_DEPLOYMENT_CANDIDATES = 5;

export const MIN_PROMOTION_DECISIONS = 5;

export const MIN_DEPLOYMENT_HISTORY_ENTRIES = 5;

export const MIN_ROLLBACK_RECOMMENDATIONS = 2;

export const MIN_DEPLOYMENT_FAILURE_INCIDENTS = 1;

export const MAX_TENANT_DEPLOYMENT_VIOLATIONS = 0;

export const PRIOR_PASS_TOKENS = [
  'PRODUCTION_OBSERVABILITY_PLATFORM_V1_PASS',
  'CUSTOMER_OPERATIONS_PLATFORM_V1_PASS',
  'STRATEGIC_CAPABILITY_AUDIT_V4_PASS',
  'PRODUCTION_READINESS_GATE_V1_PASS',
  'CLOUD_EXECUTION_PATH_V1_PASS',
  'UNIFIED_FAILURE_ESCALATION_AUTHORITY_V1_PASS',
  'CANONICAL_OWNERSHIP_V2_PASS',
] as const;
