/**
 * Market Expansion Reality Authority — markdown report builder.
 */

import {
  MARKET_EXPANSION_REALITY_AUTHORITY_PASS_TOKEN,
  MARKET_EXPANSION_REALITY_AUTHORITY_PHASE,
  MARKET_EXPANSION_REALITY_AUTHORITY_REPORT_TITLE,
  MARKET_EXPANSION_REALITY_CORE_QUESTION,
  SAFETY_GUARANTEES,
} from './market-expansion-reality-registry.js';
import type { MarketExpansionRealityReport } from './market-expansion-reality-types.js';

export function buildMarketExpansionRealityReportMarkdown(
  report: MarketExpansionRealityReport,
): string {
  const lines: string[] = [
    `# ${MARKET_EXPANSION_REALITY_AUTHORITY_REPORT_TITLE}`,
    '',
    `Generated: ${report.generatedAt}`,
    '',
    '## Phase',
    '',
    MARKET_EXPANSION_REALITY_AUTHORITY_PHASE,
    '',
    '## Core Question',
    '',
    MARKET_EXPANSION_REALITY_CORE_QUESTION,
    '',
    '# Market Expansion Reality Authority',
    '',
    '## Market Expansion State',
    '',
    `**${report.marketExpansionState}**`,
    '',
    '## Overall Expansion Score',
    '',
    `${report.overallExpansionScore}/100 (confidence: ${report.confidence}/100)`,
    '',
    '## Customer Segment Analysis',
    '',
    `- cross-segment adoption: ${report.customerSegment.crossSegmentAdoption ? 'YES' : 'NO'}`,
    `- customer diversity: ${report.customerSegment.customerDiversity ? 'YES' : 'NO'}`,
    `- segment concentration risk assessed: ${report.customerSegment.segmentConcentrationRisk ? 'YES' : 'NO'}`,
    `- customer segment score: ${report.customerSegmentScore}/100`,
    '',
    '## Industry Analysis',
    '',
    `- industry fit signals: ${report.industry.industryFitSignals ? 'YES' : 'NO'}`,
    `- use case diversity: ${report.industry.useCaseDiversity ? 'YES' : 'NO'}`,
    `- industry score: ${report.industryScore}/100`,
    '',
    '## Regional Analysis',
    '',
    `- regional adoption signals: ${report.regional.regionalAdoptionSignals ? 'YES' : 'NO'}`,
    `- localization readiness: ${report.regional.localizationReadiness ? 'YES' : 'NO'}`,
    `- regional score: ${report.regionalScore}/100`,
    '',
    '## Channel Analysis',
    '',
    `- acquisition channel diversity: ${report.channel.acquisitionChannelDiversity ? 'YES' : 'NO'}`,
    `- expansion channel readiness: ${report.channel.expansionChannelReadiness ? 'YES' : 'NO'}`,
    `- channel score: ${report.channelScore}/100`,
    '',
    '## Product-Market-Fit Resilience',
    '',
    `- fit stability: ${report.productMarketFit.fitStability ? 'YES' : 'NO'}`,
    `- expansion stress risk assessed: ${report.productMarketFit.expansionStressRisk ? 'YES' : 'NO'}`,
    `- product flexibility: ${report.productMarketFit.productFlexibility ? 'YES' : 'NO'}`,
    `- PMF score: ${report.productMarketFitScore}/100`,
    '',
    '## Expansion Risks',
    '',
    `- expansion risk score: ${report.expansionRiskScore}/100`,
    ...report.expansionRisk.riskSignals.map((r) => `- ${r}`),
    ...(report.expansionRisk.riskSignals.length === 0 ? ['- no significant expansion risks identified'] : []),
    '',
    '## Missing Evidence',
    '',
    ...report.missingEvidence.map((m) => `- ${m}`),
    ...(report.missingEvidence.length === 0 ? ['- none identified'] : []),
    '',
    '## Recommended Actions',
    '',
    ...report.recommendedActions.map((a) => `- ${a}`),
    '',
    '## Final Verdict',
    '',
    report.finalVerdict,
    '',
    '## Safety Guarantees',
    '',
    ...SAFETY_GUARANTEES.map((g) => `- ${g}`),
    '',
    '## Pass Token',
    '',
    MARKET_EXPANSION_REALITY_AUTHORITY_PASS_TOKEN,
  ];

  return lines.join('\n');
}

export function formatMarketExpansionRealitySummary(report: MarketExpansionRealityReport): string {
  return `${report.marketExpansionState} (${report.overallExpansionScore}/100)`;
}
