/**
 * Visual Reference Intelligence — registry constants (V1).
 */

export const VISUAL_REFERENCE_INTELLIGENCE_PASS_TOKEN = 'VISUAL_REFERENCE_INTELLIGENCE_V1_PASS';

export const VISUAL_REFERENCE_INTELLIGENCE_OWNER_MODULE = 'visual-reference-intelligence';

export const VISUAL_REFERENCE_INTELLIGENCE_PHASE = '26.23';

export const VISUAL_REFERENCE_INTELLIGENCE_REPORT_TITLE = 'Visual Reference Intelligence Report';

export const MAX_VISUAL_REFERENCE_HISTORY = 32;

export const SUPPORTED_VISUAL_EXTENSIONS = ['PNG', 'JPG', 'JPEG', 'WEBP'] as const;

export const LAYOUT_REGION_TYPES = [
  'HEADER',
  'FOOTER',
  'SIDEBAR',
  'NAVIGATION',
  'CARDS',
  'LISTS',
  'FORMS',
  'BUTTONS',
  'MODALS',
] as const;

export const COMPONENT_EVIDENCE_TOKENS = [
  'HEADER_DETECTED',
  'FOOTER_DETECTED',
  'SIDEBAR_DETECTED',
  'NAVIGATION_DETECTED',
  'BOTTOM_NAVIGATION_DETECTED',
  'CARD_DETECTED',
  'LIST_DETECTED',
  'FORM_DETECTED',
  'BUTTON_DETECTED',
  'BUTTON_GROUP_DETECTED',
  'MODAL_DETECTED',
] as const;

export const INFERRED_FLOW_TYPES = [
  'AUTHENTICATION',
  'ONBOARDING',
  'DASHBOARD',
  'SETTINGS',
  'CHECKOUT',
  'PROFILE',
  'MESSAGING',
] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_INTELLIGENCE',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MODIFICATION',
  'NO_OCR_DOCUMENT_EXTRACTION',
  'NO_VOICE_PROCESSING',
  'NO_AUTONOMOUS_EXECUTION',
  'EVIDENCE_BASED_OUTPUTS_ONLY',
  'BOUNDED_ANALYSIS_HISTORY',
] as const;
