/**
 * Cross-System Orchestration Proof — registry constants (V1).
 */

export const CROSS_SYSTEM_ORCHESTRATION_PROOF_V1_PASS = 'CROSS_SYSTEM_ORCHESTRATION_PROOF_V1_PASS';

export const ORCHESTRATION_PROOF_OWNER_MODULE = 'cross-system-orchestration-proof';

export const ORCHESTRATION_PROOF_PHASE = '26.35';

export const ORCHESTRATION_PROOF_REPORT_TITLE = 'Cross-System Orchestration Proof Report';

export const MAX_ORCHESTRATION_PROOF_HISTORY = 16;

export const MAX_ORCHESTRATION_PROOF_RUNTIME_MS = 90_000;

export const ORCHESTRATION_PROOF_CATEGORIES = [
  'BROKEN_CHAIN',
  'PARTIAL_CHAIN',
  'CONSISTENT_CHAIN',
  'FULLY_PROVEN_CHAIN',
] as const;

export const CHAIN_PROOF_SCENARIO_TYPES = [
  'SIMPLE_APP',
  'COMPLEX_MARKETPLACE',
  'SAAS_DASHBOARD',
  'MOBILE_FIRST',
  'AI_POWERED',
  'E_COMMERCE',
] as const;

export const AUTHORITY_CHAIN_ORDER = [
  'UNIFIED_INTAKE_INTELLIGENCE',
  'PLANNING_GATE_AUTHORITY',
  'PLANNING_BRIEF_GENERATOR',
  'ARCHITECTURE_BRIEF_GENERATOR',
  'BUILD_PLAN_GENERATOR',
  'FOUNDER_TEST_AUTOMATION',
] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_INTELLIGENCE',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MODIFICATION',
  'NO_AUTONOMOUS_EXECUTION',
  'NO_AUTONOMOUS_BUILDING',
  'EVIDENCE_BASED_PROOF_ONLY',
  'NO_FAKE_CONSISTENCY',
  'BOUNDED_PROOF_HISTORY',
  'RUNTIME_BUDGET_SAFEGUARDS',
] as const;
