/**
 * Find Panel alias registry — searchable aliases for intelligence modules.
 */

export interface FindPanelAlias {
  alias: string;
  capabilityId: string;
  ownerModule: string;
}

export const WORLD2_BUILDER_PACKET_FIND_ALIASES: readonly FindPanelAlias[] = [
  { alias: 'Builder Packet Execution', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'World 2 Builder Packet', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'Execution Packet', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'Packet Readiness', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'Builder Packet Approval', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'World 2 Build Preparation', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'Controlled Apply', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Apply Plan', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'World 2 Apply', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Apply Readiness', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Apply Approval', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Future Apply', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Rollback Runtime', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'World 2 Rollback', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Rollback Plan', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Rollback Safety', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Snapshot Requirement', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Change Reversal', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Recovery Runtime', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'World 2 Recovery', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Recovery Plan', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Failure Recovery', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Recovery Strategy', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Self Evolution Escalation', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Three Failure Rule', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Completion Runtime', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'World 2 Completion', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Completion Plan', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Completion Criteria', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Completion Evidence', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Project Done', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Verification Required', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Live Preview', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Runtime', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Session', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Target', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Ready', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Blocked', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Intelligence', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Preview Readiness', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Preview Capabilities', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Preview Limitations', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Observation Plan', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Self Vision Preparation', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Self Vision', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Self Vision Runtime', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Observation Session', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Observation Targets', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Capture Plan', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Vision Ready', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'UI Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Layout Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Navigation Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Loading Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Responsive Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Inspection Ready', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Interaction Testing', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Button Testing', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Navigation Testing', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Workflow Testing', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Interaction Results', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Interaction Ready', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Visual Verification', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Results', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Evidence', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Risks', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Ready', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Failed', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'UVL Runtime', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Unified Verification Lab', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Verification Runtime', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Verification Providers', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Verification Sessions', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Verification Registry', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Targets', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Dependencies', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Requirements', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Owners', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Orchestrator', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Verification Plan', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Execution Order', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Parallel Verification', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Blocked Verification', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Evidence Engine', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Evidence Inventory', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Evidence Lineage', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Evidence Ownership', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Evidence Traceability', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Verification Evidence Authority', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Verification Reports', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Reporting', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification History', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Trends', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Summary', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Failures', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Evidence Reports', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Founder Verification Reports', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Unified Verification', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification Entry', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification Requests', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification Sessions', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification State', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification History', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification Responses', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Cloud Runtime', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime Inventory', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime Lifecycle', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime State', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime Sessions', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime Ownership', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime History', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Cloud Runtime Diagnostics', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Workspace Hosting', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Hosted Workspaces', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Inventory', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Lifecycle', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace State', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Sessions', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Ownership', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Isolation', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Runtime Links', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Diagnostics', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Persistent Build Runtime', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Persistent Builds', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Sessions', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build State', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Progress', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Context', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Resume', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Runtime Links', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Workspace Links', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build History', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Diagnostics', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Cloud Verification', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Requests', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Sessions', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification State', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Scope', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Context', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Evidence', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Reports', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Runtime Links', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Workspace Links', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Build Links', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Diagnostics', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Recovery', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Candidates', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Plans', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Sessions', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery State', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Context', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Runtime Links', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Workspace Links', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Build Links', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Verification Links', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Diagnostics', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Cloud Monitoring', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Health', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Alerts', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Sessions', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Context', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Runtime Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Workspace Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Build Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Verification Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Recovery Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Diagnostics', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Mobile Command Runtime', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Sessions', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command State', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Context', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Permissions', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Action Gate', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Cloud Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Workspace Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Build Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Verification Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Recovery Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Monitoring Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Operator Feed Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Project Vault Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Diagnostics', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Chat Runtime', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Sessions', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Messages', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Prompts', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Responses', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Routing', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Action Gate', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Context', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Cloud Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Workspace Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Build Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Verification Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Monitoring Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Operator Feed Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Project Vault Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Diagnostics', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Preview Runtime', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Sessions', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Eligibility', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Safety', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Device Policy', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Desktop Recommendation', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview State', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Command Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Chat Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Cloud Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Workspace Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Build Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Verification Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Diagnostics', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Approval Runtime', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Sessions', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Requests', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Decisions', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Visibility', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval State', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Command Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Chat Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Preview Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval World2 Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval AiDev Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Cloud Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Project Vault Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Diagnostics', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Cross Device Runtime', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Sessions', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Inventory', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Device Registration', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Device Link', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Device Handoff', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Device Visibility', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device State', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Command Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Chat Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Preview Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Approval Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Cloud Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Diagnostics', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Founder Notification Runtime', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Founder Notifications', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Founder Notification Inventory', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Founder Alert', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Routing', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Visibility', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Priority', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Channel', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification State', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Lifecycle', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Diagnostics', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Founder Inbox', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Founder Inbox Foundation', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Founder Inbox Inventory', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Visualization', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Filter', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Search', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Grouping', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Archive', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Acknowledgement', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Diagnostics', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Notification Delivery', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Notification Delivery Foundation', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Notification Delivery Inventory', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Planning', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Routing', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Targeting', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Eligibility', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Policy', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Blocking', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Deferral', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Diagnostics', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Autonomous Testing', capabilityId: 'AUTONOMOUS_TESTING', ownerModule: 'devpulse_v2_autonomous_testing' },
  { alias: 'Autonomous Test Plan', capabilityId: 'AUTONOMOUS_TESTING', ownerModule: 'devpulse_v2_autonomous_testing' },
  { alias: 'Test Depth', capabilityId: 'AUTONOMOUS_TESTING', ownerModule: 'devpulse_v2_autonomous_testing' },
  { alias: 'Test Suite', capabilityId: 'AUTONOMOUS_TESTING', ownerModule: 'devpulse_v2_autonomous_testing' },
  { alias: 'Autonomous Fixing', capabilityId: 'AUTONOMOUS_FIXING', ownerModule: 'devpulse_v2_autonomous_fixing' },
  { alias: 'Fix Plan', capabilityId: 'AUTONOMOUS_FIXING', ownerModule: 'devpulse_v2_autonomous_fixing' },
  { alias: 'Root Cause', capabilityId: 'AUTONOMOUS_FIXING', ownerModule: 'devpulse_v2_autonomous_fixing' },
  { alias: 'Repair Strategy', capabilityId: 'AUTONOMOUS_FIXING', ownerModule: 'devpulse_v2_autonomous_fixing' },
  { alias: 'Rollback Plan', capabilityId: 'AUTONOMOUS_FIXING', ownerModule: 'devpulse_v2_autonomous_fixing' },
  { alias: 'Autonomous Verification', capabilityId: 'AUTONOMOUS_VERIFICATION', ownerModule: 'devpulse_v2_autonomous_verification' },
  { alias: 'Verification Decision', capabilityId: 'AUTONOMOUS_VERIFICATION', ownerModule: 'devpulse_v2_autonomous_verification' },
  { alias: 'Evidence Analysis', capabilityId: 'AUTONOMOUS_VERIFICATION', ownerModule: 'devpulse_v2_autonomous_verification' },
  { alias: 'Trust Evaluation', capabilityId: 'AUTONOMOUS_VERIFICATION', ownerModule: 'devpulse_v2_autonomous_verification' },
  { alias: 'Verification Confidence', capabilityId: 'AUTONOMOUS_VERIFICATION', ownerModule: 'devpulse_v2_autonomous_verification' },
  { alias: 'Autonomous Completion', capabilityId: 'AUTONOMOUS_COMPLETION_ENGINE', ownerModule: 'devpulse_v2_autonomous_completion_engine' },
  { alias: 'Completion Decision', capabilityId: 'AUTONOMOUS_COMPLETION_ENGINE', ownerModule: 'devpulse_v2_autonomous_completion_engine' },
  { alias: 'Completion Readiness', capabilityId: 'AUTONOMOUS_COMPLETION_ENGINE', ownerModule: 'devpulse_v2_autonomous_completion_engine' },
  { alias: 'Completion State', capabilityId: 'AUTONOMOUS_COMPLETION_ENGINE', ownerModule: 'devpulse_v2_autonomous_completion_engine' },
  { alias: 'Loop Guard', capabilityId: 'AUTONOMOUS_COMPLETION_ENGINE', ownerModule: 'devpulse_v2_autonomous_completion_engine' },
  { alias: 'Multi Project', capabilityId: 'MULTI_PROJECT_FOUNDATION', ownerModule: 'devpulse_v2_multi_project_foundation' },
  { alias: 'Project Registry', capabilityId: 'MULTI_PROJECT_FOUNDATION', ownerModule: 'devpulse_v2_multi_project_foundation' },
  { alias: 'Project Isolation', capabilityId: 'MULTI_PROJECT_FOUNDATION', ownerModule: 'devpulse_v2_multi_project_foundation' },
  { alias: 'Project Workspace', capabilityId: 'MULTI_PROJECT_FOUNDATION', ownerModule: 'devpulse_v2_multi_project_foundation' },
  { alias: 'Project Lifecycle', capabilityId: 'MULTI_PROJECT_FOUNDATION', ownerModule: 'devpulse_v2_multi_project_foundation' },
  { alias: 'Workspace Isolation', capabilityId: 'WORKSPACE_ISOLATION_EXPANSION', ownerModule: 'devpulse_v2_workspace_isolation_expansion' },
  { alias: 'Workspace Boundary', capabilityId: 'WORKSPACE_ISOLATION_EXPANSION', ownerModule: 'devpulse_v2_workspace_isolation_expansion' },
  { alias: 'Workspace Access', capabilityId: 'WORKSPACE_ISOLATION_EXPANSION', ownerModule: 'devpulse_v2_workspace_isolation_expansion' },
  { alias: 'Workspace Ownership', capabilityId: 'WORKSPACE_ISOLATION_EXPANSION', ownerModule: 'devpulse_v2_workspace_isolation_expansion' },
  { alias: 'Isolation Violation', capabilityId: 'WORKSPACE_ISOLATION_EXPANSION', ownerModule: 'devpulse_v2_workspace_isolation_expansion' },
  { alias: 'Resource Allocation', capabilityId: 'RESOURCE_ALLOCATION', ownerModule: 'devpulse_v2_resource_allocation' },
  { alias: 'Resource Budget', capabilityId: 'RESOURCE_ALLOCATION', ownerModule: 'devpulse_v2_resource_allocation' },
  { alias: 'Resource Priority', capabilityId: 'RESOURCE_ALLOCATION', ownerModule: 'devpulse_v2_resource_allocation' },
  { alias: 'Allocation Queue', capabilityId: 'RESOURCE_ALLOCATION', ownerModule: 'devpulse_v2_resource_allocation' },
  { alias: 'Resource Contention', capabilityId: 'RESOURCE_ALLOCATION', ownerModule: 'devpulse_v2_resource_allocation' },
  { alias: 'Parallel Build Orchestration', capabilityId: 'PARALLEL_BUILD_ORCHESTRATION', ownerModule: 'devpulse_v2_parallel_build_orchestration' },
  { alias: 'Orchestration Plan', capabilityId: 'PARALLEL_BUILD_ORCHESTRATION', ownerModule: 'devpulse_v2_parallel_build_orchestration' },
  { alias: 'Execution Groups', capabilityId: 'PARALLEL_BUILD_ORCHESTRATION', ownerModule: 'devpulse_v2_parallel_build_orchestration' },
  { alias: 'Orchestration Schedule', capabilityId: 'PARALLEL_BUILD_ORCHESTRATION', ownerModule: 'devpulse_v2_parallel_build_orchestration' },
  { alias: 'Build Orchestration', capabilityId: 'PARALLEL_BUILD_ORCHESTRATION', ownerModule: 'devpulse_v2_parallel_build_orchestration' },
  { alias: 'Multi Project Verification', capabilityId: 'MULTI_PROJECT_VERIFICATION', ownerModule: 'devpulse_v2_multi_project_verification' },
  { alias: 'Portfolio Verification', capabilityId: 'MULTI_PROJECT_VERIFICATION', ownerModule: 'devpulse_v2_multi_project_verification' },
  { alias: 'Verification Readiness', capabilityId: 'MULTI_PROJECT_VERIFICATION', ownerModule: 'devpulse_v2_multi_project_verification' },
  { alias: 'Project Verification Confidence', capabilityId: 'MULTI_PROJECT_VERIFICATION', ownerModule: 'devpulse_v2_multi_project_verification' },
  { alias: 'Cross-Project Verification', capabilityId: 'MULTI_PROJECT_VERIFICATION', ownerModule: 'devpulse_v2_multi_project_verification' },
  { alias: 'Verification Orchestration', capabilityId: 'MULTI_PROJECT_VERIFICATION_ORCHESTRATION', ownerModule: 'devpulse_v2_multi_project_verification_orchestration' },
  { alias: 'Verification Groups', capabilityId: 'MULTI_PROJECT_VERIFICATION_ORCHESTRATION', ownerModule: 'devpulse_v2_multi_project_verification_orchestration' },
  { alias: 'Portfolio Verification Schedule', capabilityId: 'MULTI_PROJECT_VERIFICATION_ORCHESTRATION', ownerModule: 'devpulse_v2_multi_project_verification_orchestration' },
  { alias: 'Verification Dependency', capabilityId: 'MULTI_PROJECT_VERIFICATION_ORCHESTRATION', ownerModule: 'devpulse_v2_multi_project_verification_orchestration' },
  { alias: 'Multi Project Verification Orchestration', capabilityId: 'MULTI_PROJECT_VERIFICATION_ORCHESTRATION', ownerModule: 'devpulse_v2_multi_project_verification_orchestration' },
  { alias: 'Multi Project Monitoring', capabilityId: 'MULTI_PROJECT_MONITORING', ownerModule: 'devpulse_v2_multi_project_monitoring' },
  { alias: 'Portfolio Monitoring', capabilityId: 'MULTI_PROJECT_MONITORING', ownerModule: 'devpulse_v2_multi_project_monitoring' },
  { alias: 'Project Operator Feed', capabilityId: 'MULTI_PROJECT_MONITORING', ownerModule: 'devpulse_v2_multi_project_monitoring' },
  { alias: 'Live Preview Tabs', capabilityId: 'MULTI_PROJECT_MONITORING', ownerModule: 'devpulse_v2_multi_project_monitoring' },
  { alias: 'Project Progress Tracking', capabilityId: 'MULTI_PROJECT_MONITORING', ownerModule: 'devpulse_v2_multi_project_monitoring' },
  { alias: 'Missing Capability Escalation', capabilityId: 'MISSING_CAPABILITY_ESCALATION', ownerModule: 'devpulse_v2_missing_capability_escalation' },
  { alias: 'Capability Gap', capabilityId: 'MISSING_CAPABILITY_ESCALATION', ownerModule: 'devpulse_v2_missing_capability_escalation' },
  { alias: 'Repeated Stall', capabilityId: 'MISSING_CAPABILITY_ESCALATION', ownerModule: 'devpulse_v2_missing_capability_escalation' },
  { alias: 'Repeated Failure', capabilityId: 'MISSING_CAPABILITY_ESCALATION', ownerModule: 'devpulse_v2_missing_capability_escalation' },
  { alias: 'Self Evolving DevPulse', capabilityId: 'MISSING_CAPABILITY_ESCALATION', ownerModule: 'devpulse_v2_missing_capability_escalation' },
  { alias: 'Capability Research Engine', capabilityId: 'CAPABILITY_RESEARCH_ENGINE', ownerModule: 'devpulse_v2_capability_research_engine' },
  { alias: 'Capability Research', capabilityId: 'CAPABILITY_RESEARCH_ENGINE', ownerModule: 'devpulse_v2_capability_research_engine' },
  { alias: 'Duplicate Capability', capabilityId: 'CAPABILITY_RESEARCH_ENGINE', ownerModule: 'devpulse_v2_capability_research_engine' },
  { alias: 'Capability Gap Research', capabilityId: 'CAPABILITY_RESEARCH_ENGINE', ownerModule: 'devpulse_v2_capability_research_engine' },
  { alias: 'Missing Capability Research', capabilityId: 'CAPABILITY_RESEARCH_ENGINE', ownerModule: 'devpulse_v2_capability_research_engine' },
  { alias: 'Capability Planning Engine', capabilityId: 'CAPABILITY_PLANNING_ENGINE', ownerModule: 'devpulse_v2_capability_planning_engine' },
  { alias: 'Capability Planning', capabilityId: 'CAPABILITY_PLANNING_ENGINE', ownerModule: 'devpulse_v2_capability_planning_engine' },
  { alias: 'Capability Plan', capabilityId: 'CAPABILITY_PLANNING_ENGINE', ownerModule: 'devpulse_v2_capability_planning_engine' },
  { alias: 'Founder Approval', capabilityId: 'CAPABILITY_PLANNING_ENGINE', ownerModule: 'devpulse_v2_capability_planning_engine' },
  { alias: 'Duplicate Capability Plan', capabilityId: 'CAPABILITY_PLANNING_ENGINE', ownerModule: 'devpulse_v2_capability_planning_engine' },
  { alias: 'Capability Build Engine', capabilityId: 'CAPABILITY_BUILD_ENGINE', ownerModule: 'devpulse_v2_capability_build_engine' },
  { alias: 'Capability Build', capabilityId: 'CAPABILITY_BUILD_ENGINE', ownerModule: 'devpulse_v2_capability_build_engine' },
  { alias: 'Build Plan', capabilityId: 'CAPABILITY_BUILD_ENGINE', ownerModule: 'devpulse_v2_capability_build_engine' },
  { alias: 'Module Plan', capabilityId: 'CAPABILITY_BUILD_ENGINE', ownerModule: 'devpulse_v2_capability_build_engine' },
  { alias: 'Rollout Plan', capabilityId: 'CAPABILITY_BUILD_ENGINE', ownerModule: 'devpulse_v2_capability_build_engine' },
  { alias: 'Capability Verification Engine', capabilityId: 'CAPABILITY_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_capability_verification_engine' },
  { alias: 'Capability Verification', capabilityId: 'CAPABILITY_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_capability_verification_engine' },
  { alias: 'Verify Capability', capabilityId: 'CAPABILITY_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_capability_verification_engine' },
  { alias: 'Readiness Evaluation', capabilityId: 'CAPABILITY_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_capability_verification_engine' },
  { alias: 'Stall Protection', capabilityId: 'CAPABILITY_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_capability_verification_engine' },
  { alias: 'Self Evolution Governance', capabilityId: 'SELF_EVOLUTION_GOVERNANCE', ownerModule: 'devpulse_v2_self_evolution_governance' },
  { alias: 'Self Evolution', capabilityId: 'SELF_EVOLUTION_GOVERNANCE', ownerModule: 'devpulse_v2_self_evolution_governance' },
  { alias: 'Governance Decision', capabilityId: 'SELF_EVOLUTION_GOVERNANCE', ownerModule: 'devpulse_v2_self_evolution_governance' },
  { alias: 'Self Modification', capabilityId: 'SELF_EVOLUTION_GOVERNANCE', ownerModule: 'devpulse_v2_self_evolution_governance' },
  { alias: 'Stall Governance', capabilityId: 'SELF_EVOLUTION_GOVERNANCE', ownerModule: 'devpulse_v2_self_evolution_governance' },
  { alias: 'Unified Trust Runtime', capabilityId: 'UNIFIED_TRUST_RUNTIME', ownerModule: 'devpulse_v2_unified_trust_runtime' },
  { alias: 'Trust Runtime', capabilityId: 'UNIFIED_TRUST_RUNTIME', ownerModule: 'devpulse_v2_unified_trust_runtime' },
  { alias: 'Trust Authority', capabilityId: 'UNIFIED_TRUST_RUNTIME', ownerModule: 'devpulse_v2_unified_trust_runtime' },
  { alias: 'Trust State', capabilityId: 'UNIFIED_TRUST_RUNTIME', ownerModule: 'devpulse_v2_unified_trust_runtime' },
  { alias: 'Trust Readiness', capabilityId: 'UNIFIED_TRUST_RUNTIME', ownerModule: 'devpulse_v2_unified_trust_runtime' },
  { alias: 'Evidence Intelligence', capabilityId: 'EVIDENCE_INTELLIGENCE', ownerModule: 'devpulse_v2_evidence_intelligence' },
  { alias: 'Evidence Authority', capabilityId: 'EVIDENCE_INTELLIGENCE', ownerModule: 'devpulse_v2_evidence_intelligence' },
  { alias: 'Evidence Analysis', capabilityId: 'EVIDENCE_INTELLIGENCE', ownerModule: 'devpulse_v2_evidence_intelligence' },
  { alias: 'Evidence Quality', capabilityId: 'EVIDENCE_INTELLIGENCE', ownerModule: 'devpulse_v2_evidence_intelligence' },
  { alias: 'Evidence Gaps', capabilityId: 'EVIDENCE_INTELLIGENCE', ownerModule: 'devpulse_v2_evidence_intelligence' },
  { alias: 'Reality Verification', capabilityId: 'REALITY_VERIFICATION_EXPANSION', ownerModule: 'devpulse_v2_reality_verification_expansion' },
  { alias: 'Reality Verification Expansion', capabilityId: 'REALITY_VERIFICATION_EXPANSION', ownerModule: 'devpulse_v2_reality_verification_expansion' },
  { alias: 'Reality Authority', capabilityId: 'REALITY_VERIFICATION_EXPANSION', ownerModule: 'devpulse_v2_reality_verification_expansion' },
  { alias: 'Claim Validation', capabilityId: 'REALITY_VERIFICATION_EXPANSION', ownerModule: 'devpulse_v2_reality_verification_expansion' },
  { alias: 'Reality State', capabilityId: 'REALITY_VERIFICATION_EXPANSION', ownerModule: 'devpulse_v2_reality_verification_expansion' },
  { alias: 'Reality Confidence', capabilityId: 'REALITY_VERIFICATION_EXPANSION', ownerModule: 'devpulse_v2_reality_verification_expansion' },
  { alias: 'Completion Truth Engine', capabilityId: 'COMPLETION_TRUTH_ENGINE', ownerModule: 'devpulse_v2_completion_truth_engine' },
  { alias: 'Completion Truth', capabilityId: 'COMPLETION_TRUTH_ENGINE', ownerModule: 'devpulse_v2_completion_truth_engine' },
  { alias: 'Truth Authority', capabilityId: 'COMPLETION_TRUTH_ENGINE', ownerModule: 'devpulse_v2_completion_truth_engine' },
  { alias: 'False Completion', capabilityId: 'COMPLETION_TRUTH_ENGINE', ownerModule: 'devpulse_v2_completion_truth_engine' },
  { alias: 'Completion Reality', capabilityId: 'COMPLETION_TRUTH_ENGINE', ownerModule: 'devpulse_v2_completion_truth_engine' },
  { alias: 'Prediction Trust Layer', capabilityId: 'PREDICTION_TRUST_LAYER', ownerModule: 'devpulse_v2_prediction_trust_layer' },
  { alias: 'Trust Prediction', capabilityId: 'PREDICTION_TRUST_LAYER', ownerModule: 'devpulse_v2_prediction_trust_layer' },
  { alias: 'Trust Risk Prediction', capabilityId: 'PREDICTION_TRUST_LAYER', ownerModule: 'devpulse_v2_prediction_trust_layer' },
  { alias: 'Trust Failure Prediction', capabilityId: 'PREDICTION_TRUST_LAYER', ownerModule: 'devpulse_v2_prediction_trust_layer' },
  { alias: 'Trust Recovery Recommendation', capabilityId: 'PREDICTION_TRUST_LAYER', ownerModule: 'devpulse_v2_prediction_trust_layer' },
  { alias: 'Unified Trust Score', capabilityId: 'UNIFIED_TRUST_SCORE', ownerModule: 'devpulse_v2_unified_trust_score' },
  { alias: 'Trust Score', capabilityId: 'UNIFIED_TRUST_SCORE', ownerModule: 'devpulse_v2_unified_trust_score' },
  { alias: 'Overall Trust', capabilityId: 'UNIFIED_TRUST_SCORE', ownerModule: 'devpulse_v2_unified_trust_score' },
  { alias: 'Trust Authority', capabilityId: 'UNIFIED_TRUST_SCORE', ownerModule: 'devpulse_v2_unified_trust_score' },
  { alias: 'Trust Confidence', capabilityId: 'UNIFIED_TRUST_SCORE', ownerModule: 'devpulse_v2_unified_trust_score' },
  { alias: 'Reliability Hardening', capabilityId: 'RELIABILITY_HARDENING', ownerModule: 'devpulse_v2_reliability_hardening' },
  { alias: 'Reliability', capabilityId: 'RELIABILITY_HARDENING', ownerModule: 'devpulse_v2_reliability_hardening' },
  { alias: 'Stability', capabilityId: 'RELIABILITY_HARDENING', ownerModule: 'devpulse_v2_reliability_hardening' },
  { alias: 'Runtime Stability', capabilityId: 'RELIABILITY_HARDENING', ownerModule: 'devpulse_v2_reliability_hardening' },
  { alias: 'Recovery Readiness', capabilityId: 'RELIABILITY_HARDENING', ownerModule: 'devpulse_v2_reliability_hardening' },
  { alias: 'Performance Hardening', capabilityId: 'PERFORMANCE_HARDENING', ownerModule: 'devpulse_v2_performance_hardening' },
  { alias: 'Performance', capabilityId: 'PERFORMANCE_HARDENING', ownerModule: 'devpulse_v2_performance_hardening' },
  { alias: 'Startup Performance', capabilityId: 'PERFORMANCE_HARDENING', ownerModule: 'devpulse_v2_performance_hardening' },
  { alias: 'Validation Performance', capabilityId: 'PERFORMANCE_HARDENING', ownerModule: 'devpulse_v2_performance_hardening' },
  { alias: 'UI Responsiveness', capabilityId: 'PERFORMANCE_HARDENING', ownerModule: 'devpulse_v2_performance_hardening' },
  { alias: 'Mobile Responsiveness', capabilityId: 'PERFORMANCE_HARDENING', ownerModule: 'devpulse_v2_performance_hardening' },
  { alias: 'Security Hardening', capabilityId: 'SECURITY_HARDENING', ownerModule: 'devpulse_v2_security_hardening' },
  { alias: 'Security', capabilityId: 'SECURITY_HARDENING', ownerModule: 'devpulse_v2_security_hardening' },
  { alias: 'Security Boundaries', capabilityId: 'SECURITY_HARDENING', ownerModule: 'devpulse_v2_security_hardening' },
  { alias: 'Secret Exposure', capabilityId: 'SECURITY_HARDENING', ownerModule: 'devpulse_v2_security_hardening' },
  { alias: 'Unsafe Capabilities', capabilityId: 'SECURITY_HARDENING', ownerModule: 'devpulse_v2_security_hardening' },
  { alias: 'Workspace Isolation', capabilityId: 'SECURITY_HARDENING', ownerModule: 'devpulse_v2_security_hardening' },
  { alias: 'Access Control Readiness', capabilityId: 'SECURITY_HARDENING', ownerModule: 'devpulse_v2_security_hardening' },
  { alias: 'Privacy Hardening', capabilityId: 'PRIVACY_HARDENING', ownerModule: 'devpulse_v2_privacy_hardening' },
  { alias: 'Privacy', capabilityId: 'PRIVACY_HARDENING', ownerModule: 'devpulse_v2_privacy_hardening' },
  { alias: 'Personal Data', capabilityId: 'PRIVACY_HARDENING', ownerModule: 'devpulse_v2_privacy_hardening' },
  { alias: 'Data Boundaries', capabilityId: 'PRIVACY_HARDENING', ownerModule: 'devpulse_v2_privacy_hardening' },
  { alias: 'Retention Risk', capabilityId: 'PRIVACY_HARDENING', ownerModule: 'devpulse_v2_privacy_hardening' },
  { alias: 'Disclosure Risk', capabilityId: 'PRIVACY_HARDENING', ownerModule: 'devpulse_v2_privacy_hardening' },
  { alias: 'Redaction Readiness', capabilityId: 'PRIVACY_HARDENING', ownerModule: 'devpulse_v2_privacy_hardening' },
  { alias: 'Compliance Readiness', capabilityId: 'PRIVACY_HARDENING', ownerModule: 'devpulse_v2_privacy_hardening' },
  { alias: 'Recovery Hardening', capabilityId: 'RECOVERY_HARDENING', ownerModule: 'devpulse_v2_recovery_hardening' },
  { alias: 'Recovery', capabilityId: 'RECOVERY_HARDENING', ownerModule: 'devpulse_v2_recovery_hardening' },
  { alias: 'Rollback Readiness', capabilityId: 'RECOVERY_HARDENING', ownerModule: 'devpulse_v2_recovery_hardening' },
  { alias: 'Failure Containment', capabilityId: 'RECOVERY_HARDENING', ownerModule: 'devpulse_v2_recovery_hardening' },
  { alias: 'Reset Readiness', capabilityId: 'RECOVERY_HARDENING', ownerModule: 'devpulse_v2_recovery_hardening' },
  { alias: 'Escalation Readiness', capabilityId: 'RECOVERY_HARDENING', ownerModule: 'devpulse_v2_recovery_hardening' },
  { alias: 'Disaster Recovery', capabilityId: 'RECOVERY_HARDENING', ownerModule: 'devpulse_v2_recovery_hardening' },
  { alias: 'Scale Hardening', capabilityId: 'SCALE_HARDENING', ownerModule: 'devpulse_v2_scale_hardening' },
  { alias: 'Scale', capabilityId: 'SCALE_HARDENING', ownerModule: 'devpulse_v2_scale_hardening' },
  { alias: 'Capacity Readiness', capabilityId: 'SCALE_HARDENING', ownerModule: 'devpulse_v2_scale_hardening' },
  { alias: 'Concurrency Risk', capabilityId: 'SCALE_HARDENING', ownerModule: 'devpulse_v2_scale_hardening' },
  { alias: 'Cloud Usage Readiness', capabilityId: 'SCALE_HARDENING', ownerModule: 'devpulse_v2_scale_hardening' },
  { alias: 'Queue Load', capabilityId: 'SCALE_HARDENING', ownerModule: 'devpulse_v2_scale_hardening' },
  { alias: 'Multi Project Scale', capabilityId: 'SCALE_HARDENING', ownerModule: 'devpulse_v2_scale_hardening' },
  { alias: 'Self Documentation', capabilityId: 'SELF_DOCUMENTATION', ownerModule: 'devpulse_v2_self_documentation' },
  { alias: 'Documentation', capabilityId: 'SELF_DOCUMENTATION', ownerModule: 'devpulse_v2_self_documentation' },
  { alias: 'Capability Documentation', capabilityId: 'SELF_DOCUMENTATION', ownerModule: 'devpulse_v2_self_documentation' },
  { alias: 'Module Documentation', capabilityId: 'SELF_DOCUMENTATION', ownerModule: 'devpulse_v2_self_documentation' },
  { alias: 'Dependency Documentation', capabilityId: 'SELF_DOCUMENTATION', ownerModule: 'devpulse_v2_self_documentation' },
  { alias: 'Authority Documentation', capabilityId: 'SELF_DOCUMENTATION', ownerModule: 'devpulse_v2_self_documentation' },
  { alias: 'Validation Documentation', capabilityId: 'SELF_DOCUMENTATION', ownerModule: 'devpulse_v2_self_documentation' },
  { alias: 'Founder Guides', capabilityId: 'FOUNDER_GUIDES', ownerModule: 'devpulse_v2_founder_guides' },
  { alias: 'Founder Documentation', capabilityId: 'FOUNDER_GUIDES', ownerModule: 'devpulse_v2_founder_guides' },
  { alias: 'Roadmap Guide', capabilityId: 'FOUNDER_GUIDES', ownerModule: 'devpulse_v2_founder_guides' },
  { alias: 'Checkpoint Guide', capabilityId: 'FOUNDER_GUIDES', ownerModule: 'devpulse_v2_founder_guides' },
  { alias: 'Navigation Guide', capabilityId: 'FOUNDER_GUIDES', ownerModule: 'devpulse_v2_founder_guides' },
  { alias: 'Modification Safety', capabilityId: 'FOUNDER_GUIDES', ownerModule: 'devpulse_v2_founder_guides' },
  { alias: 'Evolution Guide', capabilityId: 'FOUNDER_GUIDES', ownerModule: 'devpulse_v2_founder_guides' },
  { alias: 'User Guides', capabilityId: 'USER_GUIDES', ownerModule: 'devpulse_v2_user_guides' },
  { alias: 'User Documentation', capabilityId: 'USER_GUIDES', ownerModule: 'devpulse_v2_user_guides' },
  { alias: 'Onboarding Guide', capabilityId: 'USER_GUIDES', ownerModule: 'devpulse_v2_user_guides' },
  { alias: 'Workflow Guide', capabilityId: 'USER_GUIDES', ownerModule: 'devpulse_v2_user_guides' },
  { alias: 'Safety Guide', capabilityId: 'USER_GUIDES', ownerModule: 'devpulse_v2_user_guides' },
  { alias: 'Feature Guide', capabilityId: 'USER_GUIDES', ownerModule: 'devpulse_v2_user_guides' },
  { alias: 'Results Guide', capabilityId: 'USER_GUIDES', ownerModule: 'devpulse_v2_user_guides' },
  { alias: 'Architecture Documentation', capabilityId: 'ARCHITECTURE_DOCUMENTATION', ownerModule: 'devpulse_v2_architecture_documentation' },
  { alias: 'Architecture', capabilityId: 'ARCHITECTURE_DOCUMENTATION', ownerModule: 'devpulse_v2_architecture_documentation' },
  { alias: 'Domain Architecture', capabilityId: 'ARCHITECTURE_DOCUMENTATION', ownerModule: 'devpulse_v2_architecture_documentation' },
  { alias: 'Dependency Graph', capabilityId: 'ARCHITECTURE_DOCUMENTATION', ownerModule: 'devpulse_v2_architecture_documentation' },
  { alias: 'Integration Points', capabilityId: 'ARCHITECTURE_DOCUMENTATION', ownerModule: 'devpulse_v2_architecture_documentation' },
  { alias: 'Architecture Boundaries', capabilityId: 'ARCHITECTURE_DOCUMENTATION', ownerModule: 'devpulse_v2_architecture_documentation' },
  { alias: 'Authority Architecture', capabilityId: 'ARCHITECTURE_DOCUMENTATION', ownerModule: 'devpulse_v2_architecture_documentation' },
  { alias: 'API Documentation', capabilityId: 'API_DOCUMENTATION', ownerModule: 'devpulse_v2_api_documentation' },
  { alias: 'API Docs', capabilityId: 'API_DOCUMENTATION', ownerModule: 'devpulse_v2_api_documentation' },
  { alias: 'API Surface', capabilityId: 'API_DOCUMENTATION', ownerModule: 'devpulse_v2_api_documentation' },
  { alias: 'Interface Documentation', capabilityId: 'API_DOCUMENTATION', ownerModule: 'devpulse_v2_api_documentation' },
  { alias: 'Contract Documentation', capabilityId: 'API_DOCUMENTATION', ownerModule: 'devpulse_v2_api_documentation' },
  { alias: 'Integration APIs', capabilityId: 'API_DOCUMENTATION', ownerModule: 'devpulse_v2_api_documentation' },
  { alias: 'Command Documentation', capabilityId: 'API_DOCUMENTATION', ownerModule: 'devpulse_v2_api_documentation' },
  { alias: 'Interactive Explanations', capabilityId: 'INTERACTIVE_EXPLANATIONS', ownerModule: 'devpulse_v2_interactive_explanations' },
  { alias: 'Explanations', capabilityId: 'INTERACTIVE_EXPLANATIONS', ownerModule: 'devpulse_v2_interactive_explanations' },
  { alias: 'System Explanation', capabilityId: 'INTERACTIVE_EXPLANATIONS', ownerModule: 'devpulse_v2_interactive_explanations' },
  { alias: 'Workflow Explanation', capabilityId: 'INTERACTIVE_EXPLANATIONS', ownerModule: 'devpulse_v2_interactive_explanations' },
  { alias: 'Report Explanation', capabilityId: 'INTERACTIVE_EXPLANATIONS', ownerModule: 'devpulse_v2_interactive_explanations' },
  { alias: 'Reasoning Explanation', capabilityId: 'INTERACTIVE_EXPLANATIONS', ownerModule: 'devpulse_v2_interactive_explanations' },
  { alias: 'Next Step Guidance', capabilityId: 'INTERACTIVE_EXPLANATIONS', ownerModule: 'devpulse_v2_interactive_explanations' },
  { alias: 'Visual QA', capabilityId: 'VISUAL_QA_ENGINE', ownerModule: 'devpulse_v2_visual_qa_engine' },
  { alias: 'Visual Quality', capabilityId: 'VISUAL_QA_ENGINE', ownerModule: 'devpulse_v2_visual_qa_engine' },
  { alias: 'UI Quality', capabilityId: 'VISUAL_QA_ENGINE', ownerModule: 'devpulse_v2_visual_qa_engine' },
  { alias: 'Layout Quality', capabilityId: 'VISUAL_QA_ENGINE', ownerModule: 'devpulse_v2_visual_qa_engine' },
  { alias: 'First Impression', capabilityId: 'VISUAL_QA_ENGINE', ownerModule: 'devpulse_v2_visual_qa_engine' },
  { alias: 'Product Professionalism', capabilityId: 'VISUAL_QA_ENGINE', ownerModule: 'devpulse_v2_visual_qa_engine' },
  { alias: 'Visual Hierarchy', capabilityId: 'VISUAL_QA_ENGINE', ownerModule: 'devpulse_v2_visual_qa_engine' },
  { alias: 'UX Heuristic', capabilityId: 'UX_HEURISTIC_EVALUATOR', ownerModule: 'devpulse_v2_ux_heuristic_evaluator' },
  { alias: 'UX Heuristics', capabilityId: 'UX_HEURISTIC_EVALUATOR', ownerModule: 'devpulse_v2_ux_heuristic_evaluator' },
  { alias: 'Usability', capabilityId: 'UX_HEURISTIC_EVALUATOR', ownerModule: 'devpulse_v2_ux_heuristic_evaluator' },
  { alias: 'User Experience', capabilityId: 'UX_HEURISTIC_EVALUATOR', ownerModule: 'devpulse_v2_ux_heuristic_evaluator' },
  { alias: 'Founder Usability', capabilityId: 'UX_HEURISTIC_EVALUATOR', ownerModule: 'devpulse_v2_ux_heuristic_evaluator' },
  { alias: 'Intelligence Visibility', capabilityId: 'UX_HEURISTIC_EVALUATOR', ownerModule: 'devpulse_v2_ux_heuristic_evaluator' },
  { alias: 'Workflow Continuity', capabilityId: 'UX_HEURISTIC_EVALUATOR', ownerModule: 'devpulse_v2_ux_heuristic_evaluator' },
  { alias: 'First Impression Judge', capabilityId: 'FIRST_IMPRESSION_JUDGE', ownerModule: 'devpulse_v2_first_impression_judge' },
  { alias: 'Product Perception', capabilityId: 'FIRST_IMPRESSION_JUDGE', ownerModule: 'devpulse_v2_first_impression_judge' },
  { alias: 'Launch Readiness Perception', capabilityId: 'FIRST_IMPRESSION_JUDGE', ownerModule: 'devpulse_v2_first_impression_judge' },
  { alias: 'Premium Feel', capabilityId: 'FIRST_IMPRESSION_JUDGE', ownerModule: 'devpulse_v2_first_impression_judge' },
  { alias: 'Founder First Visit', capabilityId: 'FIRST_IMPRESSION_JUDGE', ownerModule: 'devpulse_v2_first_impression_judge' },
  { alias: 'Intelligence Perception', capabilityId: 'FIRST_IMPRESSION_JUDGE', ownerModule: 'devpulse_v2_first_impression_judge' },
  { alias: 'Trustworthiness Perception', capabilityId: 'FIRST_IMPRESSION_JUDGE', ownerModule: 'devpulse_v2_first_impression_judge' },
  { alias: 'Live Preview Gatekeeper', capabilityId: 'LIVE_PREVIEW_GATEKEEPER', ownerModule: 'devpulse_v2_live_preview_gatekeeper' },
  { alias: 'Live Preview Verification', capabilityId: 'LIVE_PREVIEW_GATEKEEPER', ownerModule: 'devpulse_v2_live_preview_gatekeeper' },
  { alias: 'Preview Gatekeeper', capabilityId: 'LIVE_PREVIEW_GATEKEEPER', ownerModule: 'devpulse_v2_live_preview_gatekeeper' },
  { alias: 'Founder Preview Verification', capabilityId: 'LIVE_PREVIEW_GATEKEEPER', ownerModule: 'devpulse_v2_live_preview_gatekeeper' },
  { alias: 'Preview Honesty', capabilityId: 'LIVE_PREVIEW_GATEKEEPER', ownerModule: 'devpulse_v2_live_preview_gatekeeper' },
  { alias: 'Preview Readiness', capabilityId: 'LIVE_PREVIEW_GATEKEEPER', ownerModule: 'devpulse_v2_live_preview_gatekeeper' },
  { alias: 'Responsive Preview', capabilityId: 'LIVE_PREVIEW_GATEKEEPER', ownerModule: 'devpulse_v2_live_preview_gatekeeper' },
  { alias: 'Auto-Polish Loop', capabilityId: 'AUTO_POLISH_LOOP', ownerModule: 'devpulse_v2_auto_polish_loop' },
  { alias: 'Polish Roadmap', capabilityId: 'AUTO_POLISH_LOOP', ownerModule: 'devpulse_v2_auto_polish_loop' },
  { alias: 'Polish Opportunities', capabilityId: 'AUTO_POLISH_LOOP', ownerModule: 'devpulse_v2_auto_polish_loop' },
  { alias: 'Production Quality', capabilityId: 'AUTO_POLISH_LOOP', ownerModule: 'devpulse_v2_auto_polish_loop' },
  { alias: 'Launch Blockers', capabilityId: 'AUTO_POLISH_LOOP', ownerModule: 'devpulse_v2_auto_polish_loop' },
  { alias: 'Product Polish', capabilityId: 'AUTO_POLISH_LOOP', ownerModule: 'devpulse_v2_auto_polish_loop' },
  { alias: 'Intelligence Polish', capabilityId: 'AUTO_POLISH_LOOP', ownerModule: 'devpulse_v2_auto_polish_loop' },
  { alias: 'Coherence Polish', capabilityId: 'AUTO_POLISH_LOOP', ownerModule: 'devpulse_v2_auto_polish_loop' },
  { alias: 'Product Experience', capabilityId: 'PRODUCT_EXPERIENCE_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_product_experience_verification_engine' },
  { alias: 'Product Coherence', capabilityId: 'PRODUCT_EXPERIENCE_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_product_experience_verification_engine' },
  { alias: 'Experience Continuity', capabilityId: 'PRODUCT_EXPERIENCE_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_product_experience_verification_engine' },
  { alias: 'Product Experience Roadmap', capabilityId: 'PRODUCT_EXPERIENCE_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_product_experience_verification_engine' },
  { alias: 'Launch Readiness Experience', capabilityId: 'PRODUCT_EXPERIENCE_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_product_experience_verification_engine' },
  { alias: 'Founder Experience', capabilityId: 'PRODUCT_EXPERIENCE_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_product_experience_verification_engine' },
  { alias: 'One Product', capabilityId: 'PRODUCT_EXPERIENCE_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_product_experience_verification_engine' },
  { alias: 'Product Reality', capabilityId: 'PRODUCT_REALITY_ORCHESTRATOR', ownerModule: 'devpulse_v2_product_reality_orchestrator' },
  { alias: 'Product Verdict', capabilityId: 'PRODUCT_REALITY_ORCHESTRATOR', ownerModule: 'devpulse_v2_product_reality_orchestrator' },
  { alias: 'Release Readiness', capabilityId: 'PRODUCT_REALITY_ORCHESTRATOR', ownerModule: 'devpulse_v2_product_reality_orchestrator' },
  { alias: 'Launch Blockers', capabilityId: 'PRODUCT_REALITY_ORCHESTRATOR', ownerModule: 'devpulse_v2_product_reality_orchestrator' },
  { alias: 'Product Reality Roadmap', capabilityId: 'PRODUCT_REALITY_ORCHESTRATOR', ownerModule: 'devpulse_v2_product_reality_orchestrator' },
  { alias: 'Founder Priority', capabilityId: 'PRODUCT_REALITY_ORCHESTRATOR', ownerModule: 'devpulse_v2_product_reality_orchestrator' },
  { alias: 'Authority Conflicts', capabilityId: 'PRODUCT_REALITY_ORCHESTRATOR', ownerModule: 'devpulse_v2_product_reality_orchestrator' },
  { alias: 'Founder Acceptance', capabilityId: 'FOUNDER_ACCEPTANCE_FRAMEWORK', ownerModule: 'devpulse_v2_founder_acceptance_framework' },
  { alias: 'Acceptance Framework', capabilityId: 'FOUNDER_ACCEPTANCE_FRAMEWORK', ownerModule: 'devpulse_v2_founder_acceptance_framework' },
  { alias: 'Founder Acceptance Dimensions', capabilityId: 'FOUNDER_ACCEPTANCE_FRAMEWORK', ownerModule: 'devpulse_v2_founder_acceptance_framework' },
  { alias: 'Acceptance Criteria', capabilityId: 'FOUNDER_ACCEPTANCE_FRAMEWORK', ownerModule: 'devpulse_v2_founder_acceptance_framework' },
  { alias: 'Founder Operational Acceptance', capabilityId: 'FOUNDER_ACCEPTANCE_FRAMEWORK', ownerModule: 'devpulse_v2_founder_acceptance_framework' },
  { alias: 'Founder Workflow', capabilityId: 'FOUNDER_WORKFLOW_VALIDATION', ownerModule: 'devpulse_v2_founder_workflow_validation' },
  { alias: 'Workflow Validation', capabilityId: 'FOUNDER_WORKFLOW_VALIDATION', ownerModule: 'devpulse_v2_founder_workflow_validation' },
  { alias: 'Workflow Friction', capabilityId: 'FOUNDER_WORKFLOW_VALIDATION', ownerModule: 'devpulse_v2_founder_workflow_validation' },
  { alias: 'Workflow Continuity', capabilityId: 'FOUNDER_WORKFLOW_VALIDATION', ownerModule: 'devpulse_v2_founder_workflow_validation' },
  { alias: 'Operational Workflow', capabilityId: 'FOUNDER_WORKFLOW_VALIDATION', ownerModule: 'devpulse_v2_founder_workflow_validation' },
  { alias: 'Founder Confidence', capabilityId: 'FOUNDER_CONFIDENCE_ENGINE', ownerModule: 'devpulse_v2_founder_confidence_engine' },
  { alias: 'Confidence Engine', capabilityId: 'FOUNDER_CONFIDENCE_ENGINE', ownerModule: 'devpulse_v2_founder_confidence_engine' },
  { alias: 'Progress Truth', capabilityId: 'FOUNDER_CONFIDENCE_ENGINE', ownerModule: 'devpulse_v2_founder_confidence_engine' },
  { alias: 'Reasoning Visibility', capabilityId: 'FOUNDER_CONFIDENCE_ENGINE', ownerModule: 'devpulse_v2_founder_confidence_engine' },
  { alias: 'Understanding Confidence', capabilityId: 'FOUNDER_CONFIDENCE_ENGINE', ownerModule: 'devpulse_v2_founder_confidence_engine' },
  { alias: 'Founder Trust', capabilityId: 'FOUNDER_TRUST_VALIDATION', ownerModule: 'devpulse_v2_founder_trust_validation' },
  { alias: 'Trust Validation', capabilityId: 'FOUNDER_TRUST_VALIDATION', ownerModule: 'devpulse_v2_founder_trust_validation' },
  { alias: 'Truthfulness Trust', capabilityId: 'FOUNDER_TRUST_VALIDATION', ownerModule: 'devpulse_v2_founder_trust_validation' },
  { alias: 'Transparency Trust', capabilityId: 'FOUNDER_TRUST_VALIDATION', ownerModule: 'devpulse_v2_founder_trust_validation' },
  { alias: 'Governance Trust', capabilityId: 'FOUNDER_TRUST_VALIDATION', ownerModule: 'devpulse_v2_founder_trust_validation' },
  { alias: 'Founder Productivity', capabilityId: 'FOUNDER_PRODUCTIVITY_VALIDATION', ownerModule: 'devpulse_v2_founder_productivity_validation' },
  { alias: 'Productivity Validation', capabilityId: 'FOUNDER_PRODUCTIVITY_VALIDATION', ownerModule: 'devpulse_v2_founder_productivity_validation' },
  { alias: 'Workflow Acceleration', capabilityId: 'FOUNDER_PRODUCTIVITY_VALIDATION', ownerModule: 'devpulse_v2_founder_productivity_validation' },
  { alias: 'Manual Work Reduction', capabilityId: 'FOUNDER_PRODUCTIVITY_VALIDATION', ownerModule: 'devpulse_v2_founder_productivity_validation' },
  { alias: 'Throughput Productivity', capabilityId: 'FOUNDER_PRODUCTIVITY_VALIDATION', ownerModule: 'devpulse_v2_founder_productivity_validation' },
  { alias: 'Founder Friction', capabilityId: 'FOUNDER_FRICTION_DETECTOR', ownerModule: 'devpulse_v2_founder_friction_detector' },
  { alias: 'Friction Detector', capabilityId: 'FOUNDER_FRICTION_DETECTOR', ownerModule: 'devpulse_v2_founder_friction_detector' },
  { alias: 'Decision Fatigue', capabilityId: 'FOUNDER_FRICTION_DETECTOR', ownerModule: 'devpulse_v2_founder_friction_detector' },
  { alias: 'Launch Blocker Friction', capabilityId: 'FOUNDER_FRICTION_DETECTOR', ownerModule: 'devpulse_v2_founder_friction_detector' },
  { alias: 'Discoverability Friction', capabilityId: 'FOUNDER_FRICTION_DETECTOR', ownerModule: 'devpulse_v2_founder_friction_detector' },
  { alias: 'Founder Readiness', capabilityId: 'FOUNDER_READINESS_AUTHORITY', ownerModule: 'devpulse_v2_founder_readiness_authority' },
  { alias: 'Readiness Authority', capabilityId: 'FOUNDER_READINESS_AUTHORITY', ownerModule: 'devpulse_v2_founder_readiness_authority' },
  { alias: 'Launch Readiness', capabilityId: 'FOUNDER_READINESS_AUTHORITY', ownerModule: 'devpulse_v2_founder_readiness_authority' },
  { alias: 'Operational Readiness', capabilityId: 'FOUNDER_READINESS_AUTHORITY', ownerModule: 'devpulse_v2_founder_readiness_authority' },
  { alias: 'Founder Launch Ready', capabilityId: 'FOUNDER_READINESS_AUTHORITY', ownerModule: 'devpulse_v2_founder_readiness_authority' },
  { alias: 'Founder Acceptance', capabilityId: 'FOUNDER_ACCEPTANCE_ORCHESTRATOR', ownerModule: 'devpulse_v2_founder_acceptance_orchestrator' },
  { alias: 'Acceptance Orchestrator', capabilityId: 'FOUNDER_ACCEPTANCE_ORCHESTRATOR', ownerModule: 'devpulse_v2_founder_acceptance_orchestrator' },
  { alias: 'Founder Accepts', capabilityId: 'FOUNDER_ACCEPTANCE_ORCHESTRATOR', ownerModule: 'devpulse_v2_founder_acceptance_orchestrator' },
  { alias: 'Acceptance Verdict', capabilityId: 'FOUNDER_ACCEPTANCE_ORCHESTRATOR', ownerModule: 'devpulse_v2_founder_acceptance_orchestrator' },
  { alias: 'Launch Acceptance', capabilityId: 'FOUNDER_ACCEPTANCE_ORCHESTRATOR', ownerModule: 'devpulse_v2_founder_acceptance_orchestrator' },
  { alias: 'Verification Integration', capabilityId: 'VERIFICATION_INTEGRATION', ownerModule: 'devpulse_v2_verification_integration' },
  { alias: 'Verification Readiness', capabilityId: 'VERIFICATION_INTEGRATION', ownerModule: 'devpulse_v2_verification_integration' },
  { alias: 'Verification Snapshot', capabilityId: 'VERIFICATION_INTEGRATION', ownerModule: 'devpulse_v2_verification_integration' },
  { alias: 'Verification Intelligence', capabilityId: 'VERIFICATION_INTELLIGENCE', ownerModule: 'devpulse_v2_verification_intelligence' },
  { alias: 'Verification Plan', capabilityId: 'VERIFICATION_INTELLIGENCE', ownerModule: 'devpulse_v2_verification_intelligence' },
  { alias: 'Verification Execution Order', capabilityId: 'VERIFICATION_INTELLIGENCE', ownerModule: 'devpulse_v2_verification_intelligence' },
  { alias: 'Verification Strategy', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Verification Strategy Core', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Verification Depth', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Verification Escalation', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Trust Recovery Verification', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Build Strategy', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Strategy Engine', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Strategy Inventory', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Strategy Planning', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Mode', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Autonomy Level', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Risk', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Confidence', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Depth', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Stage Recommendation', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Policy', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Classify Build', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Strategy Classification', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Strategy Diagnostics', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Autonomous Builder', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Autonomous Builder Foundation', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Autonomous Build Inventory', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Planning', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Goal', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Plan', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Stage', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Readiness', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Constraint', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Capability', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Diagnostics', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Mobile Push', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Mobile Push Foundation', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Mobile Push Inventory', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Planning', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Routing', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Targeting', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Eligibility', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Payload', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Token Metadata', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Platform', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Policy', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Blocking', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Deferral', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Diagnostics', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
] as const;

export function resolveFindPanelAlias(query: string): FindPanelAlias | null {
  const lower = query.toLowerCase().trim();
  return WORLD2_BUILDER_PACKET_FIND_ALIASES.find((a) => lower.includes(a.alias.toLowerCase())) ?? null;
}
