/**
 * Find Panel alias registry — searchable aliases for intelligence modules.
 */

export interface FindPanelAlias {
  alias: string;
  capabilityId: string;
  ownerModule: string;
}

export const WORLD2_BUILDER_PACKET_FIND_ALIASES: readonly FindPanelAlias[] = [
  { alias: 'Builder Packet Execution', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'World 2 Builder Packet', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'Execution Packet', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'Packet Readiness', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'Builder Packet Approval', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'World 2 Build Preparation', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', ownerModule: 'devpulse_v2_world2_builder_packet_execution' },
  { alias: 'Controlled Apply', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Apply Plan', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'World 2 Apply', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Apply Readiness', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Apply Approval', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Future Apply', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', ownerModule: 'devpulse_v2_world2_controlled_apply_runtime' },
  { alias: 'Rollback Runtime', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'World 2 Rollback', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Rollback Plan', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Rollback Safety', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Snapshot Requirement', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Change Reversal', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', ownerModule: 'devpulse_v2_world2_rollback_runtime' },
  { alias: 'Recovery Runtime', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'World 2 Recovery', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Recovery Plan', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Failure Recovery', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Recovery Strategy', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Self Evolution Escalation', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Three Failure Rule', capabilityId: 'WORLD2_RECOVERY_RUNTIME', ownerModule: 'devpulse_v2_world2_recovery_runtime' },
  { alias: 'Completion Runtime', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'World 2 Completion', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Completion Plan', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Completion Criteria', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Completion Evidence', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Project Done', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Verification Required', capabilityId: 'WORLD2_COMPLETION_RUNTIME', ownerModule: 'devpulse_v2_world2_completion_runtime' },
  { alias: 'Live Preview', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Runtime', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Session', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Target', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Ready', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Blocked', capabilityId: 'LIVE_PREVIEW_RUNTIME', ownerModule: 'devpulse_v2_live_preview_runtime' },
  { alias: 'Preview Intelligence', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Preview Readiness', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Preview Capabilities', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Preview Limitations', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Observation Plan', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Self Vision Preparation', capabilityId: 'PREVIEW_INTELLIGENCE', ownerModule: 'devpulse_v2_preview_intelligence' },
  { alias: 'Self Vision', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Self Vision Runtime', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Observation Session', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Observation Targets', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Capture Plan', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'Vision Ready', capabilityId: 'SELF_VISION_RUNTIME', ownerModule: 'devpulse_v2_self_vision_runtime' },
  { alias: 'UI Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Layout Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Navigation Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Loading Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Responsive Inspection', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Inspection Ready', capabilityId: 'UI_INSPECTION_ENGINE', ownerModule: 'devpulse_v2_ui_inspection_engine' },
  { alias: 'Interaction Testing', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Button Testing', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Navigation Testing', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Workflow Testing', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Interaction Results', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Interaction Ready', capabilityId: 'INTERACTION_TESTING_ENGINE', ownerModule: 'devpulse_v2_interaction_testing_engine' },
  { alias: 'Visual Verification', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Results', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Evidence', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Risks', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Ready', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'Verification Failed', capabilityId: 'VISUAL_VERIFICATION_ENGINE', ownerModule: 'devpulse_v2_visual_verification_engine' },
  { alias: 'UVL Runtime', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Unified Verification Lab', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Verification Runtime', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Verification Providers', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Verification Sessions', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', ownerModule: 'devpulse_v2_unified_verification_lab_runtime' },
  { alias: 'Verification Registry', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Targets', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Dependencies', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Requirements', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Owners', capabilityId: 'VERIFICATION_REGISTRY', ownerModule: 'devpulse_v2_verification_registry' },
  { alias: 'Verification Orchestrator', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Verification Plan', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Execution Order', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Parallel Verification', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Blocked Verification', capabilityId: 'VERIFICATION_ORCHESTRATOR', ownerModule: 'devpulse_v2_verification_orchestrator' },
  { alias: 'Evidence Engine', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Evidence Inventory', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Evidence Lineage', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Evidence Ownership', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Evidence Traceability', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Verification Evidence Authority', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', ownerModule: 'devpulse_v2_verification_evidence_engine' },
  { alias: 'Verification Reports', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Reporting', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification History', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Trends', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Summary', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Failures', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Verification Evidence Reports', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Founder Verification Reports', capabilityId: 'VERIFICATION_REPORTING_ENGINE', ownerModule: 'devpulse_v2_verification_reporting_engine' },
  { alias: 'Unified Verification', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification Entry', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification Requests', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification Sessions', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification State', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification History', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Verification Responses', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', ownerModule: 'devpulse_v2_unified_verification_entry' },
  { alias: 'Cloud Runtime', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime Inventory', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime Lifecycle', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime State', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime Sessions', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime Ownership', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Runtime History', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Cloud Runtime Diagnostics', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cloud_runtime_foundation' },
  { alias: 'Workspace Hosting', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Hosted Workspaces', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Inventory', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Lifecycle', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace State', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Sessions', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Ownership', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Isolation', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Runtime Links', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Workspace Diagnostics', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', ownerModule: 'devpulse_v2_workspace_hosting_foundation' },
  { alias: 'Persistent Build Runtime', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Persistent Builds', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Sessions', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build State', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Progress', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Context', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Resume', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Runtime Links', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Workspace Links', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build History', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Build Diagnostics', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_persistent_build_runtime_foundation' },
  { alias: 'Cloud Verification', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Requests', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Sessions', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification State', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Scope', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Context', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Evidence', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Reports', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Runtime Links', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Workspace Links', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Build Links', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Verification Diagnostics', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', ownerModule: 'devpulse_v2_cloud_verification_foundation' },
  { alias: 'Cloud Recovery', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Candidates', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Plans', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Sessions', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery State', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Context', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Runtime Links', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Workspace Links', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Build Links', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Verification Links', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Recovery Diagnostics', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', ownerModule: 'devpulse_v2_cloud_recovery_foundation' },
  { alias: 'Cloud Monitoring', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Health', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Alerts', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Sessions', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Context', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Runtime Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Workspace Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Build Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Verification Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Recovery Links', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Monitoring Diagnostics', capabilityId: 'CLOUD_MONITORING_FOUNDATION', ownerModule: 'devpulse_v2_cloud_monitoring_foundation' },
  { alias: 'Mobile Command Runtime', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Sessions', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command State', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Context', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Permissions', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Action Gate', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Cloud Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Workspace Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Build Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Verification Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Recovery Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Monitoring Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Operator Feed Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Project Vault Links', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Command Diagnostics', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_command_runtime_foundation' },
  { alias: 'Mobile Chat Runtime', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Sessions', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Messages', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Prompts', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Responses', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Routing', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Action Gate', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Context', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Cloud Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Workspace Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Build Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Verification Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Monitoring Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Operator Feed Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Project Vault Links', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Chat Diagnostics', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation' },
  { alias: 'Mobile Preview Runtime', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Sessions', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Eligibility', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Safety', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Device Policy', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Desktop Recommendation', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview State', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Command Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Chat Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Cloud Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Workspace Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Build Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Verification Links', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Preview Diagnostics', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation' },
  { alias: 'Mobile Approval Runtime', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Sessions', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Requests', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Decisions', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Visibility', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval State', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Command Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Chat Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Preview Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval World2 Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval AiDev Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Cloud Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Project Vault Links', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Mobile Approval Diagnostics', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation' },
  { alias: 'Cross Device Runtime', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Sessions', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Inventory', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Device Registration', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Device Link', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Device Handoff', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Device Visibility', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device State', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Command Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Chat Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Preview Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Approval Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Cloud Links', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Cross Device Diagnostics', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_cross_device_runtime_foundation' },
  { alias: 'Founder Notification Runtime', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Founder Notifications', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Founder Notification Inventory', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Founder Alert', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Routing', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Visibility', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Priority', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Channel', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification State', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Lifecycle', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Notification Diagnostics', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', ownerModule: 'devpulse_v2_founder_notification_runtime_foundation' },
  { alias: 'Founder Inbox', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Founder Inbox Foundation', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Founder Inbox Inventory', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Visualization', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Filter', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Search', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Grouping', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Archive', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Acknowledgement', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Inbox Diagnostics', capabilityId: 'FOUNDER_INBOX_FOUNDATION', ownerModule: 'devpulse_v2_founder_inbox_foundation' },
  { alias: 'Notification Delivery', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Notification Delivery Foundation', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Notification Delivery Inventory', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Planning', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Routing', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Targeting', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Eligibility', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Policy', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Blocking', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Deferral', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Delivery Diagnostics', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', ownerModule: 'devpulse_v2_notification_delivery_foundation' },
  { alias: 'Verification Intelligence', capabilityId: 'VERIFICATION_INTELLIGENCE', ownerModule: 'devpulse_v2_verification_intelligence' },
  { alias: 'Verification Plan', capabilityId: 'VERIFICATION_INTELLIGENCE', ownerModule: 'devpulse_v2_verification_intelligence' },
  { alias: 'Verification Execution Order', capabilityId: 'VERIFICATION_INTELLIGENCE', ownerModule: 'devpulse_v2_verification_intelligence' },
  { alias: 'Verification Strategy', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Verification Strategy Core', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Verification Depth', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Verification Escalation', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Trust Recovery Verification', capabilityId: 'VERIFICATION_STRATEGY_CORE', ownerModule: 'devpulse_v2_verification_strategy_core' },
  { alias: 'Build Strategy', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Strategy Engine', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Strategy Inventory', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Strategy Planning', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Mode', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Autonomy Level', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Risk', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Confidence', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Depth', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Stage Recommendation', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Policy', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Classify Build', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Strategy Classification', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Build Strategy Diagnostics', capabilityId: 'BUILD_STRATEGY_ENGINE', ownerModule: 'devpulse_v2_build_strategy_engine' },
  { alias: 'Autonomous Builder', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Autonomous Builder Foundation', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Autonomous Build Inventory', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Planning', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Goal', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Plan', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Stage', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Readiness', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Constraint', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Capability', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Build Diagnostics', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', ownerModule: 'devpulse_v2_autonomous_builder_foundation' },
  { alias: 'Mobile Push', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Mobile Push Foundation', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Mobile Push Inventory', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Planning', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Routing', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Targeting', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Eligibility', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Payload', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Token Metadata', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Platform', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Policy', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Blocking', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Deferral', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
  { alias: 'Push Diagnostics', capabilityId: 'MOBILE_PUSH_FOUNDATION', ownerModule: 'devpulse_v2_mobile_push_foundation' },
] as const;

export function resolveFindPanelAlias(query: string): FindPanelAlias | null {
  const lower = query.toLowerCase().trim();
  return WORLD2_BUILDER_PACKET_FIND_ALIASES.find((a) => lower.includes(a.alias.toLowerCase())) ?? null;
}
