/**
 * Post-Launch Reality Authority — markdown report builder.
 */

import {
  POST_LAUNCH_REALITY_AUTHORITY_PASS_TOKEN,
  POST_LAUNCH_REALITY_AUTHORITY_PHASE,
  POST_LAUNCH_REALITY_AUTHORITY_REPORT_TITLE,
  POST_LAUNCH_REALITY_CORE_QUESTION,
  SAFETY_GUARANTEES,
} from './post-launch-reality-registry.js';
import type { PostLaunchRealityReport } from './post-launch-reality-types.js';

export function buildPostLaunchRealityReportMarkdown(report: PostLaunchRealityReport): string {
  const lines: string[] = [
    `# ${POST_LAUNCH_REALITY_AUTHORITY_REPORT_TITLE}`,
    '',
    `Generated: ${report.generatedAt}`,
    '',
    '## Phase',
    '',
    POST_LAUNCH_REALITY_AUTHORITY_PHASE,
    '',
    '## Core Question',
    '',
    POST_LAUNCH_REALITY_CORE_QUESTION,
    '',
    '# Post-Launch Reality Authority',
    '',
    '## Post-Launch State',
    '',
    `**${report.postLaunchRealityState}**`,
    '',
    '## Overall Score',
    '',
    `${report.overallPostLaunchScore}/100 (confidence: ${report.confidence}/100)`,
    '',
    '## Traffic Analysis',
    '',
    `- traffic observed: ${report.traffic.trafficObserved ? 'YES' : 'NO'}`,
    `- sessions: ${report.traffic.sessionsObserved ?? 'UNKNOWN'}`,
    `- users: ${report.traffic.usersObserved ?? 'UNKNOWN'}`,
    `- trend: ${report.traffic.trend}`,
    `- traffic score: ${report.trafficScore}/100`,
    `- confidence: ${report.traffic.trafficConfidence}`,
    '',
    '## Engagement Analysis',
    '',
    `- active usage: ${report.engagement.activeUsage ? 'YES' : 'NO'}`,
    `- feature usage: ${report.engagement.featureUsage ? 'YES' : 'NO'}`,
    `- session quality: ${report.engagement.sessionQuality ?? 'UNKNOWN'}`,
    `- user return signals: ${report.engagement.userReturnSignals ? 'YES' : 'NO'}`,
    `- engagement score: ${report.engagementScore}/100`,
    '',
    '## Retention Analysis',
    '',
    `- repeat users: ${report.retention.repeatUsers ? 'YES' : 'NO'}`,
    `- repeat user count: ${report.retention.repeatUserCount ?? 'UNKNOWN'}`,
    `- retention signals: ${report.retention.retentionSignals ? 'YES' : 'NO'}`,
    `- retention score: ${report.retentionScore}/100`,
    '',
    '## Reliability Analysis',
    '',
    `- operational stability: ${report.reliability.operationalStability ? 'YES' : 'NO'}`,
    `- uptime: ${report.reliability.uptimePercent ?? 'UNKNOWN'}%`,
    `- runtime errors: ${report.reliability.runtimeErrors ? 'YES' : 'NO'}`,
    `- crash evidence: ${report.reliability.crashEvidence ? 'YES' : 'NO'}`,
    `- reliability score: ${report.reliabilityScore}/100`,
    '',
    '## Business Outcome Analysis',
    '',
    `- customer value evidence: ${report.businessOutcome.customerValueEvidence ? 'YES' : 'NO'}`,
    `- founder goal progress: ${report.businessOutcome.founderGoalProgress ? 'YES' : 'NO'}`,
    `- monetization evidence: ${report.businessOutcome.monetizationEvidence ? 'YES' : 'NO'}`,
    `- product impact evidence: ${report.businessOutcome.productImpactEvidence ? 'YES' : 'NO'}`,
    `- business outcome score: ${report.businessOutcomeScore}/100`,
    '',
    '## Observed Reality',
    '',
    `- activity observed: ${report.activityObserved ? 'YES' : 'NO'}`,
    `- retention observed: ${report.retentionObserved ? 'YES' : 'NO'}`,
    `- business value observed: ${report.businessValueObserved ? 'YES' : 'NO'}`,
    '',
    ...report.keyFindings.map((f) => `- ${f}`),
    '',
    '## Missing Evidence',
    '',
    ...report.missingEvidence.map((m) => `- ${m}`),
    ...(report.missingEvidence.length === 0 ? ['- none reported'] : []),
    '',
    '## Risk Signals',
    '',
    ...report.riskSignals.map((r) => `- ${r}`),
    ...(report.riskSignals.length === 0 ? ['- none identified'] : []),
    '',
    '## Recommended Actions',
    '',
    ...report.recommendedActions.map((a) => `- ${a}`),
    ...(report.recommendedActions.length === 0 ? ['- none'] : []),
    '',
    '## Final Verdict',
    '',
    report.finalVerdict,
    '',
    '## Safety',
    '',
    ...SAFETY_GUARANTEES.map((g) => `- ${g}`),
    '',
    '## Pass Token',
    '',
    POST_LAUNCH_REALITY_AUTHORITY_PASS_TOKEN,
  ];

  return lines.join('\n');
}

export function formatPostLaunchRealitySummary(report: PostLaunchRealityReport): string {
  return (
    `Post-Launch Reality: ${report.postLaunchRealityState} — ` +
    `score ${report.overallPostLaunchScore}/100, activity=${report.activityObserved}.`
  );
}
