/**
 * Founder Test Automation — registry constants (V1).
 */

export const FOUNDER_TEST_AUTOMATION_V1_PASS = 'FOUNDER_TEST_AUTOMATION_V1_PASS';

export const FOUNDER_TEST_AUTOMATION_OWNER_MODULE = 'founder-test-automation';

export const FOUNDER_TEST_AUTOMATION_PHASE = '26.26';

export const FOUNDER_TEST_AUTOMATION_REPORT_TITLE = 'Founder Test Automation Report';

export const MAX_FOUNDER_TEST_AUTOMATION_HISTORY = 32;

export const BLOCKER_PRIORITIES = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as const;

export const EXECUTION_READINESS_STATES = [
  'NOT_READY',
  'HIGH_RISK',
  'READY_WITH_ACTIONS',
  'READY_FOR_EXECUTION',
] as const;

export const RECOMMENDATION_GROUPS = [
  'PRODUCT',
  'UX',
  'ARCHITECTURE',
  'DATA',
  'AUTHENTICATION',
  'PAYMENTS',
  'INTEGRATIONS',
  'LAUNCH',
  'FOUNDER_EXPERIENCE',
] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_INTELLIGENCE',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MODIFICATION',
  'NO_AUTONOMOUS_EXECUTION',
  'NO_PLANNING_EXECUTION',
  'EVIDENCE_BASED_OUTPUTS_ONLY',
  'BOUNDED_ANALYSIS_HISTORY',
] as const;

export const CATEGORY_TO_RECOMMENDATION_GROUP: Record<string, string> = {
  EXECUTION_REALITY: 'ARCHITECTURE',
  FOUNDER_EXPERIENCE: 'FOUNDER_EXPERIENCE',
  FIRST_TIME_USER_EXPERIENCE: 'UX',
  NAVIGATION_REALITY: 'UX',
  LIVE_PREVIEW_REALITY: 'PRODUCT',
  VERIFICATION_REALITY: 'ARCHITECTURE',
  AI_INTERACTION_REALITY: 'FOUNDER_EXPERIENCE',
  MISSING_CAPABILITY_REALITY: 'PRODUCT',
  LAUNCH_RISK_REALITY: 'LAUNCH',
  COMPETITIVE_REALITY: 'PRODUCT',
};

export const PRIORITY_IMPACT_WEIGHTS = {
  CRITICAL: { launch: 95, user: 90, founder: 92 },
  HIGH: { launch: 75, user: 70, founder: 72 },
  MEDIUM: { launch: 50, user: 48, founder: 45 },
  LOW: { launch: 25, user: 22, founder: 20 },
} as const;
