/**
 * Strategic Defensibility Reality Authority — markdown report builder.
 */

import {
  STRATEGIC_DEFENSIBILITY_REALITY_AUTHORITY_PASS_TOKEN,
  STRATEGIC_DEFENSIBILITY_REALITY_AUTHORITY_PHASE,
  STRATEGIC_DEFENSIBILITY_REALITY_AUTHORITY_REPORT_TITLE,
  STRATEGIC_DEFENSIBILITY_REALITY_CORE_QUESTION,
  SAFETY_GUARANTEES,
} from './strategic-defensibility-registry.js';
import type { StrategicDefensibilityRealityReport } from './strategic-defensibility-types.js';

export function buildStrategicDefensibilityRealityReportMarkdown(
  report: StrategicDefensibilityRealityReport,
): string {
  const lines: string[] = [
    `# ${STRATEGIC_DEFENSIBILITY_REALITY_AUTHORITY_REPORT_TITLE}`,
    '',
    `Generated: ${report.generatedAt}`,
    '',
    '## Phase',
    '',
    STRATEGIC_DEFENSIBILITY_REALITY_AUTHORITY_PHASE,
    '',
    '## Core Question',
    '',
    STRATEGIC_DEFENSIBILITY_REALITY_CORE_QUESTION,
    '',
    '# Strategic Defensibility Reality Authority',
    '',
    '## Defensibility State',
    '',
    `**${report.strategicDefensibilityState}**`,
    '',
    '## Overall Defensibility Score',
    '',
    `${report.overallDefensibilityScore}/100 (confidence: ${report.confidence}/100)`,
    '',
    '## Network Effects Analysis',
    '',
    `- user network value: ${report.networkEffects.userNetworkValue ? 'YES' : 'NO'}`,
    `- network reinforcement signals: ${report.networkEffects.networkReinforcementSignals ? 'YES' : 'NO'}`,
    `- community dependency: ${report.networkEffects.communityDependency ? 'YES' : 'NO'}`,
    `- network effects score: ${report.networkEffectsScore}/100`,
    '',
    '## Data Advantage Analysis',
    '',
    `- unique data assets: ${report.dataAdvantage.uniqueDataAssets ? 'YES' : 'NO'}`,
    `- learning advantages: ${report.dataAdvantage.learningAdvantages ? 'YES' : 'NO'}`,
    `- data flywheel signals: ${report.dataAdvantage.dataFlywheelSignals ? 'YES' : 'NO'}`,
    `- data advantage score: ${report.dataAdvantageScore}/100`,
    '',
    '## Switching Cost Analysis',
    '',
    `- customer lock-in signals: ${report.switchingCost.customerLockInSignals ? 'YES' : 'NO'}`,
    `- workflow dependency: ${report.switchingCost.workflowDependency ? 'YES' : 'NO'}`,
    `- replacement resistance: ${report.switchingCost.replacementResistance ? 'YES' : 'NO'}`,
    `- switching cost score: ${report.switchingCostScore}/100`,
    '',
    '## Brand Trust Analysis',
    '',
    `- customer trust signals: ${report.brandTrust.customerTrustSignals ? 'YES' : 'NO'}`,
    `- brand preference evidence: ${report.brandTrust.brandPreferenceEvidence ? 'YES' : 'NO'}`,
    `- trust durability: ${report.brandTrust.trustDurability ? 'YES' : 'NO'}`,
    `- brand trust score: ${report.brandTrustScore}/100`,
    '',
    '## Distribution Advantage Analysis',
    '',
    `- distribution reach: ${report.distributionAdvantage.distributionReach ? 'YES' : 'NO'}`,
    `- channel strength: ${report.distributionAdvantage.channelStrength ? 'YES' : 'NO'}`,
    `- distribution score: ${report.distributionScore}/100`,
    '',
    '## Execution Advantage Analysis',
    '',
    `- improvement velocity: ${report.executionAdvantage.improvementVelocity ? 'YES' : 'NO'}`,
    `- adaptation speed: ${report.executionAdvantage.adaptationSpeed ? 'YES' : 'NO'}`,
    `- innovation signals: ${report.executionAdvantage.innovationSignals ? 'YES' : 'NO'}`,
    `- execution advantage score: ${report.executionAdvantageScore}/100`,
    '',
    '## Defensibility Risks',
    '',
    `- defensibility risk score: ${report.defensibilityRiskScore}/100`,
    ...report.defensibilityRisk.riskSignals.map((r) => `- ${r}`),
    ...(report.defensibilityRisk.riskSignals.length === 0 ? ['- no significant defensibility risks identified'] : []),
    '',
    '## Missing Evidence',
    '',
    ...report.missingEvidence.map((m) => `- ${m}`),
    ...(report.missingEvidence.length === 0 ? ['- none identified'] : []),
    '',
    '## Recommended Actions',
    '',
    ...report.recommendedActions.map((a) => `- ${a}`),
    '',
    '## Final Verdict',
    '',
    report.finalVerdict,
    '',
    '## Safety Guarantees',
    '',
    ...SAFETY_GUARANTEES.map((g) => `- ${g}`),
    '',
    '## Pass Token',
    '',
    STRATEGIC_DEFENSIBILITY_REALITY_AUTHORITY_PASS_TOKEN,
  ];

  return lines.join('\n');
}

export function formatStrategicDefensibilityRealitySummary(
  report: StrategicDefensibilityRealityReport,
): string {
  return `${report.strategicDefensibilityState} (${report.overallDefensibilityScore}/100)`;
}
