/**
 * Mobile Runtime Validation at Scale V1 — bounds and pass token.
 */

export const MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_PASS_TOKEN =
  'MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_PASS';

export const MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_FAIL_TOKEN =
  'MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_FAIL';

export const MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_REPORT_TITLE =
  'MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_REPORT.md';

export const MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_ARTIFACT_DIR =
  '.mobile-runtime-validation-at-scale-v1';

export const MIN_MOBILE_CATEGORY_COUNT = 10;

export const MIN_MOBILE_WORLD2_EXECUTIONS = 3;

export const MIN_MOBILE_PASS_RATE = 100;

export const MOBILE_RUNTIME_PROFILE_IDS = [
  'ANDROID_PHONE',
  'ANDROID_TABLET',
  'IPHONE',
  'IPAD',
] as const;

export const MOBILE_VALIDATION_SUITE_PROFILES = [
  'TASK_TRACKER_WEB_V1',
  'CRM_WEB_V1',
  'INVENTORY_WEB_V1',
  'SCHOOL_MANAGEMENT_WEB_V1',
  'PROJECT_MANAGEMENT_WEB_V1',
  'MARKETPLACE_WEB_V1',
  'APPOINTMENT_BOOKING_WEB_V1',
  'LEARNING_PLATFORM_WEB_V1',
  'CUSTOMER_SUPPORT_WEB_V1',
  'FINANCE_TRACKER_WEB_V1',
] as const;

export const MOBILE_WORLD2_PROFILES = [
  'TASK_TRACKER_WEB_V1',
  'CRM_WEB_V1',
  'MARKETPLACE_WEB_V1',
] as const;

export const PRIOR_PASS_TOKENS = [
  'WORLD2_REAL_INSTANTIATION_V1_PASS',
  'LARGE_SCALE_PIPELINE_INTEGRATION_V1_PASS',
  'CLOUD_EXECUTION_PATH_V1_PASS',
  'PRODUCTION_READINESS_GATE_V1_PASS',
  'GENERAL_PURPOSE_CODE_GENERATION_V1_PASS',
  'UVL_VERIFICATION_EXECUTION_V1_PASS',
  'REAL_BUILD_EXECUTION_PIPELINE_V1_1_PASS',
  'AIDEVENGINE_CAPABILITY_AUDIT_V3_1_PASS',
] as const;
