export {
  PROJECT_REGISTRY_DUPLICATE_NAME_CODE,
  PROJECT_REGISTRY_DUPLICATES_REPAIRED,
  PROJECT_REGISTRY_LOADED,
  PROJECT_REGISTRY_PROJECT_PERSISTED,
  PROJECT_REGISTRY_TEST_ROOT_SEGMENT,
  PROJECT_REGISTRY_V1_PASS_TOKEN,
  ProjectRegistryDuplicateNameError,
  type ProjectRegistryDuplicateRepairResult,
  type ProjectRegistryFile,
  type ProjectRegistryRecord,
  type ProjectRegistryStatus,
  type ProjectRegistrySummary,
  type ProjectRegistrySummaryItem,
} from './project-registry-v1-types.js';

export {
  archiveRegistryProject,
  bootstrapProjectRegistryV1,
  buildProjectRegistrySummary,
  buildProjectRegistrySummaryFast,
  buildProjectRegistrySummaryFromState,
  createProjectRegistryTestRoot,
  createRegistryProject,
  getProjectRegistryOperatorLogPath,
  getProjectRegistryV1FilePath,
  getRegistryProject,
  invalidateProjectRegistryV1Cache,
  isProjectRegistryTestRoot,
  loadProjectRegistryV1,
  repairDuplicateActiveProjects,
  readProjectRegistryState,
  renameRegistryProject,
  resetProjectRegistryV1ForTests,
  resolveProjectRegistryRootDir,
  setDefaultProjectRegistryRootDir,
  setRegistryActiveProject,
  validateCreateRegistryProjectName,
  writeProjectRegistryV1ForTests,
} from './project-registry-v1-store.js';
