/**
 * Production Observability Platform V1 — bounds and pass token.
 */

export const PRODUCTION_OBSERVABILITY_PLATFORM_V1_PASS_TOKEN =
  'PRODUCTION_OBSERVABILITY_PLATFORM_V1_PASS';

export const PRODUCTION_OBSERVABILITY_PLATFORM_V1_FAIL_TOKEN =
  'PRODUCTION_OBSERVABILITY_PLATFORM_V1_FAIL';

export const PRODUCTION_OBSERVABILITY_PLATFORM_V1_REPORT_TITLE =
  'PRODUCTION_OBSERVABILITY_PLATFORM_V1_REPORT.md';

export const PRODUCTION_OBSERVABILITY_PLATFORM_V1_ARTIFACT_DIR =
  '.production-observability-platform-v1';

export const MAX_INCIDENT_REGISTRY_SIZE = 1000;

export const MIN_APPLICATIONS_OBSERVED = 5;

export const MIN_DEPLOYMENTS_TRACKED = 5;

export const MIN_INCIDENTS_PROCESSED = 3;

export const MIN_RECOVERY_RECOMMENDATIONS = 2;

export const MAX_TENANT_OBSERVABILITY_VIOLATIONS = 0;

export const PRIOR_PASS_TOKENS = [
  'CUSTOMER_OPERATIONS_PLATFORM_V1_PASS',
  'STRATEGIC_CAPABILITY_AUDIT_V4_PASS',
  'PRODUCTION_READINESS_GATE_V1_PASS',
  'CLOUD_EXECUTION_PATH_V1_PASS',
  'UNIFIED_FAILURE_ESCALATION_AUTHORITY_V1_PASS',
  'CANONICAL_OWNERSHIP_V2_PASS',
] as const;
