/**
 * Multi-Project Concurrent Execution V1 — bounds and pass token.
 */

export const MULTI_PROJECT_CONCURRENT_EXECUTION_V1_PASS_TOKEN =
  'MULTI_PROJECT_CONCURRENT_EXECUTION_V1_PASS';

export const MULTI_PROJECT_CONCURRENT_EXECUTION_V1_FAIL_TOKEN =
  'MULTI_PROJECT_CONCURRENT_EXECUTION_V1_FAIL';

export const MULTI_PROJECT_CONCURRENT_EXECUTION_V1_REPORT_TITLE =
  'MULTI_PROJECT_CONCURRENT_EXECUTION_V1_REPORT.md';

export const MULTI_PROJECT_CONCURRENT_EXECUTION_V1_ARTIFACT_DIR =
  '.multi-project-concurrent-execution-v1';

export const CONCURRENT_EXECUTION_QUEUE_DIR =
  '.multi-project-concurrent-execution-v1/queue';

export const MIN_CONCURRENT_PROJECTS_PROOF = 5;

export const MIN_CONCURRENT_PASS_RATE = 100;

export const MIN_CONCURRENT_WORLD2_EXECUTIONS = 5;

/** Supported concurrent test suite — 5 independent projects. */
export const CONCURRENT_EXECUTION_SUITE_PROFILES = [
  'TASK_TRACKER_WEB_V1',
  'CRM_WEB_V1',
  'MARKETPLACE_WEB_V1',
  'PROJECT_MANAGEMENT_WEB_V1',
  'APPOINTMENT_BOOKING_WEB_V1',
] as const;

export const CONCURRENT_EXECUTION_MODES = [
  'CLOUD_SIMULATED',
  'CLOUD_SIMULATED',
  'CLOUD_SIMULATED',
  'CLOUD_SIMULATED',
  'CLOUD_SIMULATED',
] as const;

export const PRIOR_PASS_TOKENS = [
  'WORLD2_REAL_INSTANTIATION_V1_PASS',
  'CLOUD_EXECUTION_PATH_V1_PASS',
  'REAL_BUILD_EXECUTION_PIPELINE_V1_1_PASS',
  'CANONICAL_OWNERSHIP_V2_PASS',
  'VALIDATION_RUNTIME_GOVERNANCE_V1_PASS',
  'AIDEVENGINE_CAPABILITY_AUDIT_V3_1_PASS',
] as const;
