export const CAPABILITY_PACK_B1_PROVENANCE = 'UNIVERSAL_CAPABILITY_PACK_FRAMEWORK_V1.b1-crud' as const;
export const CAPABILITY_PACK_B2_PROVENANCE = 'UNIVERSAL_CAPABILITY_PACK_FRAMEWORK_V1.b2-actions' as const;
export const CAPABILITY_PACK_B3_PROVENANCE = 'UNIVERSAL_CAPABILITY_PACK_FRAMEWORK_V1.b3-workflows' as const;
export const CAPABILITY_PACK_B4_PROVENANCE = 'UNIVERSAL_CAPABILITY_PACK_FRAMEWORK_V1.b4-relationships' as const;
export const CAPABILITY_PACK_B5_PROVENANCE = 'UNIVERSAL_CAPABILITY_PACK_FRAMEWORK_V1.b5-runtime' as const;
export const CAPABILITY_PACK_B6_PROVENANCE = 'UNIVERSAL_CAPABILITY_PACK_FRAMEWORK_V1.b6-rules' as const;
