/**
 * Generated Workspace Dependency Materialization — report builder (Phase 26.78).
 */

import {
  GENERATED_WORKSPACE_DEPENDENCY_MATERIALIZATION_CORE_QUESTION,
  GENERATED_WORKSPACE_DEPENDENCY_MATERIALIZATION_PHASE,
  GENERATED_WORKSPACE_DEPENDENCY_MATERIALIZATION_REPORT_TITLE,
  GENERATED_WORKSPACE_DEPENDENCY_REPAIR_PLAN_REPORT_TITLE,
  ORCHESTRATION_FLOW,
  PACKAGE_MANAGER_RESOLUTION_PRIORITY,
  SAFETY_GUARANTEES,
} from './generated-workspace-dependency-materialization-registry.js';
import type { GeneratedWorkspaceDependencyMaterializationReport } from './generated-workspace-dependency-materialization-types.js';

export function buildGeneratedWorkspaceDependencyMaterializationReportMarkdown(
  report: GeneratedWorkspaceDependencyMaterializationReport,
): string {
  const { manifest, packageManager, presence, moduleProbe, repairPlan } = report;
  return [
    `# ${GENERATED_WORKSPACE_DEPENDENCY_MATERIALIZATION_REPORT_TITLE}`,
    '',
    `**Assessment:** ${report.assessmentId}`,
    `**Generated:** ${report.generatedAt}`,
    `**Dependency state:** ${report.dependencyState}`,
    `**Dependencies ready:** ${report.dependenciesReady}`,
    '',
    '## Core question',
    '',
    GENERATED_WORKSPACE_DEPENDENCY_MATERIALIZATION_CORE_QUESTION,
    '',
    '## Phase',
    '',
    GENERATED_WORKSPACE_DEPENDENCY_MATERIALIZATION_PHASE,
    '',
    '## Workspace',
    '',
    `- workspaceRoot: **${report.workspaceRoot}**`,
    `- workspaceId: **${report.workspaceId}**`,
    `- packageJsonExists: **${manifest.packageJsonExists}**`,
    `- nodeModulesExists: **${presence.nodeModulesExists}**`,
    `- lockfileType: **${presence.lockfileType}**`,
    '',
    '## Package manager',
    '',
    `- packageManager: **${packageManager.packageManager}**`,
    `- evidenceSource: **${packageManager.evidenceSource}**`,
    `- evidenceDetail: ${packageManager.evidenceDetail}`,
    '',
    '## Dependency presence',
    '',
    `- declaredDependencies: ${presence.declaredDependencies.length}`,
    `- missingRuntimeDependencies: ${presence.missingRuntimeDependencies.join(', ') || 'none'}`,
    `- importGraphMissingModules: ${presence.importGraphMissingModules.join(', ') || 'none'}`,
    `- dependencyStateReason: ${presence.dependencyStateReason}`,
    '',
    '## Module probe',
    '',
    `- probedFiles: ${moduleProbe.probedFiles.join(', ') || 'none'}`,
    `- unresolvedModules: ${moduleProbe.unresolvedModules.join(', ') || 'none'}`,
    '',
    '## Recommended fix',
    '',
    report.recommendedFix,
    '',
  ].join('\n');
}

export function buildGeneratedWorkspaceDependencyRepairPlanMarkdown(
  report: GeneratedWorkspaceDependencyMaterializationReport,
): string {
  const plan = report.repairPlan;
  return [
    `# ${GENERATED_WORKSPACE_DEPENDENCY_REPAIR_PLAN_REPORT_TITLE}`,
    '',
    `Generated: ${report.generatedAt}`,
    '',
    '## FILES_EXIST → DEPENDENCIES_READY → APPLICATION_BOOTS',
    '',
    `| Step | Status |`,
    `|------|--------|`,
    `| FILES_EXIST | yes |`,
    `| DEPENDENCIES_READY | **${report.dependenciesReady ? 'yes' : 'no'}** (${report.dependencyState}) |`,
    `| APPLICATION_BOOTS | pending startup probe |`,
    '',
    '## Repair plan',
    '',
    `- installCommand: **${plan.installCommand}**`,
    `- installCwd: **${plan.installCwd}**`,
    `- packageManager: **${plan.packageManager}**`,
    `- shouldAutoRun: **${plan.shouldAutoRun}**`,
    `- riskLevel: **${plan.riskLevel}**`,
    `- missingModules: **${plan.missingModulesSummary}**`,
    '',
    '### Reason',
    '',
    plan.reason,
    '',
    '### Expected effect',
    '',
    plan.expectedEffect,
    '',
    '## Package manager resolution priority',
    '',
    ...PACKAGE_MANAGER_RESOLUTION_PRIORITY.map((p, i) => `${i + 1}. ${p}`),
    '',
    '## Safety guarantees',
    '',
    ...SAFETY_GUARANTEES.map((g) => `- ${g}`),
    '',
    '## Orchestration',
    '',
    ...ORCHESTRATION_FLOW.map((s, i) => `${i + 1}. ${s}`),
    '',
  ].join('\n');
}
