/**
 * Self-Evolution Execution V1 — bounds and pass token.
 */

export const SELF_EVOLUTION_EXECUTION_V1_PASS_TOKEN = 'SELF_EVOLUTION_EXECUTION_V1_PASS';

export const SELF_EVOLUTION_EXECUTION_V1_FAIL_TOKEN = 'SELF_EVOLUTION_EXECUTION_V1_FAIL';

export const SELF_EVOLUTION_EXECUTION_V1_REPORT_TITLE = 'SELF_EVOLUTION_EXECUTION_V1_REPORT.md';

export const SELF_EVOLUTION_EXECUTION_V1_ARTIFACT_DIR = '.self-evolution-execution-v1';

export const MAX_EVOLUTION_REGISTRY_SIZE = 100;

export const MIN_EVOLUTION_EXPERIMENTS = 1;

export const MIN_EVOLUTION_PROPOSALS = 1;

export const MIN_GAP_DETECTION_COUNT = 1;

export const EVOLUTION_EXPERIMENT_PROFILES = [
  'TASK_TRACKER_WEB_V1',
  'CRM_WEB_V1',
] as const;

export const PRIOR_PASS_TOKENS = [
  'MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_PASS',
  'WORLD2_REAL_INSTANTIATION_V1_PASS',
  'LARGE_SCALE_PIPELINE_INTEGRATION_V1_PASS',
  'CLOUD_EXECUTION_PATH_V1_PASS',
  'PRODUCTION_READINESS_GATE_V1_PASS',
  'GENERAL_PURPOSE_CODE_GENERATION_V1_PASS',
  'UVL_VERIFICATION_EXECUTION_V1_PASS',
  'AIDEVENGINE_CAPABILITY_AUDIT_V3_1_PASS',
] as const;

export const EVOLUTION_PIPELINE_STAGES = [
  'OBSERVE',
  'DETECT_GAP',
  'GENERATE_PROPOSAL',
  'CREATE_WORLD2_EXPERIMENT',
  'IMPLEMENT_CHANGE',
  'VALIDATE_CHANGE',
  'MEASURE_IMPACT',
  'APPROVE_OR_REJECT',
  'PROMOTE',
  'ARCHIVE',
] as const;
