/**
 * Clarifying Question Live Gate — bounded live conversation categories.
 */

import type { LiveGateCategoryDefinition } from './clarifying-question-live-gate-types.js';

export const LIVE_GATE_CATEGORY_DEFINITIONS: readonly LiveGateCategoryDefinition[] = [
  {
    id: 'AUTHENTICATION',
    label: 'Authentication',
    priority: 'CRITICAL',
    blocksPlanning: true,
    skipArchetypes: ['PORTFOLIO_WEBSITE'],
    detectionPatterns: [
      /\b(login|log in|sign in|signup|sign up|register|authentication|password|oauth|google|apple|email\/password)\b/i,
    ],
    assumptionIfGuessed: 'Email/password authentication',
    question: 'Should users sign up and log in? What authentication method is required?',
    whyItMatters: 'Authentication requirements were never specified.',
    consequenceIfAssumed: 'The system may add or omit login flows inappropriately.',
  },
  {
    id: 'USER_ROLES',
    label: 'User Roles',
    priority: 'CRITICAL',
    blocksPlanning: true,
    skipArchetypes: ['PORTFOLIO_WEBSITE', 'EXPENSE_TRACKER'],
    detectionPatterns: [
      /\b(admin|manager|member|guest|customer|driver|restaurant|role|team|organization)\b/i,
    ],
    assumptionIfGuessed: 'Default admin and user roles',
    question: 'Who will use this product and what roles are required?',
    whyItMatters: 'User roles and permission boundaries are unspecified.',
    consequenceIfAssumed: 'The system may invent admin, manager, or guest roles incorrectly.',
  },
  {
    id: 'PERMISSIONS',
    label: 'Permissions',
    priority: 'CRITICAL',
    blocksPlanning: true,
    skipArchetypes: ['PORTFOLIO_WEBSITE', 'EXPENSE_TRACKER'],
    detectionPatterns: [
      /\b(permission|access control|rbac|read.?only|write access|role.?based|single.?user|personal use)\b/i,
    ],
    assumptionIfGuessed: 'Standard role-based permissions',
    question: 'What permissions or access levels should each role have?',
    whyItMatters: 'Permission boundaries are not defined.',
    consequenceIfAssumed: 'Users may receive incorrect access to sensitive actions.',
  },
  {
    id: 'PLATFORM_TARGETS',
    label: 'Platform Targets',
    priority: 'CRITICAL',
    blocksPlanning: true,
    skipArchetypes: [],
    detectionPatterns: [/\b(web|mobile|ios|android|desktop|api|cloud|browser|native app)\b/i],
    assumptionIfGuessed: 'Web-only deployment',
    question: 'Should this be web, mobile, desktop, API, or a combination?',
    whyItMatters: 'Target platform is not specified.',
    consequenceIfAssumed: 'The system may choose the wrong deployment surface.',
  },
  {
    id: 'PAYMENTS',
    label: 'Payments',
    priority: 'IMPORTANT',
    blocksPlanning: true,
    skipArchetypes: ['PORTFOLIO_WEBSITE', 'EXPENSE_TRACKER'],
    detectionPatterns: [
      /\b(payment|subscription|paid|free|billing|stripe|payfast|checkout|pricing|cash only|no payment)\b/i,
    ],
    assumptionIfGuessed: 'Stripe subscription payments',
    question: 'Will this product be free, paid, subscription-based, or cash-only?',
    whyItMatters: 'Monetization model is not specified.',
    consequenceIfAssumed: 'The system may invent payment flows that were never requested.',
  },
  {
    id: 'BRANDING',
    label: 'Branding',
    priority: 'IMPORTANT',
    blocksPlanning: true,
    skipArchetypes: ['EXPENSE_TRACKER'],
    detectionPatterns: [/\b(brand|branding|logo|identity|company name)\b/i],
    assumptionIfGuessed: 'Generic product branding',
    question: 'Do you have existing branding or a logo that should be used?',
    whyItMatters: 'Brand identity is not specified.',
    consequenceIfAssumed: 'The product may look unrelated to your brand.',
  },
  {
    id: 'UI_STYLE',
    label: 'UI Style',
    priority: 'OPTIONAL',
    blocksPlanning: false,
    skipArchetypes: [],
    detectionPatterns: [/\b(ui style|minimal|modern|professional|playful|design system)\b/i],
    assumptionIfGuessed: 'Modern minimal UI style',
    question: 'What UI style should the product follow?',
    whyItMatters: 'Visual style preferences are unclear.',
    consequenceIfAssumed: 'The interface may not match user expectations.',
  },
  {
    id: 'COLOR_SCHEME',
    label: 'Color Scheme',
    priority: 'IMPORTANT',
    blocksPlanning: true,
    skipArchetypes: [],
    detectionPatterns: [/\b(color|colour|palette|theme|dark mode|light mode|hex #)\b/i],
    assumptionIfGuessed: 'Default blue and gray color scheme',
    question: 'What color scheme or theme should the product use?',
    whyItMatters: 'Color preferences were never specified.',
    consequenceIfAssumed: 'The system may generate an unwanted visual style.',
  },
  {
    id: 'NOTIFICATIONS',
    label: 'Notifications',
    priority: 'IMPORTANT',
    blocksPlanning: false,
    skipArchetypes: ['PORTFOLIO_WEBSITE'],
    detectionPatterns: [/\b(notification|push|email alert|sms|reminder|notify)\b/i],
    assumptionIfGuessed: 'Email and push notifications enabled',
    question: 'What notifications should the system send and through which channels?',
    whyItMatters: 'Notification expectations are unspecified.',
    consequenceIfAssumed: 'Users may receive unwanted or missing alerts.',
  },
  {
    id: 'DATA_STORAGE',
    label: 'Data Storage',
    priority: 'IMPORTANT',
    blocksPlanning: false,
    skipArchetypes: ['PORTFOLIO_WEBSITE'],
    detectionPatterns: [/\b(database|storage|upload|file|persist|cloud storage|user data)\b/i],
    assumptionIfGuessed: 'Cloud database with file uploads',
    question: 'What data must be stored, uploaded, or persisted?',
    whyItMatters: 'Data and storage expectations are unclear.',
    consequenceIfAssumed: 'Persistence or uploads may be built without intent.',
  },
  {
    id: 'INTEGRATIONS',
    label: 'Integrations',
    priority: 'OPTIONAL',
    blocksPlanning: false,
    skipArchetypes: ['PORTFOLIO_WEBSITE', 'EXPENSE_TRACKER'],
    detectionPatterns: [/\b(integration|integrate with|connect to|sync with|api partner)\b/i],
    assumptionIfGuessed: 'Third-party API integrations',
    question: 'Which external systems must this product integrate with?',
    whyItMatters: 'Integration scope is not defined.',
    consequenceIfAssumed: 'Missing or incorrect integrations may be planned.',
  },
  {
    id: 'THIRD_PARTY_SERVICES',
    label: 'Third Party Services',
    priority: 'OPTIONAL',
    blocksPlanning: false,
    skipArchetypes: ['PORTFOLIO_WEBSITE'],
    detectionPatterns: [/\b(third.?party|external service|saas provider|maps api|sendgrid|firebase)\b/i],
    assumptionIfGuessed: 'Common SaaS providers by default',
    question: 'Are specific third-party services required?',
    whyItMatters: 'External service dependencies are unspecified.',
    consequenceIfAssumed: 'Wrong vendors may be selected during planning.',
  },
  {
    id: 'OFFLINE_REQUIREMENTS',
    label: 'Offline Requirements',
    priority: 'IMPORTANT',
    blocksPlanning: false,
    skipArchetypes: ['PORTFOLIO_WEBSITE'],
    detectionPatterns: [/\b(offline|sync when online|local.?first|without internet)\b/i],
    assumptionIfGuessed: 'Online-only application',
    question: 'Must the product work offline or sync when connectivity returns?',
    whyItMatters: 'Offline behavior is not defined.',
    consequenceIfAssumed: 'Offline support may be omitted or overbuilt.',
  },
  {
    id: 'SECURITY_REQUIREMENTS',
    label: 'Security Requirements',
    priority: 'CRITICAL',
    blocksPlanning: true,
    skipArchetypes: ['PORTFOLIO_WEBSITE', 'EXPENSE_TRACKER'],
    detectionPatterns: [/\b(security|encrypt|encryption|2fa|mfa|secure|compliance|soc2|hipaa)\b/i],
    assumptionIfGuessed: 'Standard application security defaults',
    question: 'What security requirements or compliance constraints apply?',
    whyItMatters: 'Security expectations are not specified.',
    consequenceIfAssumed: 'Sensitive data may be handled incorrectly.',
  },
  {
    id: 'PRIVACY_REQUIREMENTS',
    label: 'Privacy Requirements',
    priority: 'IMPORTANT',
    blocksPlanning: false,
    skipArchetypes: ['PORTFOLIO_WEBSITE'],
    detectionPatterns: [/\b(privacy|gdpr|data retention|consent|pii|personal data)\b/i],
    assumptionIfGuessed: 'Basic privacy policy defaults',
    question: 'What privacy or data retention rules must be enforced?',
    whyItMatters: 'Privacy obligations are unclear.',
    consequenceIfAssumed: 'User data handling may violate expectations.',
  },
  {
    id: 'REPORTING_ANALYTICS',
    label: 'Reporting / Analytics',
    priority: 'OPTIONAL',
    blocksPlanning: false,
    skipArchetypes: ['PORTFOLIO_WEBSITE'],
    detectionPatterns: [/\b(analytics|reporting|dashboard metrics|kpi|usage tracking)\b/i],
    assumptionIfGuessed: 'Built-in analytics dashboard',
    question: 'What reporting or analytics capabilities are required?',
    whyItMatters: 'Analytics scope is not defined.',
    consequenceIfAssumed: 'Reporting features may be guessed incorrectly.',
  },
  {
    id: 'ADMIN_REQUIREMENTS',
    label: 'Admin Requirements',
    priority: 'IMPORTANT',
    blocksPlanning: true,
    skipArchetypes: ['PORTFOLIO_WEBSITE', 'EXPENSE_TRACKER'],
    detectionPatterns: [/\b(admin panel|admin dashboard|back office|operations console|moderation)\b/i],
    assumptionIfGuessed: 'Full admin control panel',
    question: 'What admin controls or back-office capabilities are required?',
    whyItMatters: 'Administrative needs are unspecified.',
    consequenceIfAssumed: 'Admin tooling may be missing or excessive.',
  },
  {
    id: 'DEPLOYMENT_TARGETS',
    label: 'Deployment Targets',
    priority: 'IMPORTANT',
    blocksPlanning: true,
    skipArchetypes: [],
    detectionPatterns: [/\b(deploy|deployment|public launch|beta|internal tool|enterprise|production host)\b/i],
    assumptionIfGuessed: 'Public cloud production deployment',
    question: 'Is this for public launch, beta, internal use, or enterprise deployment?',
    whyItMatters: 'Launch scope affects requirements and quality bar.',
    consequenceIfAssumed: 'Build scope may not match intended launch stage.',
  },
  {
    id: 'FAILURE_HANDLING',
    label: 'Failure Handling',
    priority: 'CRITICAL',
    blocksPlanning: true,
    skipArchetypes: ['PORTFOLIO_WEBSITE'],
    detectionPatterns: [
      /\b(when .+ fails|error handling|on failure|retry|fallback|escalation|sync fail)\b/i,
    ],
    assumptionIfGuessed: 'Silent retry with generic error messages',
    question: 'What should happen when tasks fail, errors occur, or operations break?',
    whyItMatters: 'Failure handling rules are not explained.',
    consequenceIfAssumed: 'Failure behavior may be guessed incorrectly.',
  },
  {
    id: 'SUCCESS_CRITERIA',
    label: 'Success Criteria',
    priority: 'CRITICAL',
    blocksPlanning: true,
    skipArchetypes: [],
    detectionPatterns: [
      /\b(success criteria|definition of done|must achieve|goal is|users should be able to)\b/i,
      /\bfor (founders|teams|customers|users|students|enterprises)\b/i,
    ],
    assumptionIfGuessed: 'Generic product success metrics',
    question: 'How will you know this product succeeded for its users?',
    whyItMatters: 'Success criteria are not defined.',
    consequenceIfAssumed: 'The build may optimize for the wrong outcomes.',
  },
] as const;

export const MAX_LIVE_GATE_CATEGORIES = LIVE_GATE_CATEGORY_DEFINITIONS.length;

export const ARCHETYPE_QUESTION_OVERRIDES: Readonly<
  Partial<Record<string, Partial<Record<string, string>>>>
> = {
  FOOD_DELIVERY: {
    USER_ROLES: 'Which roles are required: customers, drivers, restaurants, admins, or all of them?',
    PAYMENTS: 'How should payments work: Stripe, PayFast, cash only, or another model?',
  },
  ACCOUNTING_PLATFORM: {
    PERMISSIONS: 'What permission levels are required for accountants, auditors, and admins?',
    SECURITY_REQUIREMENTS: 'What tax, audit, or compliance security requirements apply?',
    FAILURE_HANDLING: 'What should happen when calculations fail or data conflicts occur?',
  },
  PORTFOLIO_WEBSITE: {
    PLATFORM_TARGETS: 'Should this portfolio be web-only or also optimized for mobile?',
    COLOR_SCHEME: 'What color scheme or visual theme should the portfolio use?',
  },
  TASK_MANAGEMENT: {
    USER_ROLES: 'Will this be individual use, team use, or both? Are admin roles required?',
    NOTIFICATIONS: 'What task reminders or notifications should be sent?',
  },
};
