/**
 * Unified Intake Intelligence — registry constants (V1).
 */

export const UNIFIED_INTAKE_INTELLIGENCE_V1_PASS = 'UNIFIED_INTAKE_INTELLIGENCE_V1_PASS';

export const UNIFIED_INTAKE_INTELLIGENCE_OWNER_MODULE = 'unified-intake-intelligence';

export const UNIFIED_INTAKE_INTELLIGENCE_PHASE = '26.28';

export const UNIFIED_INTAKE_INTELLIGENCE_REPORT_TITLE = 'Unified Intake Intelligence Report';

export const MAX_UNIFIED_INTAKE_HISTORY = 32;

export const INTAKE_SOURCE_IDS = [
  'TYPED_PROMPT',
  'VOICE_NOTES_INTELLIGENCE',
  'VISUAL_REFERENCE_INTELLIGENCE',
  'REQUIREMENT_COMPLETENESS_INTELLIGENCE',
  'UPLOAD_SYSTEM',
  'PROJECT_VAULT_CONTEXT',
  'FOUNDER_CONTEXT',
  'CUSTOM_SOURCE',
] as const;

export const APPLICATION_TYPES = [
  'SAAS_PLATFORM',
  'MARKETPLACE',
  'SOCIAL_NETWORK',
  'INTERNAL_TOOL',
  'MOBILE_APP',
  'AI_PRODUCT',
  'E_COMMERCE_PLATFORM',
  'WEB_APP',
  'UNKNOWN',
] as const;

export const INTAKE_READINESS_VALUES = [
  'INSUFFICIENT_INPUT',
  'PARTIAL_UNDERSTANDING',
  'HIGH_CONFIDENCE_UNDERSTANDING',
  'READY_FOR_PLANNING',
] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_INTELLIGENCE',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MODIFICATION',
  'NO_PLANNING_EXECUTION',
  'NO_AUTONOMOUS_EXECUTION',
  'EVIDENCE_BASED_OUTPUTS_ONLY',
  'BOUNDED_ANALYSIS_HISTORY',
  'PLUGGABLE_INTAKE_SOURCES',
] as const;
