/**
 * Requirement Completeness Intelligence — registry constants (V1).
 */

export const REQUIREMENT_COMPLETENESS_INTELLIGENCE_PASS_TOKEN =
  'REQUIREMENT_COMPLETENESS_INTELLIGENCE_V1_PASS';

export const REQUIREMENT_COMPLETENESS_INTELLIGENCE_OWNER_MODULE = 'requirement-completeness-intelligence';

export const REQUIREMENT_COMPLETENESS_INTELLIGENCE_PHASE = '26.25';

export const REQUIREMENT_COMPLETENESS_INTELLIGENCE_REPORT_TITLE =
  'Requirement Completeness Intelligence Report';

export const MAX_REQUIREMENT_COMPLETENESS_HISTORY = 32;

export const ANALYSIS_DOMAINS = [
  'UI_REQUIREMENTS',
  'BUSINESS_LOGIC',
  'AUTHENTICATION',
  'DATA_MODEL',
  'NOTIFICATIONS',
  'INTEGRATIONS',
  'PLATFORM_TARGETS',
] as const;

export const COMPLETENESS_CATEGORIES = [
  'INSUFFICIENT',
  'PARTIAL',
  'READY_WITH_GAPS',
  'READY',
] as const;

export const PROJECT_READINESS_VALUES = [
  'NOT_READY',
  'NEEDS_CLARIFICATION',
  'READY_WITH_GAPS',
  'READY_FOR_PLANNING',
] as const;

export const QUESTION_PRIORITIES = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_INTELLIGENCE',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MODIFICATION',
  'NO_AUTONOMOUS_EXECUTION',
  'NO_PLANNING_ACTIONS',
  'EVIDENCE_BASED_OUTPUTS_ONLY',
  'BOUNDED_ANALYSIS_HISTORY',
] as const;
