/**
 * Command Center Chat Execution Audit V1 — canonical event names.
 */

export const COMMAND_CENTER_CHAT_AUDIT_PREFIX = 'COMMAND_CENTER_CHAT_AUDIT_' as const;

export const COMMAND_CENTER_CHAT_AUDIT_EVENTS = {
  FORM_SUBMIT_ENTER: 'COMMAND_CENTER_CHAT_AUDIT_FORM_SUBMIT_ENTER',
  FORM_SUBMIT_NO_INPUT: 'COMMAND_CENTER_CHAT_AUDIT_FORM_SUBMIT_NO_INPUT',
  FORM_SUBMIT_EMPTY_MESSAGE: 'COMMAND_CENTER_CHAT_AUDIT_FORM_SUBMIT_EMPTY_MESSAGE',
  FORM_SUBMIT_DISPATCHED: 'COMMAND_CENTER_CHAT_AUDIT_FORM_SUBMIT_DISPATCHED',
  ASK_BRAIN_ENTER: 'COMMAND_CENTER_CHAT_AUDIT_ASK_BRAIN_ENTER',
  ASK_BRAIN_BLOCKED_RUNTIME_TRUTH: 'COMMAND_CENTER_CHAT_AUDIT_ASK_BRAIN_BLOCKED_RUNTIME_TRUTH',
  ASK_BRAIN_BLOCKED_RUNTIME_HEALTH: 'COMMAND_CENTER_CHAT_AUDIT_ASK_BRAIN_BLOCKED_RUNTIME_HEALTH',
  ASK_BRAIN_BLOCKED_RUNTIME_POLL_FAILED: 'COMMAND_CENTER_CHAT_AUDIT_ASK_BRAIN_BLOCKED_RUNTIME_POLL_FAILED',
  SHOW_THINKING: 'COMMAND_CENTER_CHAT_AUDIT_SHOW_THINKING',
  SHOW_THINKING_SKIPPED_NO_HISTORY: 'COMMAND_CENTER_CHAT_AUDIT_SHOW_THINKING_SKIPPED_NO_HISTORY',
  CLASSIFY_START: 'COMMAND_CENTER_CHAT_AUDIT_CLASSIFY_START',
  CLASSIFY_COMPLETE: 'COMMAND_CENTER_CHAT_AUDIT_CLASSIFY_COMPLETE',
  FETCH_PAYLOAD_CREATED: 'COMMAND_CENTER_CHAT_AUDIT_FETCH_PAYLOAD_CREATED',
  FETCH_START: 'COMMAND_CENTER_CHAT_AUDIT_FETCH_START',
  FETCH_RESPONSE: 'COMMAND_CENTER_CHAT_AUDIT_FETCH_RESPONSE',
  FETCH_ERROR: 'COMMAND_CENTER_CHAT_AUDIT_FETCH_ERROR',
  TRACE_RENDER_START: 'COMMAND_CENTER_CHAT_AUDIT_TRACE_RENDER_START',
  TRACE_RENDER_EMPTY: 'COMMAND_CENTER_CHAT_AUDIT_TRACE_RENDER_EMPTY',
  TRACE_RENDER_COMPLETE: 'COMMAND_CENTER_CHAT_AUDIT_TRACE_RENDER_COMPLETE',
  RESPONSE_RENDERED: 'COMMAND_CENTER_CHAT_AUDIT_RESPONSE_RENDERED',
  NO_OP_DETECTED: 'COMMAND_CENTER_CHAT_AUDIT_NO_OP_DETECTED',
  SEND_BUTTON_DISABLED: 'COMMAND_CENTER_CHAT_AUDIT_SEND_BUTTON_DISABLED',

  AFTER_USER_MESSAGE_RENDERED: 'COMMAND_CENTER_CHAT_AUDIT_AFTER_USER_MESSAGE_RENDERED',
  DEGRADED_RUNTIME_TRUTH_CONTINUE: 'COMMAND_CENTER_CHAT_AUDIT_DEGRADED_RUNTIME_TRUTH_CONTINUE',
  RUNTIME_TRUTH_REHYDRATE_START: 'COMMAND_CENTER_CHAT_AUDIT_RUNTIME_TRUTH_REHYDRATE_START',
  RUNTIME_TRUTH_REHYDRATE_COMPLETE: 'COMMAND_CENTER_CHAT_AUDIT_RUNTIME_TRUTH_REHYDRATE_COMPLETE',
  SESSION_REPAIR_START: 'COMMAND_CENTER_CHAT_AUDIT_SESSION_REPAIR_START',
  SESSION_REPAIR_COMPLETE: 'COMMAND_CENTER_CHAT_AUDIT_SESSION_REPAIR_COMPLETE',
  SESSION_REPAIR_SKIPPED: 'COMMAND_CENTER_CHAT_AUDIT_SESSION_REPAIR_SKIPPED',
  PROJECT_CONTEXT_WARNING: 'COMMAND_CENTER_CHAT_AUDIT_PROJECT_CONTEXT_WARNING',
  FETCH_WATCHDOG_ARMED: 'COMMAND_CENTER_CHAT_AUDIT_FETCH_WATCHDOG_ARMED',
  FETCH_WATCHDOG_TRIGGERED: 'COMMAND_CENTER_CHAT_AUDIT_FETCH_WATCHDOG_TRIGGERED',
  CHAT_EXECUTION_STOPPED_AFTER_RENDER: 'COMMAND_CENTER_CHAT_AUDIT_CHAT_EXECUTION_STOPPED_AFTER_RENDER',
  VISIBLE_BLOCKING_ERROR_SHOWN: 'COMMAND_CENTER_CHAT_AUDIT_VISIBLE_BLOCKING_ERROR_SHOWN',

  HANDLER_ENTER: 'COMMAND_CENTER_CHAT_AUDIT_HANDLER_ENTER',
  HANDLER_EMPTY_MESSAGE: 'COMMAND_CENTER_CHAT_AUDIT_HANDLER_EMPTY_MESSAGE',
  BUILD_INTENT_DECISION: 'COMMAND_CENTER_CHAT_AUDIT_BUILD_INTENT_DECISION',
  BRIDGE_INVOKE: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_INVOKE',
  BRIDGE_SKIP: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_SKIP',
  BRIDGE_RESULT: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_RESULT',
  HANDLER_RESPONSE_SENT: 'COMMAND_CENTER_CHAT_AUDIT_HANDLER_RESPONSE_SENT',
  HANDLER_ERROR: 'COMMAND_CENTER_CHAT_AUDIT_HANDLER_ERROR',

  BRIDGE_ENTER: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_ENTER',
  BRIDGE_INTENT_DETECTED: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_INTENT_DETECTED',
  BRIDGE_ROUTE_SELECTED: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_ROUTE_SELECTED',
  BRIDGE_FIRST_EVENT: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_FIRST_EVENT',
  BRIDGE_ASE_INVOKE: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_ASE_INVOKE',
  BRIDGE_ASE_SKIP: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_ASE_SKIP',
  BRIDGE_FAILURE: 'COMMAND_CENTER_CHAT_AUDIT_BRIDGE_FAILURE',
} as const;

export type CommandCenterChatAuditEventName =
  (typeof COMMAND_CENTER_CHAT_AUDIT_EVENTS)[keyof typeof COMMAND_CENTER_CHAT_AUDIT_EVENTS];
