/**
 * Build Intent Classification Recovery V1 — contract constants.
 */

export const BUILD_INTENT_CLASSIFICATION_RECOVERY_V1_PASS_TOKEN =
  'BUILD_INTENT_CLASSIFICATION_RECOVERY_V1_PASS' as const;

export const BUILD_INTENT_CLASSIFICATION_RECOVERY_CONTRACT_VERSION =
  'BUILD_INTENT_CLASSIFICATION_RECOVERY_V1' as const;

export const BUILD_INTENT_RECOVERY_TRACE = 'BUILD_INTENT_CLASSIFICATION_RECOVERY_V1' as const;
