/**
 * Founder Simulation Engine — registry constants (V1).
 */

export const FOUNDER_SIMULATION_ENGINE_V1_PASS = 'FOUNDER_SIMULATION_ENGINE_V1_PASS';

export const FOUNDER_SIMULATION_ENGINE_OWNER_MODULE = 'founder-simulation-engine';

export const FOUNDER_SIMULATION_ENGINE_PHASE = '26.33';

export const FOUNDER_SIMULATION_ENGINE_REPORT_TITLE = 'Founder Simulation Engine Report';

export const MAX_FOUNDER_SIMULATION_HISTORY = 16;

export const MAX_SIMULATION_RUNTIME_MS = 120_000;

export const MAX_FOUNDER_SIMULATION_RUNTIME_MS = MAX_SIMULATION_RUNTIME_MS;

export const SIMULATION_STAGE_ORDER = [
  'UPLOAD_SYSTEM',
  'VISUAL_REFERENCE_INTELLIGENCE',
  'VOICE_NOTES_INTELLIGENCE',
  'REQUIREMENT_COMPLETENESS_INTELLIGENCE',
  'UNIFIED_INTAKE_INTELLIGENCE',
  'PLANNING_GATE_AUTHORITY',
  'PLANNING_BRIEF_GENERATOR',
  'ARCHITECTURE_BRIEF_GENERATOR',
  'BUILD_PLAN_GENERATOR',
  'FOUNDER_TEST_AUTOMATION',
  'FINAL_FOUNDER_READINESS_VERDICT',
] as const;

export const FOUNDER_SIMULATION_SCENARIO_TYPES = [
  'SIMPLE_APP',
  'COMPLEX_MARKETPLACE',
  'MOBILE_FIRST',
  'SAAS_DASHBOARD',
  'AI_POWERED',
  'E_COMMERCE',
  'INCOMPLETE_VAGUE',
  'CONFLICTING_EVIDENCE',
  'SCREENSHOT_SUPPORTED',
  'VOICE_NOTE_SUPPORTED',
] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_SIMULATION',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MODIFICATION',
  'NO_AUTONOMOUS_BUILDING',
  'NO_DEPLOYMENT',
  'HONEST_ASSESSMENT_ONLY',
  'EVIDENCE_BASED_OUTPUTS',
  'BOUNDED_SIMULATION_HISTORY',
  'RUNTIME_BUDGET_SAFEGUARDS',
  'PROGRESS_LOGGING',
] as const;
