/**
 * Canonical Ownership V2 Registration — bounds and pass token.
 */

export const CANONICAL_OWNERSHIP_V2_PASS_TOKEN = 'CANONICAL_OWNERSHIP_V2_PASS';

export const CANONICAL_OWNERSHIP_V2_FAIL_TOKEN = 'CANONICAL_OWNERSHIP_V2_FAIL';

export const CANONICAL_OWNERSHIP_V2_REGISTRATION_REPORT_TITLE =
  'CANONICAL_OWNERSHIP_V2_REGISTRATION_REPORT.md';

export const CANONICAL_OWNERSHIP_V2_ARTIFACT_DIR = '.canonical-ownership-v2';

export const REGISTRATION_SCOPE_CAPABILITY_IDS = [
  'CAPABILITY_AUDIT_V2',
  'CAPABILITY_AUDIT_V3',
  'CAPABILITY_AUDIT_V3_1',
  'CQI_MATURITY_V1',
  'REAL_BUILD_EXECUTION_PIPELINE_V1',
  'REAL_BUILD_EXECUTION_PIPELINE_V1_1',
  'UVL_VERIFICATION_EXECUTION_V1',
  'UVL_VERIFICATION_HUB_V1',
  'AFLA_TRUST_CALIBRATION_V1',
  'FOUNDER_REVIEW_OPERATOR_DASHBOARD_V1',
  'PRODUCT_ARCHITECT_INTELLIGENCE_V1',
  'PRODUCTION_READINESS_GATE_V1',
  'CLOUD_EXECUTION_PATH_V1',
  'GENERAL_PURPOSE_CODE_GENERATION_V1',
  'LARGE_SCALE_PIPELINE_INTEGRATION_V1',
  'LARGE_SCALE_MULTI_APP_VALIDATION_V1',
  'WORLD2_REAL_INSTANTIATION_V1',
  'MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1',
  'VALIDATION_RUNTIME_AUDIT_V1',
  'VALIDATION_RUNTIME_GOVERNANCE_V1',
    'SELF_EVOLUTION_EXECUTION_V1',
  'MULTI_PROJECT_CONCURRENT_EXECUTION_V1',
  'UNIFIED_FAILURE_ESCALATION_AUTHORITY_V1',
  'OPERATIONAL_EVIDENCE_FRESHNESS_AUTHORITY_V1',
  'CUSTOMER_OPERATIONS_PLATFORM_V1',
  'PRODUCTION_OBSERVABILITY_PLATFORM_V1',
  'CONTINUOUS_DEPLOYMENT_PIPELINE_V1',
] as const;

export const PRIOR_PASS_TOKENS = [
  'SELF_EVOLUTION_EXECUTION_V1_PASS',
  'MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_PASS',
  'WORLD2_REAL_INSTANTIATION_V1_PASS',
  'LARGE_SCALE_PIPELINE_INTEGRATION_V1_PASS',
  'VALIDATION_RUNTIME_GOVERNANCE_V1_PASS',
  'AIDEVENGINE_CAPABILITY_AUDIT_V3_1_PASS',
] as const;
