/**
 * Canonical Ownership V2 Registration — post-V1 capability registry.
 */

import type { CanonicalOwnershipEntry } from './canonical-ownership-v2-types.js';

function entry(
  capabilityId: string,
  capabilityName: string,
  canonicalOwner: CanonicalOwnershipEntry['canonicalOwner'],
  category: string,
  modulePath: string,
  validationCommand: string,
  passToken: string,
  artifactPath: string,
  consumes: readonly string[],
  provides: readonly string[],
  duplicatesResolved: readonly string[] = [],
  riskLevel: CanonicalOwnershipEntry['riskLevel'] = 'LOW',
  maturity: CanonicalOwnershipEntry['maturity'] = 'MATURE',
): CanonicalOwnershipEntry {
  return {
    readOnly: true,
    capabilityId,
    capabilityName,
    canonicalOwner,
    category,
    status: 'REGISTERED',
    maturity,
    modulePath,
    validationCommand,
    passToken,
    artifactPath,
    consumes,
    provides,
    duplicatesResolved,
    riskLevel,
  };
}

export const CANONICAL_OWNERSHIP_V2_ENTRIES: readonly CanonicalOwnershipEntry[] = [
  entry(
    'CAPABILITY_AUDIT_V2',
    'Capability Audit V2',
    'Capability Audit',
    'SELF_EVOLUTION',
    'src/capability-audit-v2/',
    'validate:capability-audit-v2',
    'AIDEVENGINE_CAPABILITY_AUDIT_V2_PASS',
    '.capability-audit-v2/assessment.json',
    [],
    ['capability inventory', 'duplicate risk baseline', 'roadmap V2'],
  ),
  entry(
    'CAPABILITY_AUDIT_V3',
    'Capability Audit V3',
    'Capability Audit',
    'SELF_EVOLUTION',
    'src/capability-audit-v3/',
    'validate:capability-audit-v3',
    'AIDEVENGINE_CAPABILITY_AUDIT_V3_PASS',
    '.capability-audit-v3/assessment.json',
    ['Capability Audit V2'],
    ['operational maturity', 'UVL evidence refresh', 'roadmap V3'],
  ),
  entry(
    'CAPABILITY_AUDIT_V3_1',
    'Capability Audit V3.1',
    'Capability Audit',
    'SELF_EVOLUTION',
    'src/capability-audit-v3/',
    'validate:capability-audit-v3-1',
    'AIDEVENGINE_CAPABILITY_AUDIT_V3_1_PASS',
    '.capability-audit-v3-1/assessment.json',
    ['Capability Audit V3', 'UVL Verification Execution V1'],
    ['UVL evidence refresh', 'coverage breakdown', 'roadmap recalculation'],
  ),
  entry(
    'CQI_MATURITY_V1',
    'CQI Maturity V1',
    'CQI',
    'REQUIREMENT_INTELLIGENCE',
    'src/clarifying-question-intelligence/',
    'validate:clarifying-question-intelligence-maturity-v1',
    'CLARIFYING_QUESTION_INTELLIGENCE_MATURITY_V1_PASS',
    '.clarifying-question-intelligence-maturity-v1/assessment.json',
    ['Clarifying Question Intelligence'],
    ['requirement completeness', 'gap detection', 'adaptive questions'],
    ['CQI Maturity V1 ↔ Requirement Completeness Intelligence'],
  ),
  entry(
    'REAL_BUILD_EXECUTION_PIPELINE_V1',
    'Real Build Execution Pipeline V1',
    'Real Build Execution Pipeline',
    'ENGINEERING_REVIEW',
    'src/real-build-execution-pipeline-v1/',
    'validate:real-build-execution-pipeline-v1',
    'REAL_BUILD_EXECUTION_PIPELINE_V1_PASS',
    '.real-build-execution-pipeline-v1/build-proof.json',
    ['Code Generation Engine V1'],
    ['build proof', 'preview proof', 'execution proof'],
    ['Real Build Execution Pipeline ↔ UVL Verification Execution — build vs verification layer'],
    'MEDIUM',
  ),
  entry(
    'REAL_BUILD_EXECUTION_PIPELINE_V1_1',
    'Real Build Execution Pipeline V1.1',
    'Real Build Execution Pipeline',
    'ENGINEERING_REVIEW',
    'src/real-build-execution-pipeline-v1-1/',
    'validate:real-build-execution-pipeline-v1-1',
    'REAL_BUILD_EXECUTION_PIPELINE_V1_1_PASS',
    '.real-build-execution-pipeline-v1-1/build-proof.json',
    ['Real Build Execution Pipeline V1'],
    ['15/15 build proof', 'generalization score', 'AFLA integration'],
    ['Real Build Execution Pipeline V1.1 ↔ UVL Verification Execution V1 — evidence split by layer'],
    'MEDIUM',
  ),
  entry(
    'UVL_VERIFICATION_EXECUTION_V1',
    'UVL Verification Execution V1',
    'UVL',
    'VERIFICATION_SYSTEMS',
    'src/uvl-verification-execution-v1/',
    'validate:uvl-verification-execution-v1',
    'UVL_VERIFICATION_EXECUTION_V1_PASS',
    '.uvl-verification-execution-v1/verification-proof.json',
    ['Real Build Execution Pipeline V1.1', 'Unified Verification Lab (UVL)'],
    ['verification proof', 'verification coverage', 'verification confidence'],
    ['Real Build Execution Pipeline ↔ UVL — RBEP build/preview vs UVL verification'],
  ),
  entry(
    'UVL_VERIFICATION_HUB_V1',
    'UVL Verification Hub V1',
    'UVL',
    'VERIFICATION_SYSTEMS',
    'src/unified-verification-lab/',
    'validate:uvl-maturity-verification-hub-v1',
    'UVL_MATURITY_VERIFICATION_HUB_V1_PASS',
    '.unified-verification-lab-v1/assessment.json',
    ['Unified Verification Lab (UVL)'],
    ['verification hub maturity', 'coverage assessment'],
    ['UVL Verification Hub ↔ Verification Orchestrator'],
    'MEDIUM',
    'PARTIAL',
  ),
  entry(
    'AFLA_TRUST_CALIBRATION_V1',
    'AFLA Trust Calibration V1',
    'AFLA',
    'LAUNCH_READINESS',
    'src/afla-trust-calibration-v1/',
    'validate:afla-trust-calibration-v1',
    'AFLA_TRUST_CALIBRATION_V1_PASS',
    '.afla-trust-calibration-v1/assessment.json',
    ['Autonomous Founder Launch Authority'],
    ['trust calibration', 'verdict stability', 'founder alignment'],
  ),
  entry(
    'FOUNDER_REVIEW_OPERATOR_DASHBOARD_V1',
    'Founder Review Operator Dashboard V1',
    'AFLA',
    'OPERATOR_SYSTEMS',
    'src/founder-review-operator-dashboard/',
    'validate:founder-review-operator-dashboard-v1',
    'FOUNDER_REVIEW_OPERATOR_DASHBOARD_V1_PASS',
    '.autonomous-founder-launch-authority/',
    ['Command Center Brain', 'Autonomous Founder Launch Authority'],
    ['founder review panel', 'operator visibility', 'AFLA cache integration'],
  ),
  entry(
    'PRODUCT_ARCHITECT_INTELLIGENCE_V1',
    'Product Architect Intelligence V1',
    'Product Architect Intelligence',
    'PRODUCT_ARCHITECT_INTELLIGENCE',
    'src/product-architect-intelligence-v1/',
    'validate:product-architect-intelligence-v1',
    'PRODUCT_ARCHITECT_INTELLIGENCE_V1_PASS',
    '.product-architect-intelligence-v1/assessment.json',
    ['CQI Maturity V1', 'UVL Verification Execution V1'],
    ['product completeness', 'architecture review', 'gap reports'],
  ),
  entry(
    'PRODUCTION_READINESS_GATE_V1',
    'Production Readiness Gate V1',
    'Production Readiness Gate',
    'PRODUCTION_READINESS',
    'src/production-readiness-gate-v1/',
    'validate:production-readiness-gate-v1',
    'PRODUCTION_READINESS_GATE_V1_PASS',
    '.production-readiness-gate-v1/assessment.json',
    ['Real Build Execution Pipeline V1.1'],
    ['production readiness score', 'production decision', 'deployment readiness'],
    ['Production Readiness Gate ↔ AFLA — production vs launch boundary'],
    'MEDIUM',
  ),
  entry(
    'CLOUD_EXECUTION_PATH_V1',
    'Cloud Execution Path V1',
    'Cloud Execution Path',
    'MULTI_PROJECT_EXECUTION',
    'src/cloud-execution-path-v1/',
    'validate:cloud-execution-path-v1',
    'CLOUD_EXECUTION_PATH_V1_PASS',
    '.cloud-execution-path-v1/assessment.json',
    ['Real Build Execution Pipeline V1.1'],
    ['cloud job contract', 'queue', 'workers', 'cloud-ready packages'],
    ['Cloud Execution Path ↔ World2 — job contract vs isolated environment'],
    'MEDIUM',
  ),
  entry(
    'GENERAL_PURPOSE_CODE_GENERATION_V1',
    'General-Purpose Code Generation V1',
    'General-Purpose Code Generation',
    'CODE_GENERATION',
    'src/general-purpose-code-generation-v1/',
    'validate:general-purpose-code-generation-v1',
    'GENERAL_PURPOSE_CODE_GENERATION_V1_PASS',
    '.general-purpose-code-generation-v1/assessment.json',
    ['Code Generation Engine V1'],
    ['domain diversity', 'general-purpose codegen proof'],
  ),
  entry(
    'LARGE_SCALE_PIPELINE_INTEGRATION_V1',
    'Large-Scale Pipeline Integration V1',
    'Large-Scale Pipeline Integration',
    'VERIFICATION_SYSTEMS',
    'src/large-scale-pipeline-integration-v1/',
    'validate:large-scale-pipeline-integration-v1',
    'LARGE_SCALE_PIPELINE_INTEGRATION_V1_PASS',
    '.large-scale-pipeline-integration-v1/assessment.json',
    [
      'Real Build Execution Pipeline V1.1',
      'UVL Verification Execution V1',
      'Production Readiness Gate V1',
      'Mobile Runtime Validation at Scale V1',
    ],
    ['pipeline score', 'category mapping', 'gap classification', 'audit impact'],
  ),
  entry(
    'LARGE_SCALE_MULTI_APP_VALIDATION_V1',
    'Large-Scale Multi-App Validation V1',
    'Large-Scale Pipeline Integration',
    'VERIFICATION_SYSTEMS',
    'src/large-scale-multi-app-validation-v1/',
    'validate:large-scale-multi-app-validation-v1',
    'LARGE_SCALE_MULTI_APP_VALIDATION_V1_PASS',
    '.large-scale-multi-app-validation/assessment.json',
    ['Feature Reality Validation'],
    ['58-category breadth validation', 'generalization score'],
    [],
    'MEDIUM',
    'PARTIAL',
  ),
  entry(
    'WORLD2_REAL_INSTANTIATION_V1',
    'World2 Real Instantiation V1',
    'World2',
    'WORLD2',
    'src/world2-real-instantiation-v1/',
    'validate:world2-real-instantiation-v1',
    'WORLD2_REAL_INSTANTIATION_V1_PASS',
    '.world2-real-instantiation-v1/assessment.json',
    ['Cloud Execution Path V1', 'Real Build Execution Pipeline V1.1'],
    ['isolated worlds', 'promotion', 'destruction proof', 'World1 protection'],
    ['Cloud Execution Path ↔ World2 — execution contract vs disposable environment'],
    'MEDIUM',
  ),
  entry(
    'MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1',
    'Mobile Runtime Validation at Scale V1',
    'Mobile Runtime Validation',
    'VERIFICATION_SYSTEMS',
    'src/mobile-runtime-validation-at-scale-v1/',
    'validate:mobile-runtime-validation-at-scale-v1',
    'MOBILE_RUNTIME_VALIDATION_AT_SCALE_V1_PASS',
    '.mobile-runtime-validation-at-scale-v1/assessment.json',
    ['Real Build Execution Pipeline V1.1', 'World2 Real Instantiation V1'],
    ['mobile runtime proof', 'touch interaction', 'mobile profile coverage'],
  ),
  entry(
    'VALIDATION_RUNTIME_AUDIT_V1',
    'Validation Runtime Audit V1',
    'Validation Runtime Governance',
    'SELF_EVOLUTION',
    'src/validation-runtime-audit-v1/',
    'validate:validation-runtime-audit-v1',
    'VALIDATION_RUNTIME_AUDIT_V1_PASS',
    '.validation-runtime-audit-v1/runtime-metrics.json',
    ['Validation Runtime Governance V1'],
    ['duplicate work analysis', 'runtime metrics', 'dependency graph'],
  ),
  entry(
    'VALIDATION_RUNTIME_GOVERNANCE_V1',
    'Validation Runtime Governance V1',
    'Validation Runtime Governance',
    'SELF_EVOLUTION',
    'src/validation-runtime-governance-v1/',
    'validate:validation-runtime-governance-v1',
    'VALIDATION_RUNTIME_GOVERNANCE_V1_PASS',
    '.validation-runtime-governance-v1/assessment.json',
    [],
    ['validation tiering', 'caching', 'reuse policy', 'runtime budgets'],
    ['Validation Runtime Governance ↔ UVL — governance policy vs verification execution'],
    'MEDIUM',
  ),
  entry(
    'SELF_EVOLUTION_EXECUTION_V1',
    'Self-Evolution Execution V1',
    'Self-Evolution Execution',
    'SELF_EVOLUTION',
    'src/self-evolution-execution-v1/',
    'validate:self-evolution-execution-v1',
    'SELF_EVOLUTION_EXECUTION_V1_PASS',
    '.self-evolution-execution-v1/assessment.json',
    ['Capability Audit V3.1', 'World2 Real Instantiation V1'],
    ['gap detection', 'evolution proposals', 'World2 experiments', 'promotion path'],
  ),
  entry(
    'MULTI_PROJECT_CONCURRENT_EXECUTION_V1',
    'Multi-Project Concurrent Execution V1',
    'Large-Scale Pipeline Integration',
    'MULTI_PROJECT_EXECUTION',
    'src/multi-project-concurrent-execution-v1/',
    'validate:multi-project-concurrent-execution-v1',
    'MULTI_PROJECT_CONCURRENT_EXECUTION_V1_PASS',
    '.multi-project-concurrent-execution-v1/assessment.json',
    [
      'World2 Real Instantiation V1',
      'Cloud Execution Path V1',
      'Real Build Execution Pipeline V1.1',
    ],
    ['concurrent execution proof', 'multi-project isolation', 'parallel build proof'],
    ['Multi-Project Concurrent Execution ↔ Parallel Build Orchestration — planning vs execution'],
    'MEDIUM',
  ),
  entry(
    'UNIFIED_FAILURE_ESCALATION_AUTHORITY_V1',
    'Unified Failure Escalation Authority V1',
    'Validation Runtime Governance',
    'SELF_EVOLUTION',
    'src/unified-failure-escalation-authority-v1/',
    'validate:unified-failure-escalation-authority-v1',
    'UNIFIED_FAILURE_ESCALATION_AUTHORITY_V1_PASS',
    '.unified-failure-escalation-authority-v1/assessment.json',
    [
      'Self-Evolution Execution V1',
      'World2 Real Instantiation V1',
      'Canonical Ownership V2 Registration',
      'Multi-Project Concurrent Execution V1',
    ],
    ['failure escalation', 'three-failure rule', 'escalation effectiveness'],
    ['Unified Failure Escalation ↔ Self-Evolution — authority decides, Self-Evolution executes'],
    'MEDIUM',
  ),
  entry(
    'OPERATIONAL_EVIDENCE_FRESHNESS_AUTHORITY_V1',
    'Operational Evidence Freshness Authority V1',
    'Validation Runtime Governance',
    'VALIDATION_GOVERNANCE',
    'src/operational-evidence-freshness-authority-v1/',
    'validate:operational-evidence-freshness-authority-v1',
    'OPERATIONAL_EVIDENCE_FRESHNESS_AUTHORITY_V1_PASS',
    '.operational-evidence-freshness-authority-v1/assessment.json',
    [
      'Validation Runtime Governance V1',
      'Unified Failure Escalation Authority V1',
      'Capability Audit V3.1',
      'Canonical Ownership V2 Registration',
    ],
    ['evidence freshness scoring', 'confidence decay', 'revalidation recommendations'],
    ['Operational Evidence Freshness ↔ Self-Evolution — Self-Evolution proposes cadence; authority governs'],
    'MEDIUM',
  ),
  entry(
    'CUSTOMER_OPERATIONS_PLATFORM_V1',
    'Customer Operations Platform V1',
    'Production Readiness Gate',
    'OPERATOR',
    'src/customer-operations-platform-v1/',
    'validate:customer-operations-platform-v1',
    'CUSTOMER_OPERATIONS_PLATFORM_V1_PASS',
    '.customer-operations-platform-v1/assessment.json',
    [
      'Production Readiness Gate V1',
      'Cloud Execution Path V1',
      'Multi-Project Concurrent Execution V1',
      'World2 Real Instantiation V1',
      'Strategic Capability Audit V4',
    ],
    ['customer onboarding', 'tenant isolation', 'project ownership', 'usage tracking'],
    ['Customer Operations ↔ Multi-Project — per-tenant concurrent execution'],
    'HIGH',
  ),
  entry(
    'PRODUCTION_OBSERVABILITY_PLATFORM_V1',
    'Production Observability Platform V1',
    'Customer Operations Platform',
    'OPERATOR',
    'src/production-observability-platform-v1/',
    'validate:production-observability-platform-v1',
    'PRODUCTION_OBSERVABILITY_PLATFORM_V1_PASS',
    '.production-observability-platform-v1/assessment.json',
    [
      'Customer Operations Platform V1',
      'Cloud Execution Path V1',
      'Unified Failure Escalation Authority V1',
      'Production Readiness Gate V1',
      'Strategic Capability Audit V4',
    ],
    ['application health', 'deployment tracking', 'availability monitoring', 'incident detection'],
    ['Production Observability ↔ UFEA — incidents feed escalation authority; observability reports only'],
    'HIGH',
  ),
  entry(
    'CONTINUOUS_DEPLOYMENT_PIPELINE_V1',
    'Continuous Deployment Pipeline V1',
    'Production Observability Platform',
    'OPERATOR',
    'src/continuous-deployment-pipeline-v1/',
    'validate:continuous-deployment-pipeline-v1',
    'CONTINUOUS_DEPLOYMENT_PIPELINE_V1_PASS',
    '.continuous-deployment-pipeline-v1/assessment.json',
    [
      'Production Observability Platform V1',
      'Cloud Execution Path V1',
      'Production Readiness Gate V1',
      'Unified Failure Escalation Authority V1',
      'Strategic Capability Audit V4',
    ],
    ['deployment candidates', 'promotion governance', 'deployment history', 'rollback recommendations'],
    ['Continuous Deployment ↔ Cloud Execution — candidates originate from cloud-ready artifacts'],
    'HIGH',
  ),
] as const;

export function getCanonicalOwnershipV2Entry(
  capabilityId: string,
): CanonicalOwnershipEntry | undefined {
  return CANONICAL_OWNERSHIP_V2_ENTRIES.find((e) => e.capabilityId === capabilityId);
}

export function listCanonicalOwnershipV2Entries(): readonly CanonicalOwnershipEntry[] {
  return CANONICAL_OWNERSHIP_V2_ENTRIES;
}
