/**
 * Adoption Reality Authority — markdown report builder.
 */

import {
  ADOPTION_REALITY_AUTHORITY_PASS_TOKEN,
  ADOPTION_REALITY_AUTHORITY_PHASE,
  ADOPTION_REALITY_AUTHORITY_REPORT_TITLE,
  ADOPTION_REALITY_CORE_QUESTION,
  SAFETY_GUARANTEES,
} from './adoption-reality-registry.js';
import type { AdoptionRealityReport } from './adoption-reality-types.js';

export function buildAdoptionRealityReportMarkdown(report: AdoptionRealityReport): string {
  const lines: string[] = [
    `# ${ADOPTION_REALITY_AUTHORITY_REPORT_TITLE}`,
    '',
    `Generated: ${report.generatedAt}`,
    '',
    '## Phase',
    '',
    ADOPTION_REALITY_AUTHORITY_PHASE,
    '',
    '## Core Question',
    '',
    ADOPTION_REALITY_CORE_QUESTION,
    '',
    '# Adoption Reality Authority',
    '',
    '## Adoption State',
    '',
    `**${report.adoptionRealityState}**`,
    '',
    '## Overall Adoption Score',
    '',
    `${report.overallAdoptionScore}/100 (confidence: ${report.confidence}/100)`,
    '',
    '## Repeat Usage Analysis',
    '',
    `- repeat users: ${report.repeatUsage.repeatUsers ? 'YES' : 'NO'}`,
    `- repeat user count: ${report.repeatUsage.repeatUserCount ?? 'UNKNOWN'}`,
    `- repeat sessions: ${report.repeatUsage.repeatSessions ? 'YES' : 'NO'}`,
    `- return frequency: ${report.repeatUsage.returnFrequency ? 'YES' : 'NO'}`,
    `- long-term usage: ${report.repeatUsage.longTermUsage ? 'YES' : 'NO'}`,
    `- usage consistency: ${report.repeatUsage.usageConsistency ? 'YES' : 'NO'}`,
    `- repeat usage score: ${report.repeatUsageScore}/100`,
    '',
    '## Behavioral Integration Analysis',
    '',
    `- workflow integration: ${report.behavioralIntegration.workflowIntegration ? 'YES' : 'NO'}`,
    `- habit formation signals: ${report.behavioralIntegration.habitFormationSignals ? 'YES' : 'NO'}`,
    `- operational dependence: ${report.behavioralIntegration.operationalDependence ? 'YES' : 'NO'}`,
    `- routine usage indicators: ${report.behavioralIntegration.routineUsageIndicators ? 'YES' : 'NO'}`,
    `- behavioral integration score: ${report.behavioralIntegrationScore}/100`,
    '',
    '## Feature Adoption Analysis',
    '',
    `- core feature usage: ${report.featureAdoption.coreFeatureUsage ? 'YES' : 'NO'}`,
    `- feature stickiness: ${report.featureAdoption.featureStickiness ? 'YES' : 'NO'}`,
    `- feature depth: ${report.featureAdoption.featureDepth ?? 'UNKNOWN'}`,
    `- critical feature penetration: ${report.featureAdoption.criticalFeaturePenetration ? 'YES' : 'NO'}`,
    `- feature adoption score: ${report.featureAdoptionScore}/100`,
    '',
    '## Dependency Analysis',
    '',
    `- dependency signals: ${report.userDependency.dependencySignals ? 'YES' : 'NO'}`,
    `- replacement resistance: ${report.userDependency.replacementResistance ? 'YES' : 'NO'}`,
    `- switching cost indicators: ${report.userDependency.switchingCostIndicators ? 'YES' : 'NO'}`,
    `- operational importance: ${report.userDependency.operationalImportance ? 'YES' : 'NO'}`,
    `- dependency score: ${report.dependencyScore}/100`,
    '',
    '## Risk Analysis',
    '',
    `- adoption risk score: ${report.adoptionRiskScore}/100`,
    `- drop-off risk: ${report.adoptionRisk.dropOffRisk ? 'YES' : 'NO'}`,
    `- retention risk: ${report.adoptionRisk.retentionRisk ? 'YES' : 'NO'}`,
    `- churn indicators: ${report.adoptionRisk.churnIndicators ? 'YES' : 'NO'}`,
    `- adoption fragility: ${report.adoptionRisk.adoptionFragility ? 'YES' : 'NO'}`,
    '',
    '## Observed Adoption Signals',
    '',
    `- repeat usage observed: ${report.repeatUsageObserved ? 'YES' : 'NO'}`,
    `- behavioral integration observed: ${report.behavioralIntegrationObserved ? 'YES' : 'NO'}`,
    `- feature adoption observed: ${report.featureAdoptionObserved ? 'YES' : 'NO'}`,
    `- dependency observed: ${report.dependencyObserved ? 'YES' : 'NO'}`,
    '',
    ...report.keyFindings.map((f) => `- ${f}`),
    '',
    '## Missing Evidence',
    '',
    ...report.missingEvidence.map((m) => `- ${m}`),
    ...(report.missingEvidence.length === 0 ? ['- none reported'] : []),
    '',
    '## Risk Signals',
    '',
    ...report.riskSignals.map((r) => `- ${r}`),
    ...(report.riskSignals.length === 0 ? ['- none identified'] : []),
    '',
    '## Recommended Actions',
    '',
    ...report.recommendedActions.map((a) => `- ${a}`),
    ...(report.recommendedActions.length === 0 ? ['- none'] : []),
    '',
    '## Final Verdict',
    '',
    report.finalVerdict,
    '',
    '## Safety',
    '',
    ...SAFETY_GUARANTEES.map((g) => `- ${g}`),
    '',
    '## Pass Token',
    '',
    ADOPTION_REALITY_AUTHORITY_PASS_TOKEN,
  ];

  return lines.join('\n');
}

export function formatAdoptionRealitySummary(report: AdoptionRealityReport): string {
  return (
    `Adoption Reality: ${report.adoptionRealityState} — ` +
    `score ${report.overallAdoptionScore}/100, repeatUsage=${report.repeatUsageObserved}.`
  );
}
