/**
 * Scale Readiness Reality Authority — markdown report builder.
 */

import {
  SCALE_READINESS_REALITY_AUTHORITY_PASS_TOKEN,
  SCALE_READINESS_REALITY_AUTHORITY_PHASE,
  SCALE_READINESS_REALITY_AUTHORITY_REPORT_TITLE,
  SCALE_READINESS_REALITY_CORE_QUESTION,
  SAFETY_GUARANTEES,
} from './scale-readiness-registry.js';
import type { ScaleReadinessRealityReport } from './scale-readiness-types.js';

export function buildScaleReadinessRealityReportMarkdown(
  report: ScaleReadinessRealityReport,
): string {
  const lines: string[] = [
    `# ${SCALE_READINESS_REALITY_AUTHORITY_REPORT_TITLE}`,
    '',
    `Generated: ${report.generatedAt}`,
    '',
    '## Phase',
    '',
    SCALE_READINESS_REALITY_AUTHORITY_PHASE,
    '',
    '## Core Question',
    '',
    SCALE_READINESS_REALITY_CORE_QUESTION,
    '',
    '# Scale Readiness Reality Authority',
    '',
    '## Scale Readiness State',
    '',
    `**${report.scaleReadinessState}**`,
    '',
    '## Overall Scale Readiness Score',
    '',
    `${report.overallScaleReadinessScore}/100 (confidence: ${report.confidence}/100)`,
    '',
    '## Architecture Scalability',
    '',
    `- system scalability: ${report.architecture.systemScalability ? 'YES' : 'NO'}`,
    `- bottleneck risks identified: ${report.architecture.bottleneckRisks ? 'YES' : 'NO'}`,
    `- infrastructure readiness: ${report.architecture.infrastructureReadiness ? 'YES' : 'NO'}`,
    `- capacity signals: ${report.architecture.capacitySignals ? 'YES' : 'NO'}`,
    `- architecture score: ${report.architectureScalabilityScore}/100`,
    '',
    '## Operational Scalability',
    '',
    `- operational maturity: ${report.operational.operationalMaturity ? 'YES' : 'NO'}`,
    `- monitoring coverage: ${report.operational.monitoringCoverage ? 'YES' : 'NO'}`,
    `- incident response capability: ${report.operational.incidentResponseCapability ? 'YES' : 'NO'}`,
    `- recovery capability: ${report.operational.recoveryCapability ? 'YES' : 'NO'}`,
    `- operational score: ${report.operationalScalabilityScore}/100`,
    '',
    '## Team Scalability',
    '',
    `- knowledge distribution: ${report.team.knowledgeDistribution ? 'YES' : 'NO'}`,
    `- bus factor risk assessed: ${report.team.busFactorRisk ? 'YES' : 'NO'}`,
    `- team dependency risk assessed: ${report.team.teamDependencyRisk ? 'YES' : 'NO'}`,
    `- operational ownership: ${report.team.operationalOwnership ? 'YES' : 'NO'}`,
    `- team score: ${report.teamScalabilityScore}/100`,
    '',
    '## Financial Scalability',
    '',
    `- revenue sustainability: ${report.financial.revenueSustainability ? 'YES' : 'NO'}`,
    `- growth cost signals: ${report.financial.growthCostSignals ? 'YES' : 'NO'}`,
    `- scaling cost risks assessed: ${report.financial.scalingCostRisks ? 'YES' : 'NO'}`,
    `- financial stability: ${report.financial.financialStability ? 'YES' : 'NO'}`,
    `- financial score: ${report.financialScalabilityScore}/100`,
    '',
    '## Customer Support Scalability',
    '',
    `- support capacity: ${report.customerSupport.supportCapacity ? 'YES' : 'NO'}`,
    `- support response signals: ${report.customerSupport.supportResponseSignals ? 'YES' : 'NO'}`,
    `- customer success readiness: ${report.customerSupport.customerSuccessReadiness ? 'YES' : 'NO'}`,
    `- support bottlenecks assessed: ${report.customerSupport.supportBottlenecks ? 'YES' : 'NO'}`,
    `- support score: ${report.supportScalabilityScore}/100`,
    '',
    '## Reliability Scalability',
    '',
    `- reliability history: ${report.reliability.reliabilityHistory ? 'YES' : 'NO'}`,
    `- availability signals: ${report.reliability.availabilitySignals ? 'YES' : 'NO'}`,
    `- incident trends assessed: ${report.reliability.incidentTrends ? 'YES' : 'NO'}`,
    `- failure recovery capability: ${report.reliability.failureRecoveryCapability ? 'YES' : 'NO'}`,
    `- reliability score: ${report.reliabilityScalabilityScore}/100`,
    '',
    '## Scale Risks',
    '',
    `- scale risk score: ${report.scaleRiskScore}/100`,
    ...report.scaleRisk.riskSignals.map((r) => `- ${r}`),
    ...(report.scaleRisk.riskSignals.length === 0 ? ['- no significant scale risks identified'] : []),
    '',
    '## Missing Evidence',
    '',
    ...report.missingEvidence.map((m) => `- ${m}`),
    ...(report.missingEvidence.length === 0 ? ['- none identified'] : []),
    '',
    '## Recommended Actions',
    '',
    ...report.recommendedActions.map((a) => `- ${a}`),
    '',
    '## Final Verdict',
    '',
    report.finalVerdict,
    '',
    '## Safety Guarantees',
    '',
    ...SAFETY_GUARANTEES.map((g) => `- ${g}`),
    '',
    '## Pass Token',
    '',
    SCALE_READINESS_REALITY_AUTHORITY_PASS_TOKEN,
  ];

  return lines.join('\n');
}

export function formatScaleReadinessRealitySummary(report: ScaleReadinessRealityReport): string {
  return `${report.scaleReadinessState} (${report.overallScaleReadinessScore}/100)`;
}
