/**
 * Customer Operations Platform V1 — bounds and pass token.
 */

export const CUSTOMER_OPERATIONS_PLATFORM_V1_PASS_TOKEN =
  'CUSTOMER_OPERATIONS_PLATFORM_V1_PASS';

export const CUSTOMER_OPERATIONS_PLATFORM_V1_FAIL_TOKEN =
  'CUSTOMER_OPERATIONS_PLATFORM_V1_FAIL';

export const CUSTOMER_OPERATIONS_PLATFORM_V1_REPORT_TITLE =
  'CUSTOMER_OPERATIONS_PLATFORM_V1_REPORT.md';

export const CUSTOMER_OPERATIONS_PLATFORM_V1_ARTIFACT_DIR =
  '.customer-operations-platform-v1';

export const MIN_CUSTOMERS_PROVEN = 3;

export const MIN_TENANTS_PROVEN = 3;

export const MIN_PROJECTS_REGISTERED = 5;

export const MIN_ONBOARDING_ACTIVATION_RATE = 80;

export const MIN_PLAN_TYPES = 4;

export const MAX_ISOLATION_VIOLATIONS = 0;

export const PLAN_TYPES = ['FREE', 'PRO', 'BUSINESS', 'ENTERPRISE'] as const;

export const CUSTOMER_STATUSES = [
  'ACTIVE',
  'TRIAL',
  'SUSPENDED',
  'PENDING',
  'CANCELLED',
] as const;

export const PRIOR_PASS_TOKENS = [
  'STRATEGIC_CAPABILITY_AUDIT_V4_PASS',
  'MULTI_PROJECT_CONCURRENT_EXECUTION_V1_PASS',
  'WORLD2_REAL_INSTANTIATION_V1_PASS',
  'CLOUD_EXECUTION_PATH_V1_PASS',
  'PRODUCTION_READINESS_GATE_V1_PASS',
  'CANONICAL_OWNERSHIP_V2_PASS',
] as const;
