/**
 * Production Readiness Gate V1 — bounds and pass token.
 */

export const PRODUCTION_READINESS_GATE_V1_PASS_TOKEN = 'PRODUCTION_READINESS_GATE_V1_PASS';

export const PRODUCTION_READINESS_GATE_V1_REPORT_TITLE = 'PRODUCTION_READINESS_GATE_V1_REPORT.md';

export const PRODUCTION_READINESS_GATE_V1_ARTIFACT_DIR = '.production-readiness-gate-v1';

export const MIN_PRODUCTION_READY_CATEGORIES = 15;

export const MIN_PRODUCTION_READINESS_SCORE = 80;

export const MAX_PRODUCTION_READINESS_GATE_HISTORY = 20;

export const PRODUCTION_READY_VERDICT_THRESHOLD = 80;

export const PRODUCTION_READY_WITH_WARNINGS_THRESHOLD = 70;

export const NEEDS_HARDENING_THRESHOLD = 55;
