/**
 * Large-Scale Pipeline Integration V1 — bounds and pass token.
 */

export const LARGE_SCALE_PIPELINE_INTEGRATION_V1_PASS_TOKEN =
  'LARGE_SCALE_PIPELINE_INTEGRATION_V1_PASS';

export const LARGE_SCALE_PIPELINE_INTEGRATION_V1_REPORT_TITLE =
  'LARGE_SCALE_PIPELINE_INTEGRATION_V1_REPORT.md';

export const LARGE_SCALE_PIPELINE_INTEGRATION_V1_ARTIFACT_DIR =
  '.large-scale-pipeline-integration-v1';

export const MIN_PIPELINE_SCORE = 70;

export const MIN_RBEP_BUILD_SUCCESS_RATE = 100;

export const MIN_BROAD_CATEGORY_COUNT = 50;

export const RBEP_SUITE_SIZE = 15;

export const GP_SUITE_SIZE = 10;

export const CLOUD_SUITE_SIZE = 3;

export const PRIOR_PASS_TOKENS = [
  'REAL_BUILD_EXECUTION_PIPELINE_V1_1_PASS',
  'UVL_VERIFICATION_EXECUTION_V1_PASS',
  'PRODUCTION_READINESS_GATE_V1_PASS',
  'GENERAL_PURPOSE_CODE_GENERATION_V1_PASS',
  'CLOUD_EXECUTION_PATH_V1_PASS',
  'LARGE_SCALE_MULTI_APP_VALIDATION_V1_PASS',
] as const;
