/**
 * Mobile Preview Modes — registry constants (V1).
 */

export const MOBILE_PREVIEW_MODES_V1_PASS = 'MOBILE_PREVIEW_MODES_V1_PASS';

export const MOBILE_PREVIEW_MODES_OWNER_MODULE = 'mobile-preview-modes';

export const MOBILE_PREVIEW_MODES_PHASE = '26.27';

export const MOBILE_PREVIEW_MODES_REPORT_TITLE = 'Mobile Preview Modes Report';

export const MAX_MOBILE_PREVIEW_HISTORY = 32;

export const DEVICE_PROFILE_IDS = [
  'ANDROID_PHONE_SMALL',
  'ANDROID_PHONE_MEDIUM',
  'ANDROID_PHONE_LARGE',
  'IPHONE_SMALL',
  'IPHONE_STANDARD',
  'IPHONE_PRO_MAX',
  'ANDROID_TABLET',
  'IPAD',
  'DESKTOP_STANDARD',
  'DESKTOP_WIDE',
] as const;

export const DEVICE_CATEGORIES = ['ANDROID_PHONE', 'IPHONE', 'TABLET', 'DESKTOP'] as const;

export const PREVIEW_READINESS_VALUES = [
  'NOT_READY',
  'HIGH_RISK',
  'READY_WITH_ADJUSTMENTS',
  'READY_FOR_PREVIEW',
] as const;

export const RESPONSIVE_RISK_TYPES = [
  'OVERFLOW_RISK',
  'NAVIGATION_CROWDING',
  'TOUCH_TARGET_ISSUE',
  'MODAL_SIZE_ISSUE',
  'DASHBOARD_DENSITY_ISSUE',
] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_INTELLIGENCE',
  'NO_EMULATOR_LAUNCH',
  'NO_MOBILE_BUILD_EXECUTION',
  'NO_RUNTIME_ENVIRONMENT_CREATION',
  'NO_DEPLOYMENT',
  'EVIDENCE_BASED_OUTPUTS_ONLY',
  'BOUNDED_ANALYSIS_HISTORY',
] as const;

export const TOUCH_TARGET_MIN_DP = 48;
