/**
 * Product Architect Intelligence V1 — bounds and pass token.
 */

export const PRODUCT_ARCHITECT_INTELLIGENCE_V1_PASS_TOKEN = 'PRODUCT_ARCHITECT_INTELLIGENCE_V1_PASS';

export const PRODUCT_ARCHITECT_INTELLIGENCE_OWNER_MODULE =
  'aidevengine_product_architect_intelligence' as const;

export const PRODUCT_ARCHITECT_INTELLIGENCE_PHASE = 27.8;

export const MAX_PRODUCT_ARCHITECT_INTELLIGENCE_HISTORY = 50;

export const PRODUCT_READINESS_LAUNCH_READY_THRESHOLD = 80;

export const PRODUCT_READINESS_REFINEMENT_THRESHOLD = 70;

export const PRODUCT_READINESS_COMPLETE_THRESHOLD = 90;

export const CRITICAL_PRODUCT_GAP_PENALTY = 12;

export const WARNING_PRODUCT_GAP_PENALTY = 5;

export const AFLA_PRODUCT_ARCHITECTURE_MAX_PENALTY = 20;

export const MIN_PRODUCT_ARCHITECT_SUITE_APPS = 12;
