/**
 * Operator Feed event factory — creates visibility-only feed events.
 */

import type {
  OperatorFeedConfidence,
  OperatorFeedEvent,
  OperatorFeedEventStatus,
  OperatorFeedStage,
} from './operator-feed-types.js';

let eventCounter = 0;

function nextEventId(): string {
  eventCounter += 1;
  return `ofeed-${eventCounter.toString().padStart(4, '0')}`;
}

const STAGE_SUMMARIES: Record<OperatorFeedStage, string> = {
  'Loading Context': 'Loading intelligence context for the current query.',
  'Reading Shared Memory': 'Recalling relevant shared memory facts.',
  'Reading Project Understanding': 'Reading project profile and fact inventory.',
  'Reading Project Facts': 'Gathering project facts from Project Understanding.',
  'Reading Vault Facts': 'Reading supplemental vault facts read-only.',
  'Reading Vault Intelligence': 'Loading Project Vault Intelligence context.',
  'Reading Dependency Intelligence': 'Analyzing dependency graph and blockers.',
  'Reading Workspace Intelligence': 'Resolving workspace ownership and boundaries.',
  'Reading History Intelligence': 'Reading project history and recent changes.',
  'Reading Summaries': 'Compressing intelligence sources into summaries.',
  'Reading Portfolio Intelligence': 'Aggregating multi-project portfolio context.',
  'Loading Portfolio': 'Initializing portfolio visibility context.',
  'Reading Project Inventory': 'Reading portfolio project inventory.',
  'Computing Health': 'Computing portfolio health across projects.',
  'Generating Portfolio Summary': 'Generating portfolio advisory summary.',
  'Evaluating Risks': 'Evaluating risk facts for advisory recommendation.',
  'Generating Recommendation': 'Generating advisory recommendation.',
  'Generating Project Answer': 'Composing project understanding answer.',
  'Generating Response': 'Composing final intelligence response.',
  'Response Ready': 'Visibility timeline complete — response ready.',
  'Action Identified': 'Action candidate identified for visibility review.',
  'Action Evaluated': 'Action status, priority, and blockers evaluated.',
  'Action Recommended': 'Action marked as recommended — visibility only, not executed.',
  'Action Deferred': 'Action deferred per governance gates — visibility only.',
  'Action Blocked': 'Action blocked — execution not permitted.',
  'Action Completed': 'Action visibility marked complete — no execution performed.',
  'Reasoning Started': 'Structured reasoning visibility started — no chain-of-thought exposed.',
  'Evidence Collected': 'Evidence gathered from consulted intelligence systems.',
  'Risks Evaluated': 'Visible risk findings evaluated for advisory reasoning.',
  'Blockers Evaluated': 'Blockers evaluated for advisory visibility across reasoning and progress.',
  'Confidence Calculated': 'Confidence basis calculated from structured evidence.',
  'Reasoning Ready': 'Reasoning visibility complete — structured summary ready.',
  'Progress Evaluation Started': 'Progress evaluation started — visibility only.',
  'Milestones Evaluated': 'Milestones evaluated across portfolio projects.',
  'Progress Calculated': 'Completion percentage calculated from intelligence sources.',
  'Progress Ready': 'Progress visibility complete — advisory summary ready.',
  'Failure Detected': 'Failure detection started — visibility only, no auto-fix.',
  'Failure Evaluated': 'Visible failures evaluated across intelligence sources.',
  'Severity Calculated': 'Failure severity classified for advisory visibility.',
  'Impact Evaluated': 'Affected systems and blocked capabilities evaluated.',
  'Next Step Generated': 'Advisory next step generated — visibility only, not executed.',
  'Failure Ready': 'Failure visibility complete — structured summary ready.',
  'Learning Analysis Started': 'Learning analysis started — visibility only, no self-learning.',
  'Patterns Evaluated': 'Observed patterns evaluated across intelligence sources.',
  'Failures Evaluated': 'Recurring failure patterns evaluated for learning visibility.',
  'Recommendations Evaluated': 'Recurring recommendation patterns evaluated for learning visibility.',
  'Learning Ready': 'Learning visibility complete — observed lessons ready.',
  'Execution Evaluation Started': 'Execution runtime foundation evaluation started — readiness only.',
  'Readiness Evaluation': 'Execution readiness evaluated from intelligence sources.',
  'Dependency Check': 'Dependency prerequisites checked for execution readiness.',
  'Safety Check': 'Execution safety boundary evaluated — no real execution.',
  'Execution Readiness Ready': 'Execution readiness advisory complete — simulation only.',
  'Build Task Planning Started': 'Build task runtime foundation planning started — no execution.',
  'Task Request Parsed': 'Build task request parsed into planning scope.',
  'Dependencies Resolved': 'Build task dependencies resolved from intelligence sources.',
  'Safety Gates Evaluated': 'Build task safety gates evaluated — planning only.',
  'Verification Plan Created': 'Build task verification plan created — proof criteria advisory.',
  'Build Task Plan Ready': 'Build task plan ready — simulation only, execution blocked.',
  'Code Generation Planning Started': 'Code generation runtime foundation planning started — proposal only.',
  'Generation Request Parsed': 'Code generation request parsed into proposal scope.',
  'Artifact Proposals Created': 'In-memory code artifact proposals created — no disk writes.',
  'Change Proposals Created': 'File change proposals created — not applied to project source.',
  'Generation Risks Evaluated': 'Code generation risks evaluated before any future generation.',
  'Validation Plan Created': 'Code generation validation plan created — proof criteria advisory.',
  'Code Generation Plan Ready': 'Code generation plan ready — simulation only, no file writes.',
  'Testing Planning Started': 'Testing runtime foundation planning started — no test execution.',
  'Testing Request Parsed': 'Testing request parsed into planning scope.',
  'Test Cases Created': 'Test cases modeled — simulation only, no test files written.',
  'Evidence Requirements Created': 'Evidence requirements defined — proof criteria advisory.',
  'Test Risks Evaluated': 'Testing risks evaluated before any future test execution.',
  'Simulated Results Created': 'Simulated pass/fail results created — no commands run.',
  'Testing Plan Ready': 'Testing plan ready — simulation only, execution blocked.',
  'Auto Fix Planning Started': 'Auto-fix runtime foundation planning started — no fix application.',
  'Failure Analysis Complete': 'Failure records analyzed for fix planning — advisory only.',
  'Fix Proposals Created': 'Fix proposals created — not applied to project.',
  'Alternatives Evaluated': 'Alternative fixes ranked — simulation only.',
  'Rollback Plan Created': 'Rollback plan created — prerequisites advisory.',
  'Auto Fix Plan Ready': 'Auto-fix plan ready — simulation only, no files modified.',
  'Runtime Verification Started': 'Runtime verification layer started — no runtime actions.',
  'Verification Evidence Collected': 'Verification evidence collected from Phase 14 runtime chain.',
  'Verification Gaps Evaluated': 'Verification gaps evaluated — advisory only.',
  'Trust Assessment Calculated': 'Runtime chain trust assessment calculated — simulation only.',
  'Verification Score Calculated': 'Composite verification score calculated — no execution.',
  'Runtime Verification Report Ready': 'Runtime verification report ready — verification only.',
  'World 2 Activation Started': 'World 2 execution activation planning started — no real execution.',
  'Workspace Isolation Checked': 'World 2 workspace isolation checked — World 1 protected.',
  'Governance Gates Checked': 'World 2 governance gates evaluated — approval required.',
  'Runtime Chain Linked': 'Phase 14 runtime chain linked for World 2 activation — execution blocked.',
  'Activation Readiness Evaluated': 'World 2 activation readiness evaluated — simulation only.',
  'World 2 Activation Plan Ready': 'World 2 activation plan ready — no files modified.',
  'Builder Packet Execution Started': 'Builder packet execution preparation started — no apply.',
  'Builder Packet Validated': 'Builder packet validated against activation and isolation gates.',
  'Builder Packet Steps Normalized': 'Builder packet steps normalized for Phase 15.2.',
  'Builder Packet Risks Classified': 'Step risks classified — high/critical require approval.',
  'Builder Packet Execution Packet Ready': 'Execution packet ready — simulation only.',
  'Builder Packet Execution Blocked': 'Builder packet execution blocked — inspect blockers.',
  'Controlled Apply Started': 'Controlled apply planning started — applyAllowed false.',
  'Controlled Apply Validated': 'Controlled apply preconditions validated.',
  'Controlled Apply Gates Evaluated': 'Governance gates evaluated for apply plan.',
  'Controlled Apply Risks Classified': 'Apply step risks classified.',
  'Controlled Apply Plan Ready': 'Controlled apply plan ready — no apply performed.',
  'Controlled Apply Blocked': 'Controlled apply blocked — inspect gate failures.',
  'Rollback Planning Started': 'Rollback planning started — rollbackAllowed false.',
  'Rollback Preconditions Validated': 'Rollback preconditions validated against apply plan.',
  'Rollback Snapshot Requirements Evaluated': 'Pre-apply snapshot requirements recorded — no snapshots created.',
  'Rollback Risks Classified': 'Rollback step risks classified.',
  'Rollback Plan Ready': 'Rollback plan ready — no rollback performed.',
  'Rollback Planning Blocked': 'Rollback planning blocked — inspect gate failures.',
  'Recovery Planning Started': 'Recovery planning started — recoveryAllowed false.',
  'Recovery Preconditions Validated': 'Recovery preconditions validated — rollback and apply plans linked.',
  'Recovery Failure Classified': 'Failure category classified for recovery strategy selection.',
  'Recovery Strategy Selected': 'Proposal-only recovery strategy selected.',
  'Recovery Escalation Evaluated': 'Escalation level evaluated including three-failure rule.',
  'Recovery Plan Ready': 'Recovery plan ready — recoveryAllowed remains false.',
  'Recovery Planning Blocked': 'Recovery planning blocked — inspect gate failures.',
  'Completion Planning Started': 'Completion planning started — completionAllowed false.',
  'Completion Criteria Evaluated': 'Completion criteria evaluated for project goal and safety.',
  'Completion Evidence Evaluated': 'Completion evidence records evaluated without creating artifacts.',
  'Completion Verification Evaluated': 'Verification requirements evaluated before completion.',
  'Completion Risks Classified': 'Completion risks classified including evidence and approval gaps.',
  'Completion Plan Ready': 'Completion plan ready — completionAllowed remains false.',
  'Completion Planning Blocked': 'Completion planning blocked — inspect gate failures.',
  'Preview Target Discovered': 'Preview target discovered — metadata registered.',
  'Preview Session Created': 'Preview session created — no browser launch.',
  'Preview Session Validated': 'Preview session validated against ownership and isolation gates.',
  'Preview Runtime Ready': 'Preview runtime ready — capability tracking only.',
  'Preview Runtime Blocked': 'Preview runtime blocked — inspect gate failures.',
  'Preview Intelligence Started': 'Preview intelligence analysis started — reasoning only.',
  'Preview Context Analyzed': 'Preview session, target, and workspace context analyzed.',
  'Preview Readiness Evaluated': 'Preview readiness level and score evaluated.',
  'Preview Capabilities Analyzed': 'Preview capability availability analyzed without execution.',
  'Preview Limitations Identified': 'Preview limitations identified for future visual systems.',
  'Preview Observation Plan Prepared': 'Future observation plan prepared — no actual observation.',
  'Preview Intelligence Ready': 'Preview intelligence ready — observation plan deferred to later phases.',
  'Preview Intelligence Blocked': 'Preview intelligence blocked — inspect session, target, and workspace gates.',
  'Self Vision Started': 'Self vision observation runtime started — no capture execution.',
  'Self Vision Session Created': 'Self vision session created and linked to preview session.',
  'Observation Targets Planned': 'Future observation targets planned — no analysis performed.',
  'Capture Plan Prepared': 'Capture plan prepared — no capture occurs in Phase 16.3.',
  'Self Vision Ready': 'Self vision runtime ready — observation session metadata only.',
  'Self Vision Blocked': 'Self vision blocked — inspect preview session, target, and ownership gates.',
  'UI Inspection Started': 'UI inspection started — structure identification only.',
  'Layout Structures Identified': 'Layout structures identified without quality judgment.',
  'Navigation Structures Identified': 'Navigation structures identified — no clicking or navigation.',
  'Loading Structures Identified': 'Loading structures identified — no correctness determination.',
  'Responsive Structures Identified': 'Responsive surfaces identified — no quality verification.',
  'UI Inspection Ready': 'UI inspection ready — structure inspection only.',
  'UI Inspection Blocked': 'UI inspection blocked — inspect self vision session and observation targets.',
  'Interaction Testing Started': 'Interaction testing started — simulation and outcome recording only.',
  'Interaction Plans Generated': 'Interaction plans generated for buttons, navigation, forms, and workflows.',
  'Button Testing Executed': 'Button interaction simulation executed — no correctness verdict.',
  'Navigation Testing Executed': 'Navigation interaction simulation executed — no route correctness verdict.',
  'Form Testing Executed': 'Form interaction simulation executed — no submission correctness verdict.',
  'Workflow Testing Executed': 'Workflow interaction simulation executed — no path correctness verdict.',
  'Interaction Results Recorded': 'Interaction outcomes recorded — no pass/fail or quality score.',
  'Interaction Testing Ready': 'Interaction testing ready — outcomes recorded without verdicts.',
  'Interaction Testing Blocked': 'Interaction testing blocked — inspect inspection report and self vision session.',
  'Visual Verification Started': 'Visual verification started — outcome evaluation only, no UI modification.',
  'Verification Targets Identified': 'Verification targets classified from inspection and interaction reports.',
  'Layout Verification Complete': 'Layout verification complete — regions compared without UI changes.',
  'Navigation Verification Complete': 'Navigation verification complete — structures assessed without interaction.',
  'Loading Verification Complete': 'Loading verification complete — indicators and states evaluated.',
  'Responsive Verification Complete': 'Responsive verification complete — viewport regions assessed.',
  'Interaction Verification Complete': 'Interaction outcome verification complete — no re-execution.',
  'Verification Evidence Built': 'Verification evidence records assembled — no auto-fix applied.',
  'Visual Verification Ready': 'Visual verification ready — evidence produced without repairs.',
  'Visual Verification Blocked': 'Visual verification blocked — inspect inspection and interaction reports.',
  'Verification Provider Registered': 'Verification provider registered — lifecycle only, no verification execution.',
  'Verification Session Created': 'Verification session created — awaiting future provider execution.',
  'Verification Session Started': 'Verification session started — lifecycle transition only.',
  'Verification Session Completed': 'Verification session completed — no evidence or report orchestration.',
  'Verification Session Failed': 'Verification session failed — lifecycle transition only.',
  'Verification Runtime Ready': 'Unified Verification Lab Runtime ready — providers and sessions registered.',
  'Verification Runtime Blocked': 'Verification runtime blocked — inspect provider and session registration.',
  'Verification Target Registered': 'Verification target registered — registry metadata only.',
  'Verification Dependency Registered': 'Verification dependency registered — no orchestration.',
  'Verification Requirement Registered': 'Verification requirement registered — no evidence collection.',
  'Verification Capability Registered': 'Verification capability registered — future expansion support.',
  'Verification Registry Ready': 'Verification registry ready — targets, owners, and dependencies defined.',
  'Verification Registry Blocked': 'Verification registry blocked — inspect target and owner registration.',
  'Verification Dependencies Resolved': 'Verification dependencies resolved — upstream/downstream chains defined.',
  'Verification Schedule Prepared': 'Verification schedule prepared — execution order determined, no execution.',
  'Verification Parallel Groups Identified': 'Parallel verification groups identified — future parallel support.',
  'Verification Targets Blocked': 'Verification targets blocked — inspect dependencies and prerequisites.',
  'Verification Orchestration Ready': 'Verification orchestration ready — execution plan and schedule defined.',
  'Verification Orchestration Blocked': 'Verification orchestration blocked — inspect dependency cycles and ownership.',
  'Evidence Registered': 'Evidence record registered in verification evidence authority store.',
  'Evidence Ownership Assigned': 'Evidence ownership metadata assigned to registered record.',
  'Evidence Lineage Updated': 'Evidence lineage relationships updated — parent, child, and derived links.',
  'Evidence Traceability Linked': 'Evidence traceability index linked by target, session, project, or chain.',
  'Evidence Validation Complete': 'Evidence integrity validation complete — diagnostics only.',
  'Evidence Report Generated': 'Evidence inventory, ownership, lineage, and traceability reports generated.',
  'Verification Evidence Ready': 'Verification evidence authority ready — evidence registered and validated.',
  'Verification Evidence Blocked': 'Verification evidence authority blocked — inspect registration and ownership.',
  'Report Created': 'Verification report created in reporting authority store.',
  'Report Updated': 'Verification report updated with latest findings.',
  'Report Validated': 'Verification report validated — diagnostics only.',
  'Evidence Linked': 'Report findings linked to registered evidence records.',
  'History Updated': 'Verification report history updated.',
  'Trend Updated': 'Verification trend metrics updated — historical only.',
  'Report Exported': 'Verification report exported to structured format.',
  'Report Generated': 'Verification reporting authority report bundle generated.',
  'Verification Reporting Ready': 'Verification reporting ready — evidence-backed reports available.',
  'Verification Reporting Blocked': 'Verification reporting blocked — inspect report generation and ownership.',
  'Verification Requested': 'Unified verification request accepted at entry point.',
  'Verification Routed': 'Verification request routed to registry, orchestrator, evidence, and reporting.',
  'Verification Scope Built': 'Verification scope defined for request authority.',
  'Verification Context Built': 'Verification context aggregated from all subsystems.',
  'Unified Verification Session Created': 'Unified verification entry session created — lifecycle only.',
  'Verification State Updated': 'Verification state updated — no provider execution.',
  'Verification Response Generated': 'Unified verification response generated with evidence and report references.',
  'Verification Complete': 'Unified verification complete — authority response ready.',
  'Unified Verification Ready': 'Unified verification entry ready — use requestVerification() only.',
  'Unified Verification Blocked': 'Unified verification entry blocked — inspect scope and ownership.',
  'Cloud Runtime Created': 'Cloud runtime registered at foundation authority.',
  'Cloud Runtime Initialized': 'Cloud runtime initialized — lifecycle only, no execution.',
  'Cloud Runtime Activated': 'Cloud runtime activated — authority state only.',
  'Cloud Runtime Paused': 'Cloud runtime paused — no cloud execution.',
  'Cloud Runtime Resumed': 'Cloud runtime resumed — resumable authority marker.',
  'Cloud Runtime Completed': 'Cloud runtime completed — authority lifecycle only.',
  'Cloud Runtime Failed': 'Cloud runtime failed — inspect ownership and duplicate risks.',
  'Cloud Runtime Archived': 'Cloud runtime archived — historical authority record.',
  'Cloud Runtime Ready': 'Cloud runtime foundation ready — authority surface available.',
  'Cloud Runtime Blocked': 'Cloud runtime foundation blocked — inspect registration gates.',
  'Workspace Created': 'Hosted workspace registered at workspace hosting authority.',
  'Workspace Initialized': 'Hosted workspace initialized — lifecycle only, no execution.',
  'Workspace Activated': 'Hosted workspace activated — authority state only.',
  'Workspace Isolated': 'Hosted workspace isolated — metadata only, no containers.',
  'Workspace Paused': 'Hosted workspace paused — no cloud workers.',
  'Workspace Resumed': 'Hosted workspace resumed — resumable authority marker.',
  'Workspace Completed': 'Hosted workspace completed — authority lifecycle only.',
  'Workspace Failed': 'Hosted workspace failed — inspect ownership and runtime link.',
  'Workspace Archived': 'Hosted workspace archived — historical authority record.',
  'Workspace Linked To Runtime': 'Hosted workspace linked to Cloud Runtime Foundation runtime.',
  'Workspace Hosting Ready': 'Workspace hosting foundation ready — authority surface available.',
  'Workspace Hosting Blocked': 'Workspace hosting foundation blocked — inspect registration gates.',
  'Persistent Build Created': 'Persistent build session registered — authority only, no execution.',
  'Persistent Build Initialized': 'Persistent build initialization tracked — metadata only.',
  'Persistent Build Activated': 'Persistent build activated — lifecycle tracking without execution.',
  'Persistent Build Paused': 'Persistent build paused — session state metadata updated.',
  'Persistent Build Resumed': 'Persistent build resumed — resume metadata tracked without rollback.',
  'Persistent Build Waiting For Approval': 'Persistent build waiting for approval — gate metadata only.',
  'Persistent Build Waiting For Verification': 'Persistent build waiting for verification — evidence links tracked.',
  'Persistent Build Waiting For Recovery': 'Persistent build waiting for recovery — recovery context metadata only.',
  'Persistent Build Completed': 'Persistent build completed — authority lifecycle closed without execution.',
  'Persistent Build Failed': 'Persistent build failed — inspect ownership and bridge links.',
  'Persistent Build Archived': 'Persistent build archived — historical record preserved.',
  'Persistent Build Linked To Runtime': 'Persistent build linked to Cloud Runtime Foundation — runtime source of truth.',
  'Persistent Build Linked To Workspace': 'Persistent build linked to Workspace Hosting Foundation — workspace source of truth.',
  'Persistent Build Runtime Ready': 'Persistent build runtime foundation ready — long-running build session authority.',
  'Persistent Build Runtime Blocked': 'Persistent build runtime foundation blocked — inspect registration gates.',
  'Cloud Verification Created': 'Cloud verification request registered — authority only, no provider execution.',
  'Cloud Verification Initialized': 'Cloud verification initialization tracked — metadata only.',
  'Cloud Verification Requested': 'Cloud verification requested — routes through Unified Verification Entry.',
  'Cloud Verification Linked To Unified Entry': 'Cloud verification linked to Unified Verification Entry — global verification source of truth.',
  'Cloud Verification Linked To Runtime': 'Cloud verification linked to Cloud Runtime Foundation — runtime source of truth.',
  'Cloud Verification Linked To Workspace': 'Cloud verification linked to Workspace Hosting Foundation — workspace source of truth.',
  'Cloud Verification Linked To Persistent Build': 'Cloud verification linked to Persistent Build Runtime Foundation — build source of truth.',
  'Cloud Verification Evidence Linked': 'Cloud verification evidence linked — Verification Evidence Engine source of truth.',
  'Cloud Verification Report Linked': 'Cloud verification report linked — Verification Reporting Engine source of truth.',
  'Cloud Verification Completed': 'Cloud verification completed — authority lifecycle closed without provider execution.',
  'Cloud Verification Failed': 'Cloud verification failed — inspect ownership and bridge links.',
  'Cloud Verification Archived': 'Cloud verification archived — historical record preserved.',
  'Cloud Verification Foundation Ready': 'Cloud verification foundation ready — cloud-specific verification coordination authority.',
  'Cloud Verification Foundation Blocked': 'Cloud verification foundation blocked — inspect registration gates.',
  'Cloud Failure Identified': 'Cloud failure metadata registered — authority only, no recovery execution.',
  'Cloud Recovery Candidate Identified': 'Recovery candidate registered — coordination metadata only.',
  'Cloud Recovery Plan Registered': 'Recovery plan registered — no rollback or repair actions.',
  'Cloud Recovery Linked To Runtime': 'Cloud recovery linked to Cloud Runtime Foundation — runtime source of truth.',
  'Cloud Recovery Linked To Workspace': 'Cloud recovery linked to Workspace Hosting Foundation — workspace source of truth.',
  'Cloud Recovery Linked To Build': 'Cloud recovery linked to Persistent Build Runtime Foundation — build source of truth.',
  'Cloud Recovery Linked To Verification': 'Cloud recovery linked to Cloud Verification Foundation — verification source of truth.',
  'Cloud Recovery Ready': 'Cloud recovery metadata ready — no recovery execution.',
  'Cloud Recovery Completed': 'Cloud recovery authority lifecycle closed without execution.',
  'Cloud Recovery Failed': 'Cloud recovery failed — inspect ownership and bridge links.',
  'Cloud Recovery Archived': 'Cloud recovery archived — historical record preserved.',
  'Cloud Recovery Foundation Blocked': 'Cloud recovery foundation blocked — inspect registration gates.',
  'Cloud Monitoring Created': 'Cloud monitoring record registered — authority only, no infrastructure polling.',
  'Cloud Monitoring Activated': 'Cloud monitoring activated — metadata only, no real monitoring.',
  'Health Updated': 'Monitoring health metadata updated — no infrastructure polling.',
  'Alert Created': 'Monitoring alert registered — metadata only, no notifications.',
  'Alert Acknowledged': 'Monitoring alert acknowledged — metadata only.',
  'Monitoring Linked To Runtime': 'Monitoring linked to Cloud Runtime Foundation — runtime source of truth.',
  'Monitoring Linked To Workspace': 'Monitoring linked to Workspace Hosting Foundation — workspace source of truth.',
  'Monitoring Linked To Build': 'Monitoring linked to Persistent Build Runtime Foundation — build source of truth.',
  'Monitoring Linked To Verification': 'Monitoring linked to Cloud Verification Foundation — verification source of truth.',
  'Monitoring Linked To Recovery': 'Monitoring linked to Cloud Recovery Foundation — recovery source of truth.',
  'Cloud Monitoring Completed': 'Cloud monitoring completed — authority lifecycle closed without real monitoring.',
  'Cloud Monitoring Failed': 'Cloud monitoring failed — inspect ownership and bridge links.',
  'Cloud Monitoring Archived': 'Cloud monitoring archived — historical record preserved.',
  'Cloud Monitoring Foundation Blocked': 'Cloud monitoring foundation blocked — inspect registration gates.',
  'Mobile Command Session Created': 'Mobile command session registered — authority only, no mobile UI or cloud execution.',
  'Mobile Command Connected To Cloud': 'Mobile command linked to Cloud Runtime Foundation — runtime source of truth.',
  'Mobile Command Connected To Workspace': 'Mobile command linked to Workspace Hosting Foundation — workspace source of truth.',
  'Mobile Command Connected To Build': 'Mobile command linked to Persistent Build Runtime Foundation — build source of truth.',
  'Mobile Command Connected To Verification': 'Mobile command linked to Cloud Verification Foundation — verification source of truth.',
  'Mobile Command Connected To Recovery': 'Mobile command linked to Cloud Recovery Foundation — recovery source of truth.',
  'Mobile Command Connected To Monitoring': 'Mobile command linked to Cloud Monitoring Foundation — monitoring source of truth.',
  'Mobile Command Action Allowed': 'Mobile action gate allowed — decision metadata only, no execution.',
  'Mobile Command Action Blocked': 'Mobile action gate blocked — inspect permission metadata.',
  'Mobile Command Requires Approval': 'Mobile action requires approval — waiting for founder or desktop surface.',
  'Mobile Command Desktop Recommended': 'Mobile action desktop recommended — large system work deferred to desktop.',
  'Mobile Command Completed': 'Mobile command session completed — authority lifecycle closed without execution.',
  'Mobile Command Failed': 'Mobile command failed — inspect ownership and bridge links.',
  'Mobile Command Archived': 'Mobile command archived — historical record preserved.',
  'Mobile Chat Session Created': 'Mobile chat session registered — authority only, no mobile UI or LLM execution.',
  'Mobile Chat Prompt Received': 'Mobile chat prompt intake recorded — metadata only, no prompt execution.',
  'Mobile Chat Context Ready': 'Mobile chat context prepared from upstream authorities.',
  'Mobile Chat Routed To Command': 'Mobile chat intent routed to command systems — routing metadata only.',
  'Mobile Chat Action Allowed': 'Mobile chat action gate allowed — decision metadata only.',
  'Mobile Chat Action Blocked': 'Mobile chat action gate blocked — inspect permission metadata.',
  'Mobile Chat Requires Approval': 'Mobile chat action requires approval before proceeding.',
  'Mobile Chat Desktop Recommended': 'Mobile chat action desktop recommended — defer large work to desktop.',
  'Mobile Chat Response Pending': 'Mobile chat response pending — metadata only, no LLM generation.',
  'Mobile Chat Response Ready': 'Mobile chat response state ready — metadata summary available.',
  'Mobile Chat Completed': 'Mobile chat session completed — authority lifecycle closed.',
  'Mobile Chat Failed': 'Mobile chat failed — inspect ownership and bridge links.',
  'Mobile Chat Archived': 'Mobile chat archived — historical record preserved.',
  'Mobile Preview Session Created': 'Mobile preview session registered — authority only, no mobile UI or preview streaming.',
  'Eligibility Checked': 'Mobile preview eligibility evaluated — metadata only, no preview execution.',
  'Safety Checked': 'Mobile preview safety evaluated — governance metadata only.',
  'Allowed': 'Mobile preview allowed — decision metadata only, no preview rendering.',
  'Blocked': 'Mobile preview blocked — inspect eligibility, safety, or device policy metadata.',
  'Desktop Recommended': 'Desktop recommended for mobile preview scope — defer large preview work to desktop.',
  'Link Registered': 'Preview link metadata registered — no streaming or rendering.',
  'Pending': 'Mobile preview pending — waiting for readiness metadata.',
  'Ready': 'Mobile preview ready — metadata surface available without execution.',
  'Completed': 'Mobile preview session completed — authority lifecycle closed.',
  'Failed': 'Mobile preview failed — inspect ownership and bridge links.',
  'Archived': 'Mobile preview archived — historical record preserved.',
  'Mobile Approval Session Created': 'Mobile approval session registered — authority only, no execution or push notifications.',
  'Approval Request Registered': 'Approval request metadata registered — awaiting governed decision interface.',
  'Waiting For Decision': 'Mobile approval waiting for decision — metadata only, no real approvals performed.',
  'Decision Recorded': 'Approval decision metadata recorded — authority only, no execution performed.',
  'Approval Approved': 'Approval approved metadata recorded — defer execution to governed systems.',
  'Approval Rejected': 'Approval rejected metadata recorded — no execution performed.',
  'Approval Completed': 'Mobile approval session completed — authority lifecycle closed.',
  'Approval Failed': 'Mobile approval failed — inspect ownership and bridge links.',
  'Approval Archived': 'Mobile approval archived — historical record preserved.',
  'Cross Device Session Created': 'Cross device session registered — authority only, no real device sync or connections.',
  'Device Registered': 'Device record registered — metadata only, no real device pairing.',
  'Device Linked': 'Device link registered — metadata only, no real connection established.',
  'Device Handoff Available': 'Device handoff available — metadata only, no real transfer performed.',
  'Device Handoff Requested': 'Device handoff requested — metadata only, awaiting handoff readiness.',
  'Device Handoff Ready': 'Device handoff ready — metadata only, no real transfer performed.',
  'Device Handoff Completed': 'Device handoff completed — metadata only, no real transfer performed.',
  'Device Visibility Updated': 'Cross device visibility updated — metadata only.',
  'Cross Device Completed': 'Cross device session completed — authority lifecycle closed.',
  'Cross Device Failed': 'Cross device session failed — inspect ownership and bridge links.',
  'Cross Device Archived': 'Cross device session archived — historical record preserved.',
  'Notification Created': 'Founder notification registered — authority only, no real delivery.',
  'Notification Routed': 'Notification routed — metadata only, no push, email, or SMS.',
  'Notification Visible': 'Notification visible in founder inbox — metadata only.',
  'Notification Viewed': 'Notification viewed — authority lifecycle tracked.',
  'Notification Acknowledged': 'Notification acknowledged — founder review recorded.',
  'Notification Dismissed': 'Notification dismissed — authority lifecycle updated.',
  'Notification Archived': 'Notification archived — historical record preserved.',
  'Notification Failed': 'Notification failed — inspect ownership and bridge links.',
  'Inbox Entry Created': 'Founder inbox entry registered — visualization only, references notification runtime.',
  'Inbox Entry Visible': 'Inbox entry visible — visualization layer metadata only.',
  'Inbox Entry Read': 'Inbox entry read — founder inbox state tracked.',
  'Inbox Entry Acknowledged': 'Inbox entry acknowledged — visualization metadata recorded.',
  'Inbox Entry Archived': 'Inbox entry archived — historical visualization record preserved.',
  'Inbox Entry Restored': 'Inbox entry restored from archive — visualization layer updated.',
  'Inbox Entry Failed': 'Inbox entry failed — inspect notification reference and bridge links.',
  'Notification Delivery Created': 'Notification delivery record registered — planning only, references inbox and notification authorities.',
  'Notification Delivery Planned': 'Delivery intent and policy planned — metadata only.',
  'Notification Delivery Eligibility Checked': 'Channel eligibility checked — real delivery channels blocked by policy.',
  'Notification Delivery Routed': 'Delivery route planned — no real email, SMS, or push.',
  'Notification Delivery Target Selected': 'Delivery target selected — planning metadata recorded.',
  'Notification Delivery Blocked': 'Delivery planning blocked — inspect upstream links or duplicate authority risk.',
  'Notification Delivery Deferred': 'Delivery planning deferred — resume when context is available.',
  'Notification Delivery Ready': 'Delivery planning ready — metadata complete, no real delivery.',
  'Notification Delivery Completed': 'Delivery planning completed — metadata only.',
  'Notification Delivery Failed': 'Delivery planning failed — inspect inbox and notification references.',
  'Notification Delivery Archived': 'Delivery record archived — historical planning metadata preserved.',
  'Autonomous Build Created': 'Autonomous build session registered — planning only, references mobile push upstream authority.',
  'Autonomous Goal Created': 'Autonomous build goal defined — metadata only, no code execution.',
  'Autonomous Plan Created': 'Autonomous build plan created — planning metadata recorded.',
  'Autonomous Stage Created': 'Autonomous build stage registered — pipeline stage metadata only.',
  'Autonomous Readiness Evaluated': 'Autonomous build readiness evaluated — constraints and capabilities checked.',
  'Autonomous Build Ready': 'Autonomous build planning ready — metadata complete, no execution.',
  'Autonomous Build Blocked': 'Autonomous build blocked — inspect upstream links or duplicate authority risk.',
  'Autonomous Build Paused': 'Autonomous build paused — planning metadata preserved.',
  'Autonomous Build Completed': 'Autonomous build planning completed — metadata only, no code modification.',
  'Autonomous Build Failed': 'Autonomous build planning failed — inspect push and delivery references.',
  'Autonomous Build Archived': 'Autonomous build archived — historical planning metadata preserved.',
  'Mobile Push Created': 'Mobile push record registered — planning only, references delivery and notification authorities.',
  'Mobile Push Planned': 'Push platform and policy planned — metadata only.',
  'Mobile Push Eligibility Checked': 'Push eligibility checked — real FCM/APNS connectors blocked by policy.',
  'Mobile Push Token Metadata Checked': 'Token metadata checked — alias and fingerprint only, no raw tokens.',
  'Mobile Push Payload Planned': 'Push payload planned — metadata only, no real push delivery.',
  'Mobile Push Routed': 'Push route planned — no real FCM or APNS.',
  'Mobile Push Target Selected': 'Push device target selected — planning metadata recorded.',
  'Mobile Push Blocked': 'Push planning blocked — inspect upstream links or duplicate authority risk.',
  'Mobile Push Deferred': 'Push planning deferred — resume when context is available.',
  'Mobile Push Ready': 'Push planning ready — metadata complete, no real push.',
  'Mobile Push Completed': 'Push planning completed — metadata only.',
  'Mobile Push Failed': 'Push planning failed — inspect delivery and notification references.',
  'Mobile Push Archived': 'Push record archived — historical planning metadata preserved.',
};

export function createOperatorFeedEvent(
  stage: OperatorFeedStage,
  sourceSystem: string,
  timestamp: number,
  opts: {
    status?: OperatorFeedEventStatus;
    confidence?: OperatorFeedConfidence;
    relatedProject?: string | null;
    relatedWorkspace?: string | null;
    summary?: string;
  } = {},
): OperatorFeedEvent {
  return {
    eventId: nextEventId(),
    timestamp,
    sourceSystem,
    stage,
    status: opts.status ?? 'COMPLETE',
    summary: opts.summary ?? STAGE_SUMMARIES[stage],
    confidence: opts.confidence ?? 'HIGH',
    relatedProject: opts.relatedProject ?? null,
    relatedWorkspace: opts.relatedWorkspace ?? null,
    visibilityOnly: true,
  };
}

export function resetOperatorFeedEventCounterForTests(): void {
  eventCounter = 0;
}
