/**
 * Operator Feed event factory — creates visibility-only feed events.
 */

import type {
  OperatorFeedConfidence,
  OperatorFeedEvent,
  OperatorFeedEventStatus,
  OperatorFeedStage,
} from './operator-feed-types.js';

let eventCounter = 0;

function nextEventId(): string {
  eventCounter += 1;
  return `ofeed-${eventCounter.toString().padStart(4, '0')}`;
}

const STAGE_SUMMARIES: Record<OperatorFeedStage, string> = {
  'Loading Context': 'Loading intelligence context for the current query.',
  'Reading Shared Memory': 'Recalling relevant shared memory facts.',
  'Reading Project Understanding': 'Reading project profile and fact inventory.',
  'Reading Project Facts': 'Gathering project facts from Project Understanding.',
  'Reading Vault Facts': 'Reading supplemental vault facts read-only.',
  'Reading Vault Intelligence': 'Loading Project Vault Intelligence context.',
  'Reading Dependency Intelligence': 'Analyzing dependency graph and blockers.',
  'Reading Workspace Intelligence': 'Resolving workspace ownership and boundaries.',
  'Reading History Intelligence': 'Reading project history and recent changes.',
  'Reading Summaries': 'Compressing intelligence sources into summaries.',
  'Reading Portfolio Intelligence': 'Aggregating multi-project portfolio context.',
  'Loading Portfolio': 'Initializing portfolio visibility context.',
  'Reading Project Inventory': 'Reading portfolio project inventory.',
  'Computing Health': 'Computing portfolio health across projects.',
  'Generating Portfolio Summary': 'Generating portfolio advisory summary.',
  'Evaluating Risks': 'Evaluating risk facts for advisory recommendation.',
  'Generating Recommendation': 'Generating advisory recommendation.',
  'Generating Project Answer': 'Composing project understanding answer.',
  'Generating Response': 'Composing final intelligence response.',
  'Response Ready': 'Visibility timeline complete — response ready.',
  'Action Identified': 'Action candidate identified for visibility review.',
  'Action Evaluated': 'Action status, priority, and blockers evaluated.',
  'Action Recommended': 'Action marked as recommended — visibility only, not executed.',
  'Action Deferred': 'Action deferred per governance gates — visibility only.',
  'Action Blocked': 'Action blocked — execution not permitted.',
  'Action Completed': 'Action visibility marked complete — no execution performed.',
  'Reasoning Started': 'Structured reasoning visibility started — no chain-of-thought exposed.',
  'Evidence Collected': 'Evidence gathered from consulted intelligence systems.',
  'Risks Evaluated': 'Visible risk findings evaluated for advisory reasoning.',
  'Blockers Evaluated': 'Blockers evaluated for advisory visibility across reasoning and progress.',
  'Confidence Calculated': 'Confidence basis calculated from structured evidence.',
  'Reasoning Ready': 'Reasoning visibility complete — structured summary ready.',
  'Progress Evaluation Started': 'Progress evaluation started — visibility only.',
  'Milestones Evaluated': 'Milestones evaluated across portfolio projects.',
  'Progress Calculated': 'Completion percentage calculated from intelligence sources.',
  'Progress Ready': 'Progress visibility complete — advisory summary ready.',
  'Failure Detected': 'Failure detection started — visibility only, no auto-fix.',
  'Failure Evaluated': 'Visible failures evaluated across intelligence sources.',
  'Severity Calculated': 'Failure severity classified for advisory visibility.',
  'Impact Evaluated': 'Affected systems and blocked capabilities evaluated.',
  'Next Step Generated': 'Advisory next step generated — visibility only, not executed.',
  'Failure Ready': 'Failure visibility complete — structured summary ready.',
  'Learning Analysis Started': 'Learning analysis started — visibility only, no self-learning.',
  'Patterns Evaluated': 'Observed patterns evaluated across intelligence sources.',
  'Failures Evaluated': 'Recurring failure patterns evaluated for learning visibility.',
  'Recommendations Evaluated': 'Recurring recommendation patterns evaluated for learning visibility.',
  'Learning Ready': 'Learning visibility complete — observed lessons ready.',
  'Execution Evaluation Started': 'Execution runtime foundation evaluation started — readiness only.',
  'Readiness Evaluation': 'Execution readiness evaluated from intelligence sources.',
  'Dependency Check': 'Dependency prerequisites checked for execution readiness.',
  'Safety Check': 'Execution safety boundary evaluated — no real execution.',
  'Execution Readiness Ready': 'Execution readiness advisory complete — simulation only.',
  'Build Task Planning Started': 'Build task runtime foundation planning started — no execution.',
  'Task Request Parsed': 'Build task request parsed into planning scope.',
  'Dependencies Resolved': 'Build task dependencies resolved from intelligence sources.',
  'Safety Gates Evaluated': 'Build task safety gates evaluated — planning only.',
  'Verification Plan Created': 'Build task verification plan created — proof criteria advisory.',
  'Build Task Plan Ready': 'Build task plan ready — simulation only, execution blocked.',
  'Code Generation Planning Started': 'Code generation runtime foundation planning started — proposal only.',
  'Generation Request Parsed': 'Code generation request parsed into proposal scope.',
  'Artifact Proposals Created': 'In-memory code artifact proposals created — no disk writes.',
  'Change Proposals Created': 'File change proposals created — not applied to project source.',
  'Generation Risks Evaluated': 'Code generation risks evaluated before any future generation.',
  'Validation Plan Created': 'Code generation validation plan created — proof criteria advisory.',
  'Code Generation Plan Ready': 'Code generation plan ready — simulation only, no file writes.',
  'Testing Planning Started': 'Testing runtime foundation planning started — no test execution.',
  'Testing Request Parsed': 'Testing request parsed into planning scope.',
  'Test Cases Created': 'Test cases modeled — simulation only, no test files written.',
  'Evidence Requirements Created': 'Evidence requirements defined — proof criteria advisory.',
  'Test Risks Evaluated': 'Testing risks evaluated before any future test execution.',
  'Simulated Results Created': 'Simulated pass/fail results created — no commands run.',
  'Testing Plan Ready': 'Testing plan ready — simulation only, execution blocked.',
  'Auto Fix Planning Started': 'Auto-fix runtime foundation planning started — no fix application.',
  'Failure Analysis Complete': 'Failure records analyzed for fix planning — advisory only.',
  'Fix Proposals Created': 'Fix proposals created — not applied to project.',
  'Alternatives Evaluated': 'Alternative fixes ranked — simulation only.',
  'Rollback Plan Created': 'Rollback plan created — prerequisites advisory.',
  'Auto Fix Plan Ready': 'Auto-fix plan ready — simulation only, no files modified.',
  'Runtime Verification Started': 'Runtime verification layer started — no runtime actions.',
  'Verification Evidence Collected': 'Verification evidence collected from Phase 14 runtime chain.',
  'Verification Gaps Evaluated': 'Verification gaps evaluated — advisory only.',
  'Trust Assessment Calculated': 'Runtime chain trust assessment calculated — simulation only.',
  'Verification Score Calculated': 'Composite verification score calculated — no execution.',
  'Runtime Verification Report Ready': 'Runtime verification report ready — verification only.',
  'World 2 Activation Started': 'World 2 execution activation planning started — no real execution.',
  'Workspace Isolation Checked': 'World 2 workspace isolation checked — World 1 protected.',
  'Governance Gates Checked': 'World 2 governance gates evaluated — approval required.',
  'Runtime Chain Linked': 'Phase 14 runtime chain linked for World 2 activation — execution blocked.',
  'Activation Readiness Evaluated': 'World 2 activation readiness evaluated — simulation only.',
  'World 2 Activation Plan Ready': 'World 2 activation plan ready — no files modified.',
  'Builder Packet Execution Started': 'Builder packet execution preparation started — no apply.',
  'Builder Packet Validated': 'Builder packet validated against activation and isolation gates.',
  'Builder Packet Steps Normalized': 'Builder packet steps normalized for Phase 15.2.',
  'Builder Packet Risks Classified': 'Step risks classified — high/critical require approval.',
  'Builder Packet Execution Packet Ready': 'Execution packet ready — simulation only.',
  'Builder Packet Execution Blocked': 'Builder packet execution blocked — inspect blockers.',
  'Controlled Apply Started': 'Controlled apply planning started — applyAllowed false.',
  'Controlled Apply Validated': 'Controlled apply preconditions validated.',
  'Controlled Apply Gates Evaluated': 'Governance gates evaluated for apply plan.',
  'Controlled Apply Risks Classified': 'Apply step risks classified.',
  'Controlled Apply Plan Ready': 'Controlled apply plan ready — no apply performed.',
  'Controlled Apply Blocked': 'Controlled apply blocked — inspect gate failures.',
  'Rollback Planning Started': 'Rollback planning started — rollbackAllowed false.',
  'Rollback Preconditions Validated': 'Rollback preconditions validated against apply plan.',
  'Rollback Snapshot Requirements Evaluated': 'Pre-apply snapshot requirements recorded — no snapshots created.',
  'Rollback Risks Classified': 'Rollback step risks classified.',
  'Rollback Plan Ready': 'Rollback plan ready — no rollback performed.',
  'Rollback Planning Blocked': 'Rollback planning blocked — inspect gate failures.',
  'Recovery Planning Started': 'Recovery planning started — recoveryAllowed false.',
  'Recovery Preconditions Validated': 'Recovery preconditions validated — rollback and apply plans linked.',
  'Recovery Failure Classified': 'Failure category classified for recovery strategy selection.',
  'Recovery Strategy Selected': 'Proposal-only recovery strategy selected.',
  'Recovery Escalation Evaluated': 'Escalation level evaluated including three-failure rule.',
  'Recovery Plan Ready': 'Recovery plan ready — recoveryAllowed remains false.',
  'Recovery Planning Blocked': 'Recovery planning blocked — inspect gate failures.',
  'Completion Planning Started': 'Completion planning started — completionAllowed false.',
  'Completion Criteria Evaluated': 'Completion criteria evaluated for project goal and safety.',
  'Completion Evidence Evaluated': 'Completion evidence records evaluated without creating artifacts.',
  'Completion Verification Evaluated': 'Verification requirements evaluated before completion.',
  'Completion Risks Classified': 'Completion risks classified including evidence and approval gaps.',
  'Completion Plan Ready': 'Completion plan ready — completionAllowed remains false.',
  'Completion Planning Blocked': 'Completion planning blocked — inspect gate failures.',
  'Preview Target Discovered': 'Preview target discovered — metadata registered.',
  'Preview Session Created': 'Preview session created — no browser launch.',
  'Preview Session Validated': 'Preview session validated against ownership and isolation gates.',
  'Preview Runtime Ready': 'Preview runtime ready — capability tracking only.',
  'Preview Runtime Blocked': 'Preview runtime blocked — inspect gate failures.',
  'Preview Intelligence Started': 'Preview intelligence analysis started — reasoning only.',
  'Preview Context Analyzed': 'Preview session, target, and workspace context analyzed.',
  'Preview Readiness Evaluated': 'Preview readiness level and score evaluated.',
  'Preview Capabilities Analyzed': 'Preview capability availability analyzed without execution.',
  'Preview Limitations Identified': 'Preview limitations identified for future visual systems.',
  'Preview Observation Plan Prepared': 'Future observation plan prepared — no actual observation.',
  'Preview Intelligence Ready': 'Preview intelligence ready — observation plan deferred to later phases.',
  'Preview Intelligence Blocked': 'Preview intelligence blocked — inspect session, target, and workspace gates.',
  'Self Vision Started': 'Self vision observation runtime started — no capture execution.',
  'Self Vision Session Created': 'Self vision session created and linked to preview session.',
  'Observation Targets Planned': 'Future observation targets planned — no analysis performed.',
  'Capture Plan Prepared': 'Capture plan prepared — no capture occurs in Phase 16.3.',
  'Self Vision Ready': 'Self vision runtime ready — observation session metadata only.',
  'Self Vision Blocked': 'Self vision blocked — inspect preview session, target, and ownership gates.',
  'UI Inspection Started': 'UI inspection started — structure identification only.',
  'Layout Structures Identified': 'Layout structures identified without quality judgment.',
  'Navigation Structures Identified': 'Navigation structures identified — no clicking or navigation.',
  'Loading Structures Identified': 'Loading structures identified — no correctness determination.',
  'Responsive Structures Identified': 'Responsive surfaces identified — no quality verification.',
  'UI Inspection Ready': 'UI inspection ready — structure inspection only.',
  'UI Inspection Blocked': 'UI inspection blocked — inspect self vision session and observation targets.',
  'Interaction Testing Started': 'Interaction testing started — simulation and outcome recording only.',
  'Interaction Plans Generated': 'Interaction plans generated for buttons, navigation, forms, and workflows.',
  'Button Testing Executed': 'Button interaction simulation executed — no correctness verdict.',
  'Navigation Testing Executed': 'Navigation interaction simulation executed — no route correctness verdict.',
  'Form Testing Executed': 'Form interaction simulation executed — no submission correctness verdict.',
  'Workflow Testing Executed': 'Workflow interaction simulation executed — no path correctness verdict.',
  'Interaction Results Recorded': 'Interaction outcomes recorded — no pass/fail or quality score.',
  'Interaction Testing Ready': 'Interaction testing ready — outcomes recorded without verdicts.',
  'Interaction Testing Blocked': 'Interaction testing blocked — inspect inspection report and self vision session.',
  'Visual Verification Started': 'Visual verification started — outcome evaluation only, no UI modification.',
  'Verification Targets Identified': 'Verification targets classified from inspection and interaction reports.',
  'Layout Verification Complete': 'Layout verification complete — regions compared without UI changes.',
  'Navigation Verification Complete': 'Navigation verification complete — structures assessed without interaction.',
  'Loading Verification Complete': 'Loading verification complete — indicators and states evaluated.',
  'Responsive Verification Complete': 'Responsive verification complete — viewport regions assessed.',
  'Interaction Verification Complete': 'Interaction outcome verification complete — no re-execution.',
  'Verification Evidence Built': 'Verification evidence records assembled — no auto-fix applied.',
  'Visual Verification Ready': 'Visual verification ready — evidence produced without repairs.',
  'Visual Verification Blocked': 'Visual verification blocked — inspect inspection and interaction reports.',
  'Verification Provider Registered': 'Verification provider registered — lifecycle only, no verification execution.',
  'Verification Session Created': 'Verification session created — awaiting future provider execution.',
  'Verification Session Started': 'Verification session started — lifecycle transition only.',
  'Verification Session Completed': 'Verification session completed — no evidence or report orchestration.',
  'Verification Session Failed': 'Verification session failed — lifecycle transition only.',
  'Verification Runtime Ready': 'Unified Verification Lab Runtime ready — providers and sessions registered.',
  'Verification Runtime Blocked': 'Verification runtime blocked — inspect provider and session registration.',
  'Verification Target Registered': 'Verification target registered — registry metadata only.',
  'Verification Dependency Registered': 'Verification dependency registered — no orchestration.',
  'Verification Requirement Registered': 'Verification requirement registered — no evidence collection.',
  'Verification Capability Registered': 'Verification capability registered — future expansion support.',
  'Verification Registry Ready': 'Verification registry ready — targets, owners, and dependencies defined.',
  'Verification Registry Blocked': 'Verification registry blocked — inspect target and owner registration.',
  'Verification Dependencies Resolved': 'Verification dependencies resolved — upstream/downstream chains defined.',
  'Verification Schedule Prepared': 'Verification schedule prepared — execution order determined, no execution.',
  'Verification Parallel Groups Identified': 'Parallel verification groups identified — future parallel support.',
  'Verification Targets Blocked': 'Verification targets blocked — inspect dependencies and prerequisites.',
  'Verification Orchestration Ready': 'Verification orchestration ready — execution plan and schedule defined.',
  'Verification Orchestration Blocked': 'Verification orchestration blocked — inspect dependency cycles and ownership.',
};

export function createOperatorFeedEvent(
  stage: OperatorFeedStage,
  sourceSystem: string,
  timestamp: number,
  opts: {
    status?: OperatorFeedEventStatus;
    confidence?: OperatorFeedConfidence;
    relatedProject?: string | null;
    relatedWorkspace?: string | null;
    summary?: string;
  } = {},
): OperatorFeedEvent {
  return {
    eventId: nextEventId(),
    timestamp,
    sourceSystem,
    stage,
    status: opts.status ?? 'COMPLETE',
    summary: opts.summary ?? STAGE_SUMMARIES[stage],
    confidence: opts.confidence ?? 'HIGH',
    relatedProject: opts.relatedProject ?? null,
    relatedWorkspace: opts.relatedWorkspace ?? null,
    visibilityOnly: true,
  };
}

export function resetOperatorFeedEventCounterForTests(): void {
  eventCounter = 0;
}
