/**
 * Operator Feed stage mapper — maps routing capabilities to visibility stages.
 */

import type { SelectedCapability } from '../command-center-brain/general-question-understanding/general-question-types.js';
import type { OperatorFeedStage } from './operator-feed-types.js';

const CAPABILITY_STAGE_MAP: Partial<Record<SelectedCapability, OperatorFeedStage[]>> = {
  UNIFIED_DECISION_LAYER: [
    'Loading Context',
    'Reading Dependency Intelligence',
    'Evaluating Risks',
    'Generating Recommendation',
    'Response Ready',
  ],
  PORTFOLIO_INTELLIGENCE: [
    'Loading Portfolio',
    'Reading Project Inventory',
    'Computing Health',
    'Generating Portfolio Summary',
    'Response Ready',
  ],
  PROJECT_SUMMARIZATION_ENGINE: [
    'Loading Context',
    'Reading Summaries',
    'Generating Response',
    'Response Ready',
  ],
  PROJECT_HISTORY_INTELLIGENCE: [
    'Loading Context',
    'Reading History Intelligence',
    'Generating Response',
    'Response Ready',
  ],
  WORKSPACE_INTELLIGENCE: [
    'Loading Context',
    'Reading Workspace Intelligence',
    'Generating Response',
    'Response Ready',
  ],
  DEPENDENCY_INTELLIGENCE: [
    'Loading Context',
    'Reading Dependency Intelligence',
    'Generating Response',
    'Response Ready',
  ],
  PROJECT_VAULT_INTELLIGENCE: [
    'Loading Context',
    'Reading Vault Intelligence',
    'Reading Vault Facts',
    'Generating Response',
    'Response Ready',
  ],
  PROJECT_KNOWLEDGE_REASONING: [
    'Loading Context',
    'Reading Project Facts',
    'Reading Vault Facts',
    'Generating Project Answer',
    'Response Ready',
  ],
  PROJECT_UNDERSTANDING: [
    'Loading Context',
    'Reading Project Understanding',
    'Reading Project Facts',
    'Generating Project Answer',
    'Response Ready',
  ],
  TIMELINE_INTELLIGENCE: [
    'Loading Context',
    'Reading History Intelligence',
    'Generating Response',
    'Response Ready',
  ],
  SHARED_MEMORY_RECALL: [
    'Loading Context',
    'Reading Shared Memory',
    'Generating Response',
    'Response Ready',
  ],
  ACTION_VISIBILITY_ENGINE: [
    'Action Identified',
    'Action Evaluated',
    'Action Recommended',
    'Response Ready',
  ],
  REASONING_VISIBILITY_ENGINE: [
    'Reasoning Started',
    'Evidence Collected',
    'Risks Evaluated',
    'Blockers Evaluated',
    'Confidence Calculated',
    'Reasoning Ready',
    'Response Ready',
  ],
  PROGRESS_INTELLIGENCE: [
    'Progress Evaluation Started',
    'Milestones Evaluated',
    'Blockers Evaluated',
    'Progress Calculated',
    'Progress Ready',
    'Response Ready',
  ],
  FAILURE_VISIBILITY_ENGINE: [
    'Failure Detected',
    'Failure Evaluated',
    'Severity Calculated',
    'Impact Evaluated',
    'Next Step Generated',
    'Failure Ready',
    'Response Ready',
  ],
  LEARNING_VISIBILITY_ENGINE: [
    'Learning Analysis Started',
    'Patterns Evaluated',
    'Failures Evaluated',
    'Recommendations Evaluated',
    'Learning Ready',
    'Response Ready',
  ],
  EXECUTION_RUNTIME_FOUNDATION: [
    'Execution Evaluation Started',
    'Readiness Evaluation',
    'Dependency Check',
    'Safety Check',
    'Execution Readiness Ready',
    'Response Ready',
  ],
  BUILD_TASK_RUNTIME_FOUNDATION: [
    'Build Task Planning Started',
    'Task Request Parsed',
    'Dependencies Resolved',
    'Safety Gates Evaluated',
    'Verification Plan Created',
    'Build Task Plan Ready',
    'Response Ready',
  ],
  CODE_GENERATION_RUNTIME_FOUNDATION: [
    'Code Generation Planning Started',
    'Generation Request Parsed',
    'Artifact Proposals Created',
    'Change Proposals Created',
    'Generation Risks Evaluated',
    'Validation Plan Created',
    'Code Generation Plan Ready',
    'Response Ready',
  ],
  TESTING_RUNTIME_FOUNDATION: [
    'Testing Planning Started',
    'Testing Request Parsed',
    'Test Cases Created',
    'Evidence Requirements Created',
    'Test Risks Evaluated',
    'Simulated Results Created',
    'Testing Plan Ready',
    'Response Ready',
  ],
  AUTO_FIX_RUNTIME_FOUNDATION: [
    'Auto Fix Planning Started',
    'Failure Analysis Complete',
    'Fix Proposals Created',
    'Alternatives Evaluated',
    'Risks Evaluated',
    'Rollback Plan Created',
    'Verification Plan Created',
    'Auto Fix Plan Ready',
    'Response Ready',
  ],
  RUNTIME_VERIFICATION_LAYER: [
    'Runtime Verification Started',
    'Verification Evidence Collected',
    'Verification Gaps Evaluated',
    'Trust Assessment Calculated',
    'Verification Score Calculated',
    'Runtime Verification Report Ready',
    'Response Ready',
  ],
  WORLD2_EXECUTION_ACTIVATION: [
    'World 2 Activation Started',
    'Workspace Isolation Checked',
    'Governance Gates Checked',
    'Runtime Chain Linked',
    'Activation Readiness Evaluated',
    'World 2 Activation Plan Ready',
    'Response Ready',
  ],
  WORLD2_BUILDER_PACKET_EXECUTION: [
    'Builder Packet Execution Started',
    'Builder Packet Validated',
    'Builder Packet Steps Normalized',
    'Builder Packet Risks Classified',
    'Builder Packet Execution Packet Ready',
    'Builder Packet Execution Blocked',
    'Response Ready',
  ],
  WORLD2_CONTROLLED_APPLY_RUNTIME: [
    'Controlled Apply Started',
    'Controlled Apply Validated',
    'Controlled Apply Gates Evaluated',
    'Controlled Apply Risks Classified',
    'Controlled Apply Plan Ready',
    'Controlled Apply Blocked',
    'Response Ready',
  ],
  WORLD2_ROLLBACK_RUNTIME: [
    'Rollback Planning Started',
    'Rollback Preconditions Validated',
    'Rollback Snapshot Requirements Evaluated',
    'Rollback Risks Classified',
    'Rollback Plan Ready',
    'Rollback Planning Blocked',
    'Response Ready',
  ],
  WORLD2_RECOVERY_RUNTIME: [
    'Recovery Planning Started',
    'Recovery Preconditions Validated',
    'Recovery Failure Classified',
    'Recovery Strategy Selected',
    'Recovery Escalation Evaluated',
    'Recovery Plan Ready',
    'Recovery Planning Blocked',
    'Response Ready',
  ],
  WORLD2_COMPLETION_RUNTIME: [
    'Completion Planning Started',
    'Completion Criteria Evaluated',
    'Completion Evidence Evaluated',
    'Completion Verification Evaluated',
    'Completion Risks Classified',
    'Completion Plan Ready',
    'Completion Planning Blocked',
    'Response Ready',
  ],
  LIVE_PREVIEW_RUNTIME: [
    'Preview Target Discovered',
    'Preview Session Created',
    'Preview Session Validated',
    'Preview Runtime Ready',
    'Preview Runtime Blocked',
    'Response Ready',
  ],
  PREVIEW_INTELLIGENCE: [
    'Preview Intelligence Started',
    'Preview Context Analyzed',
    'Preview Readiness Evaluated',
    'Preview Capabilities Analyzed',
    'Preview Limitations Identified',
    'Preview Observation Plan Prepared',
    'Preview Intelligence Ready',
    'Preview Intelligence Blocked',
    'Response Ready',
  ],
  SELF_VISION_RUNTIME: [
    'Self Vision Started',
    'Self Vision Session Created',
    'Observation Targets Planned',
    'Capture Plan Prepared',
    'Self Vision Ready',
    'Self Vision Blocked',
    'Response Ready',
  ],
  UI_INSPECTION_ENGINE: [
    'UI Inspection Started',
    'Layout Structures Identified',
    'Navigation Structures Identified',
    'Loading Structures Identified',
    'Responsive Structures Identified',
    'UI Inspection Ready',
    'UI Inspection Blocked',
    'Response Ready',
  ],
  INTERACTION_TESTING_ENGINE: [
    'Interaction Testing Started',
    'Interaction Plans Generated',
    'Button Testing Executed',
    'Navigation Testing Executed',
    'Form Testing Executed',
    'Workflow Testing Executed',
    'Interaction Results Recorded',
    'Interaction Testing Ready',
    'Interaction Testing Blocked',
    'Response Ready',
  ],
  VISUAL_VERIFICATION_ENGINE: [
    'Visual Verification Started',
    'Verification Targets Identified',
    'Layout Verification Complete',
    'Navigation Verification Complete',
    'Loading Verification Complete',
    'Responsive Verification Complete',
    'Interaction Verification Complete',
    'Verification Evidence Built',
    'Visual Verification Ready',
    'Visual Verification Blocked',
    'Response Ready',
  ],
  UNIFIED_VERIFICATION_LAB_RUNTIME: [
    'Verification Provider Registered',
    'Verification Session Created',
    'Verification Session Started',
    'Verification Session Completed',
    'Verification Session Failed',
    'Verification Runtime Ready',
    'Verification Runtime Blocked',
    'Response Ready',
  ],
  VERIFICATION_REGISTRY: [
    'Verification Target Registered',
    'Verification Dependency Registered',
    'Verification Requirement Registered',
    'Verification Capability Registered',
    'Verification Registry Ready',
    'Verification Registry Blocked',
    'Response Ready',
  ],
  VERIFICATION_ORCHESTRATOR: [
    'Verification Plan Created',
    'Verification Dependencies Resolved',
    'Verification Schedule Prepared',
    'Verification Parallel Groups Identified',
    'Verification Targets Blocked',
    'Verification Orchestration Ready',
    'Verification Orchestration Blocked',
    'Response Ready',
  ],
  VERIFICATION_EVIDENCE_ENGINE: [
    'Evidence Registered',
    'Evidence Ownership Assigned',
    'Evidence Lineage Updated',
    'Evidence Traceability Linked',
    'Evidence Validation Complete',
    'Evidence Report Generated',
    'Verification Evidence Ready',
    'Verification Evidence Blocked',
    'Response Ready',
  ],
  VERIFICATION_REPORTING_ENGINE: [
    'Report Created',
    'Report Updated',
    'Evidence Linked',
    'History Updated',
    'Trend Updated',
    'Report Validated',
    'Report Exported',
    'Report Generated',
    'Verification Reporting Ready',
    'Verification Reporting Blocked',
    'Response Ready',
  ],
  UNIFIED_VERIFICATION_ENTRY: [
    'Verification Requested',
    'Verification Routed',
    'Verification Scope Built',
    'Verification Context Built',
    'Unified Verification Session Created',
    'Verification State Updated',
    'Verification Response Generated',
    'Verification Complete',
    'Unified Verification Ready',
    'Unified Verification Blocked',
    'Response Ready',
  ],
  CLOUD_RUNTIME_FOUNDATION: [
    'Cloud Runtime Created',
    'Cloud Runtime Initialized',
    'Cloud Runtime Activated',
    'Cloud Runtime Paused',
    'Cloud Runtime Resumed',
    'Cloud Runtime Completed',
    'Cloud Runtime Failed',
    'Cloud Runtime Archived',
    'Cloud Runtime Ready',
    'Cloud Runtime Blocked',
    'Response Ready',
  ],
  WORKSPACE_HOSTING_FOUNDATION: [
    'Workspace Created',
    'Workspace Initialized',
    'Workspace Linked To Runtime',
    'Workspace Activated',
    'Workspace Isolated',
    'Workspace Paused',
    'Workspace Resumed',
    'Workspace Completed',
    'Workspace Failed',
    'Workspace Archived',
    'Workspace Hosting Ready',
    'Workspace Hosting Blocked',
    'Response Ready',
  ],
  PERSISTENT_BUILD_RUNTIME_FOUNDATION: [
    'Persistent Build Created',
    'Persistent Build Initialized',
    'Persistent Build Linked To Runtime',
    'Persistent Build Linked To Workspace',
    'Persistent Build Activated',
    'Persistent Build Paused',
    'Persistent Build Resumed',
    'Persistent Build Waiting For Approval',
    'Persistent Build Waiting For Verification',
    'Persistent Build Waiting For Recovery',
    'Persistent Build Completed',
    'Persistent Build Failed',
    'Persistent Build Archived',
    'Persistent Build Runtime Ready',
    'Persistent Build Runtime Blocked',
    'Response Ready',
  ],
  CLOUD_VERIFICATION_FOUNDATION: [
    'Cloud Verification Created',
    'Cloud Verification Initialized',
    'Cloud Verification Linked To Unified Entry',
    'Cloud Verification Linked To Runtime',
    'Cloud Verification Linked To Workspace',
    'Cloud Verification Linked To Persistent Build',
    'Cloud Verification Requested',
    'Cloud Verification Evidence Linked',
    'Cloud Verification Report Linked',
    'Cloud Verification Completed',
    'Cloud Verification Failed',
    'Cloud Verification Archived',
    'Cloud Verification Foundation Ready',
    'Cloud Verification Foundation Blocked',
    'Response Ready',
  ],
  CLOUD_RECOVERY_FOUNDATION: [
    'Cloud Failure Identified',
    'Cloud Recovery Candidate Identified',
    'Cloud Recovery Plan Registered',
    'Cloud Recovery Linked To Runtime',
    'Cloud Recovery Linked To Workspace',
    'Cloud Recovery Linked To Build',
    'Cloud Recovery Linked To Verification',
    'Cloud Recovery Ready',
    'Cloud Recovery Completed',
    'Cloud Recovery Failed',
    'Cloud Recovery Archived',
    'Cloud Recovery Foundation Blocked',
    'Response Ready',
  ],
  CLOUD_MONITORING_FOUNDATION: [
    'Cloud Monitoring Created',
    'Cloud Monitoring Activated',
    'Health Updated',
    'Alert Created',
    'Alert Acknowledged',
    'Monitoring Linked To Runtime',
    'Monitoring Linked To Workspace',
    'Monitoring Linked To Build',
    'Monitoring Linked To Verification',
    'Monitoring Linked To Recovery',
    'Cloud Monitoring Completed',
    'Cloud Monitoring Failed',
    'Cloud Monitoring Archived',
    'Cloud Monitoring Foundation Blocked',
    'Response Ready',
  ],
  MOBILE_COMMAND_RUNTIME_FOUNDATION: [
    'Mobile Command Session Created',
    'Mobile Command Connected To Cloud',
    'Mobile Command Connected To Workspace',
    'Mobile Command Connected To Build',
    'Mobile Command Connected To Verification',
    'Mobile Command Connected To Recovery',
    'Mobile Command Connected To Monitoring',
    'Mobile Command Action Allowed',
    'Mobile Command Action Blocked',
    'Mobile Command Requires Approval',
    'Mobile Command Desktop Recommended',
    'Mobile Command Completed',
    'Mobile Command Failed',
    'Mobile Command Archived',
    'Response Ready',
  ],
  MOBILE_CHAT_RUNTIME_FOUNDATION: [
    'Mobile Chat Session Created',
    'Mobile Chat Prompt Received',
    'Mobile Chat Context Ready',
    'Mobile Chat Routed To Command',
    'Mobile Chat Action Allowed',
    'Mobile Chat Action Blocked',
    'Mobile Chat Requires Approval',
    'Mobile Chat Desktop Recommended',
    'Mobile Chat Response Pending',
    'Mobile Chat Response Ready',
    'Mobile Chat Completed',
    'Mobile Chat Failed',
    'Mobile Chat Archived',
    'Response Ready',
  ],
  MOBILE_PREVIEW_RUNTIME_FOUNDATION: [
    'Mobile Preview Session Created',
    'Eligibility Checked',
    'Safety Checked',
    'Allowed',
    'Blocked',
    'Desktop Recommended',
    'Link Registered',
    'Pending',
    'Ready',
    'Completed',
    'Failed',
    'Archived',
    'Response Ready',
  ],
  MOBILE_APPROVAL_RUNTIME_FOUNDATION: [
    'Mobile Approval Session Created',
    'Approval Request Registered',
    'Waiting For Decision',
    'Decision Recorded',
    'Approval Approved',
    'Approval Rejected',
    'Approval Completed',
    'Approval Failed',
    'Approval Archived',
    'Response Ready',
  ],
  CROSS_DEVICE_RUNTIME_FOUNDATION: [
    'Cross Device Session Created',
    'Device Registered',
    'Device Linked',
    'Device Handoff Available',
    'Device Handoff Requested',
    'Device Handoff Ready',
    'Device Handoff Completed',
    'Device Visibility Updated',
    'Cross Device Completed',
    'Cross Device Failed',
    'Cross Device Archived',
    'Response Ready',
  ],
  FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION: [
    'Notification Created',
    'Notification Routed',
    'Notification Visible',
    'Notification Viewed',
    'Notification Acknowledged',
    'Notification Dismissed',
    'Notification Archived',
    'Notification Failed',
    'Response Ready',
  ],
  FOUNDER_INBOX_FOUNDATION: [
    'Inbox Entry Created',
    'Inbox Entry Visible',
    'Inbox Entry Read',
    'Inbox Entry Acknowledged',
    'Inbox Entry Archived',
    'Inbox Entry Restored',
    'Inbox Entry Failed',
    'Response Ready',
  ],
  BUILD_STRATEGY_ENGINE: [
    'Build Strategy Created',
    'Build Strategy Classified',
    'Build Mode Selected',
    'Autonomy Level Selected',
    'Build Risk Evaluated',
    'Build Confidence Evaluated',
    'Build Depth Selected',
    'Build Stages Recommended',
    'Build Strategy Ready',
    'Build Strategy Blocked',
    'Build Strategy Completed',
    'Build Strategy Failed',
    'Response Ready',
  ],
  AUTONOMOUS_BUILDER_FOUNDATION: [
    'Autonomous Build Created',
    'Autonomous Goal Created',
    'Autonomous Plan Created',
    'Autonomous Stage Created',
    'Autonomous Readiness Evaluated',
    'Autonomous Build Ready',
    'Autonomous Build Blocked',
    'Autonomous Build Paused',
    'Autonomous Build Completed',
    'Autonomous Build Failed',
    'Autonomous Build Archived',
    'Response Ready',
  ],
  MOBILE_PUSH_FOUNDATION: [
    'Mobile Push Created',
    'Mobile Push Planned',
    'Mobile Push Eligibility Checked',
    'Mobile Push Token Metadata Checked',
    'Mobile Push Payload Planned',
    'Mobile Push Routed',
    'Mobile Push Target Selected',
    'Mobile Push Blocked',
    'Mobile Push Deferred',
    'Mobile Push Ready',
    'Mobile Push Completed',
    'Mobile Push Failed',
    'Mobile Push Archived',
    'Response Ready',
  ],
  NOTIFICATION_DELIVERY_FOUNDATION: [
    'Notification Delivery Created',
    'Notification Delivery Planned',
    'Notification Delivery Eligibility Checked',
    'Notification Delivery Routed',
    'Notification Delivery Target Selected',
    'Notification Delivery Blocked',
    'Notification Delivery Deferred',
    'Notification Delivery Ready',
    'Notification Delivery Completed',
    'Notification Delivery Failed',
    'Notification Delivery Archived',
    'Response Ready',
  ],
};

const DEFAULT_STAGES: OperatorFeedStage[] = [
  'Loading Context',
  'Reading Project Understanding',
  'Generating Response',
  'Response Ready',
];

export function mapCapabilityToFeedStages(
  primaryCapability: SelectedCapability | null,
  supplementalCapabilities: SelectedCapability[] = [],
): OperatorFeedStage[] {
  if (!primaryCapability) return [...DEFAULT_STAGES];

  const base = CAPABILITY_STAGE_MAP[primaryCapability] ?? DEFAULT_STAGES;
  const stages = new Set<OperatorFeedStage>(base);

  if (supplementalCapabilities.includes('SHARED_MEMORY_RECALL')) {
    stages.add('Reading Shared Memory');
  }
  if (supplementalCapabilities.includes('PROJECT_VAULT_INTELLIGENCE')) {
    stages.add('Reading Vault Intelligence');
  }
  if (supplementalCapabilities.includes('DEPENDENCY_INTELLIGENCE')) {
    stages.add('Reading Dependency Intelligence');
  }

  const ordered = [...base];
  for (const stage of stages) {
    if (!ordered.includes(stage)) ordered.splice(ordered.length - 1, 0, stage);
  }

  if (!ordered.includes('Response Ready')) ordered.push('Response Ready');
  return ordered;
}

export function sourceSystemForCapability(capability: SelectedCapability | null): string {
  if (!capability) return 'command_center_brain';
  const map: Partial<Record<SelectedCapability, string>> = {
    UNIFIED_DECISION_LAYER: 'unified_decision_layer',
    PORTFOLIO_INTELLIGENCE: 'portfolio_intelligence',
    PROJECT_SUMMARIZATION_ENGINE: 'project_summarization_engine',
    PROJECT_HISTORY_INTELLIGENCE: 'project_history_intelligence',
    WORKSPACE_INTELLIGENCE: 'workspace_intelligence',
    DEPENDENCY_INTELLIGENCE: 'dependency_intelligence',
    PROJECT_VAULT_INTELLIGENCE: 'project_vault_intelligence',
    PROJECT_KNOWLEDGE_REASONING: 'project_understanding_engine',
    PROJECT_UNDERSTANDING: 'project_understanding_engine',
    TIMELINE_INTELLIGENCE: 'timeline_intelligence',
    SHARED_MEMORY_RECALL: 'shared_memory_layer',
    ACTION_VISIBILITY_ENGINE: 'action_visibility_engine',
    REASONING_VISIBILITY_ENGINE: 'reasoning_visibility_engine',
    PROGRESS_INTELLIGENCE: 'progress_intelligence',
    FAILURE_VISIBILITY_ENGINE: 'failure_visibility_engine',
    LEARNING_VISIBILITY_ENGINE: 'learning_visibility_engine',
    EXECUTION_RUNTIME_FOUNDATION: 'execution_runtime',
    BUILD_TASK_RUNTIME_FOUNDATION: 'build_task_runtime',
    CODE_GENERATION_RUNTIME_FOUNDATION: 'code_generation_runtime',
    TESTING_RUNTIME_FOUNDATION: 'testing_runtime',
    AUTO_FIX_RUNTIME_FOUNDATION: 'auto_fix_runtime',
    RUNTIME_VERIFICATION_LAYER: 'runtime_verification_layer',
    CLOUD_RUNTIME_FOUNDATION: 'cloud_runtime_foundation',
    WORKSPACE_HOSTING_FOUNDATION: 'workspace_hosting_foundation',
    PERSISTENT_BUILD_RUNTIME_FOUNDATION: 'persistent_build_runtime_foundation',
    CLOUD_VERIFICATION_FOUNDATION: 'cloud_verification_foundation',
    CLOUD_RECOVERY_FOUNDATION: 'cloud_recovery_foundation',
    CLOUD_MONITORING_FOUNDATION: 'cloud_monitoring_foundation',
    MOBILE_COMMAND_RUNTIME_FOUNDATION: 'mobile_command_runtime_foundation',
    MOBILE_CHAT_RUNTIME_FOUNDATION: 'mobile_chat_runtime_foundation',
    MOBILE_PREVIEW_RUNTIME_FOUNDATION: 'mobile_preview_runtime_foundation',
    MOBILE_APPROVAL_RUNTIME_FOUNDATION: 'mobile_approval_runtime_foundation',
    CROSS_DEVICE_RUNTIME_FOUNDATION: 'cross_device_runtime_foundation',
    FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION: 'founder_notification_runtime_foundation',
    FOUNDER_INBOX_FOUNDATION: 'founder_inbox_foundation',
    NOTIFICATION_DELIVERY_FOUNDATION: 'notification_delivery_foundation',
    MOBILE_PUSH_FOUNDATION: 'mobile_push_foundation',
    BUILD_STRATEGY_ENGINE: 'build_strategy_engine',
    AUTONOMOUS_BUILDER_FOUNDATION: 'autonomous_builder_foundation',
  };
  return map[capability] ?? 'command_center_brain';
}

export function sourceSystemsForStages(stages: OperatorFeedStage[]): string[] {
  const systems = new Set<string>(['operator_feed']);
  for (const stage of stages) {
    if (stage.includes('Memory')) systems.add('shared_memory_layer');
    if (stage.includes('Project Understanding') || stage.includes('Project Facts')) {
      systems.add('project_understanding_engine');
    }
    if (stage.includes('Vault')) systems.add('project_vault_intelligence');
    if (stage.includes('Dependency')) systems.add('dependency_intelligence');
    if (stage.includes('Workspace')) systems.add('workspace_intelligence');
    if (stage.includes('History')) systems.add('project_history_intelligence');
    if (stage.includes('Summaries')) systems.add('project_summarization_engine');
    if (stage.includes('Portfolio') || stage.includes('Inventory') || stage.includes('Computing Health')) {
      systems.add('portfolio_intelligence');
    }
    if (stage.includes('Recommendation') || stage.includes('Evaluating Risks')) {
      systems.add('unified_decision_layer');
    }
    if (stage.includes('Action')) {
      systems.add('action_visibility_engine');
    }
    if (stage.includes('Reasoning') || stage.includes('Evidence') || stage.includes('Confidence')) {
      systems.add('reasoning_visibility_engine');
    }
    if (stage.includes('Progress') || stage.includes('Milestones Evaluated')) {
      systems.add('progress_intelligence');
    }
    if (stage.includes('Failure') || stage.includes('Severity Calculated') || stage.includes('Next Step Generated')) {
      systems.add('failure_visibility_engine');
    }
    if (stage.includes('Learning') || stage.includes('Patterns Evaluated') || stage.includes('Recommendations Evaluated')) {
      systems.add('learning_visibility_engine');
    }
  }
  systems.add('command_center_brain');
  return [...systems];
}
