/**
 * Planning Gate Authority — registry constants (V1).
 */

export const PLANNING_GATE_AUTHORITY_V1_PASS = 'PLANNING_GATE_AUTHORITY_V1_PASS';

export const PLANNING_GATE_AUTHORITY_OWNER_MODULE = 'planning-gate-authority';

export const PLANNING_GATE_AUTHORITY_PHASE = '26.29';

export const PLANNING_GATE_AUTHORITY_REPORT_TITLE = 'Planning Gate Authority Report';

export const MAX_PLANNING_GATE_HISTORY = 32;

export const PLANNING_READINESS_CATEGORIES = [
  'NOT_READY',
  'NEEDS_CLARIFICATION',
  'READY_WITH_GAPS',
  'READY_FOR_PLANNING',
] as const;

export const PLANNING_GATE_DECISIONS = [
  'REJECT_PLANNING',
  'REQUEST_CLARIFICATION',
  'ALLOW_LIMITED_PLANNING',
  'ALLOW_FULL_PLANNING',
] as const;

export const PLANNING_RISK_TYPES = [
  'MISSING_REQUIREMENTS',
  'CONFLICTING_EVIDENCE',
  'PLATFORM_AMBIGUITY',
  'WORKFLOW_AMBIGUITY',
  'ROLE_AMBIGUITY',
  'INTEGRATION_AMBIGUITY',
] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_GATE_AUTHORITY',
  'NO_PLANNING_EXECUTION',
  'NO_ARCHITECTURE_GENERATION',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MODIFICATION',
  'NO_AUTONOMOUS_EXECUTION',
  'EVIDENCE_BASED_OUTPUTS_ONLY',
  'BOUNDED_ANALYSIS_HISTORY',
] as const;

export const COVERAGE_DIMENSIONS = [
  'REQUIREMENTS',
  'WORKFLOWS',
  'SCREENS',
  'ROLES',
  'INTEGRATIONS',
  'BUSINESS_LOGIC',
] as const;
