/**
 * Capability routing table — declarative route entries for brain routing.
 */

import type { ContextNeed, SelectedCapability } from './general-question-types.js';
import type { CapabilityDetectorKey } from './capability-routing-detectors.js';

export type FoundationCategory =
  | 'mobile'
  | 'notification'
  | 'cloud'
  | 'world2'
  | 'autonomous'
  | 'verification'
  | 'execution'
  | 'general';

export interface CapabilityRouteEntry {
  routeId: string;
  capabilityId: SelectedCapability;
  phase: number;
  domain: string;
  foundationCategory: FoundationCategory;
  priority: number;
  routingReason: string;
  companionCapabilities: SelectedCapability[];
  detectorKey: CapabilityDetectorKey;
  keywords: string[];
}

export interface CompanionRouteEntry {
  detectorKey: CapabilityDetectorKey;
  companions: SelectedCapability[];
}

export const CONTEXT_CAPABILITY_MAP: Partial<Record<ContextNeed, SelectedCapability>> = {
  PROJECT_PROFILE: 'PROJECT_UNDERSTANDING',
  PROJECT_FACTS: 'PROJECT_KNOWLEDGE_REASONING',
  RISK_FACTS: 'PROJECT_KNOWLEDGE_REASONING',
  MISSING_CAPABILITIES: 'PROJECT_KNOWLEDGE_REASONING',
  BLOCKERS: 'PROJECT_KNOWLEDGE_REASONING',
  SHARED_MEMORY: 'SHARED_MEMORY_RECALL',
  CROSS_SYSTEM_RELATIONSHIPS: 'CROSS_SYSTEM_AWARENESS',
  ROADMAP_STATE: 'ROADMAP_AWARENESS',
  OWNERSHIP_REGISTRY: 'SYSTEM_AWARENESS',
  RUNTIME_STATUS: 'PROJECT_KNOWLEDGE_REASONING',
  DEVELOPMENT_KNOWLEDGE: 'DEVELOPMENT_REASONING',
  DEBUG_CONTEXT: 'DEBUGGING_REASONING',
  TIMELINE_STATE: 'TIMELINE_INTELLIGENCE',
  DEPENDENCY_FACTS: 'DEPENDENCY_INTELLIGENCE',
  WORKSPACE_FACTS: 'WORKSPACE_INTELLIGENCE',
  HISTORY_FACTS: 'PROJECT_HISTORY_INTELLIGENCE',
  SUMMARIZATION_FACTS: 'PROJECT_SUMMARIZATION_ENGINE',
  PORTFOLIO_FACTS: 'PORTFOLIO_INTELLIGENCE',
  ACTION_VISIBILITY_FACTS: 'ACTION_VISIBILITY_ENGINE',
  REASONING_VISIBILITY_FACTS: 'REASONING_VISIBILITY_ENGINE',
  PROGRESS_INTELLIGENCE_FACTS: 'PROGRESS_INTELLIGENCE',
  FAILURE_VISIBILITY_FACTS: 'FAILURE_VISIBILITY_ENGINE',
  LEARNING_VISIBILITY_FACTS: 'LEARNING_VISIBILITY_ENGINE',
  EXECUTION_RUNTIME_FACTS: 'EXECUTION_RUNTIME_FOUNDATION',
  BUILD_TASK_RUNTIME_FACTS: 'BUILD_TASK_RUNTIME_FOUNDATION',
  CODE_GENERATION_RUNTIME_FACTS: 'CODE_GENERATION_RUNTIME_FOUNDATION',
  TESTING_RUNTIME_FACTS: 'TESTING_RUNTIME_FOUNDATION',
  AUTO_FIX_RUNTIME_FACTS: 'AUTO_FIX_RUNTIME_FOUNDATION',
  RUNTIME_VERIFICATION_FACTS: 'RUNTIME_VERIFICATION_LAYER',
  WORLD2_EXECUTION_ACTIVATION_FACTS: 'WORLD2_EXECUTION_ACTIVATION',
  WORLD2_BUILDER_PACKET_EXECUTION_FACTS: 'WORLD2_BUILDER_PACKET_EXECUTION',
  WORLD2_CONTROLLED_APPLY_RUNTIME_FACTS: 'WORLD2_CONTROLLED_APPLY_RUNTIME',
  WORLD2_ROLLBACK_RUNTIME_FACTS: 'WORLD2_ROLLBACK_RUNTIME',
  WORLD2_RECOVERY_RUNTIME_FACTS: 'WORLD2_RECOVERY_RUNTIME',
  WORLD2_COMPLETION_RUNTIME_FACTS: 'WORLD2_COMPLETION_RUNTIME',
  LIVE_PREVIEW_RUNTIME_FACTS: 'LIVE_PREVIEW_RUNTIME',
  PREVIEW_INTELLIGENCE_FACTS: 'PREVIEW_INTELLIGENCE',
  SELF_VISION_RUNTIME_FACTS: 'SELF_VISION_RUNTIME',
  UI_INSPECTION_ENGINE_FACTS: 'UI_INSPECTION_ENGINE',
  INTERACTION_TESTING_ENGINE_FACTS: 'INTERACTION_TESTING_ENGINE',
  VISUAL_VERIFICATION_ENGINE_FACTS: 'VISUAL_VERIFICATION_ENGINE',
  UNIFIED_VERIFICATION_LAB_RUNTIME_FACTS: 'UNIFIED_VERIFICATION_LAB_RUNTIME',
  VERIFICATION_REGISTRY_FACTS: 'VERIFICATION_REGISTRY',
  VERIFICATION_ORCHESTRATOR_FACTS: 'VERIFICATION_ORCHESTRATOR',
  VERIFICATION_EVIDENCE_ENGINE_FACTS: 'VERIFICATION_EVIDENCE_ENGINE',
  VERIFICATION_REPORTING_ENGINE_FACTS: 'VERIFICATION_REPORTING_ENGINE',
  UNIFIED_VERIFICATION_ENTRY_FACTS: 'UNIFIED_VERIFICATION_ENTRY',
  CLOUD_RUNTIME_FOUNDATION_FACTS: 'CLOUD_RUNTIME_FOUNDATION',
  WORKSPACE_HOSTING_FOUNDATION_FACTS: 'WORKSPACE_HOSTING_FOUNDATION',
  PERSISTENT_BUILD_RUNTIME_FOUNDATION_FACTS: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION',
  CLOUD_VERIFICATION_FOUNDATION_FACTS: 'CLOUD_VERIFICATION_FOUNDATION',
  CLOUD_RECOVERY_FOUNDATION_FACTS: 'CLOUD_RECOVERY_FOUNDATION',
  CLOUD_MONITORING_FOUNDATION_FACTS: 'CLOUD_MONITORING_FOUNDATION',
  MOBILE_COMMAND_RUNTIME_FOUNDATION_FACTS: 'MOBILE_COMMAND_RUNTIME_FOUNDATION',
  MOBILE_CHAT_RUNTIME_FOUNDATION_FACTS: 'MOBILE_CHAT_RUNTIME_FOUNDATION',
  MOBILE_PREVIEW_RUNTIME_FOUNDATION_FACTS: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION',
  MOBILE_APPROVAL_RUNTIME_FOUNDATION_FACTS: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION',
  CROSS_DEVICE_RUNTIME_FOUNDATION_FACTS: 'CROSS_DEVICE_RUNTIME_FOUNDATION',
  FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION_FACTS: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION',
  FOUNDER_INBOX_FOUNDATION_FACTS: 'FOUNDER_INBOX_FOUNDATION',
  NOTIFICATION_DELIVERY_FOUNDATION_FACTS: 'NOTIFICATION_DELIVERY_FOUNDATION',
  AUTONOMOUS_BUILDER_FOUNDATION_FACTS: 'AUTONOMOUS_BUILDER_FOUNDATION',
  MOBILE_PUSH_FOUNDATION_FACTS: 'MOBILE_PUSH_FOUNDATION',
};

export const PRIMARY_ROUTE_ENTRIES: readonly CapabilityRouteEntry[] = [
  { routeId: 'portfolio-intelligence', capabilityId: 'PORTFOLIO_INTELLIGENCE', phase: 12, domain: 'portfolio', foundationCategory: 'general', priority: 1, routingReason: 'Portfolio-oriented question — PORTFOLIO_INTELLIGENCE aggregates multi-project health, risk, priority, and comparison across all Phase 12 sources.', companionCapabilities: [], detectorKey: 'portfolioIntelligence', keywords: ['portfolio', 'multi-project'] },
  { routeId: 'mobile-approval', capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', phase: 18.4, domain: 'mobile-approval', foundationCategory: 'mobile', priority: 2, routingReason: 'Mobile approval question — MOBILE_APPROVAL_RUNTIME_FOUNDATION is the mobile approval session, request, decision, governance, and context authority; no execution, push notifications, or real approvals.', companionCapabilities: [], detectorKey: 'mobileApprovalRuntimeFoundation', keywords: ['mobile approval', 'approval session'] },
  { routeId: 'autonomous-builder', capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION', phase: 19.1, domain: 'autonomous-builder', foundationCategory: 'autonomous', priority: 3, routingReason: 'Autonomous builder question — AUTONOMOUS_BUILDER_FOUNDATION is the build planning, goal/plan/stage metadata, and readiness evaluation authority referencing Mobile Push Foundation; planning only, no code execution.', companionCapabilities: [], detectorKey: 'autonomousBuilderFoundation', keywords: ['autonomous builder', 'autonomous build'] },
  { routeId: 'mobile-push', capabilityId: 'MOBILE_PUSH_FOUNDATION', phase: 19, domain: 'mobile-push', foundationCategory: 'mobile', priority: 4, routingReason: 'Mobile push question — MOBILE_PUSH_FOUNDATION is the push planning, token metadata, payload planning, and platform targeting authority referencing Notification Delivery Foundation; no real push, FCM, APNS, or raw token storage.', companionCapabilities: [], detectorKey: 'mobilePushFoundation', keywords: ['mobile push', 'push token'] },
  { routeId: 'notification-delivery', capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION', phase: 18.5, domain: 'notification-delivery', foundationCategory: 'notification', priority: 5, routingReason: 'Notification delivery question — NOTIFICATION_DELIVERY_FOUNDATION is the delivery planning, routing, targeting, and channel eligibility authority referencing Founder Inbox and Founder Notification Runtime; no real email, SMS, push, FCM, or APNS.', companionCapabilities: [], detectorKey: 'notificationDeliveryFoundation', keywords: ['notification delivery', 'delivery routing'] },
  { routeId: 'founder-inbox', capabilityId: 'FOUNDER_INBOX_FOUNDATION', phase: 18.5, domain: 'founder-inbox', foundationCategory: 'notification', priority: 6, routingReason: 'Founder inbox question — FOUNDER_INBOX_FOUNDATION is the founder inbox visualization and organization layer referencing Founder Notification Runtime; no notification authority or delivery.', companionCapabilities: [], detectorKey: 'founderInboxFoundation', keywords: ['founder inbox', 'inbox entry'] },
  { routeId: 'founder-notification', capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', phase: 18.3, domain: 'founder-notification', foundationCategory: 'notification', priority: 7, routingReason: 'Founder notification question — FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION is the founder notification routing, visibility, priority, and channel authority; no real delivery, push, email, or SMS.', companionCapabilities: [], detectorKey: 'founderNotificationRuntimeFoundation', keywords: ['founder notification'] },
  { routeId: 'cross-device', capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION', phase: 18.2, domain: 'cross-device', foundationCategory: 'mobile', priority: 8, routingReason: 'Cross device question — CROSS_DEVICE_RUNTIME_FOUNDATION is the cross device session, device link, handoff, and visibility authority; no real sync, connections, or device pairing.', companionCapabilities: [], detectorKey: 'crossDeviceRuntimeFoundation', keywords: ['cross device', 'device link'] },
  { routeId: 'mobile-preview', capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', phase: 18.1, domain: 'mobile-preview', foundationCategory: 'mobile', priority: 9, routingReason: 'Mobile preview question — MOBILE_PREVIEW_RUNTIME_FOUNDATION is the mobile preview session, eligibility, safety, link, and desktop-recommendation authority; no mobile UI, preview streaming, or preview rendering.', companionCapabilities: [], detectorKey: 'mobilePreviewRuntimeFoundation', keywords: ['mobile preview'] },
  { routeId: 'mobile-chat', capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION', phase: 18, domain: 'mobile-chat', foundationCategory: 'mobile', priority: 10, routingReason: 'Mobile chat question — MOBILE_CHAT_RUNTIME_FOUNDATION is the mobile chat session, prompt, message, routing, and response-state authority; no mobile UI, LLM execution, or cloud execution.', companionCapabilities: [], detectorKey: 'mobileChatRuntimeFoundation', keywords: ['mobile chat'] },
  { routeId: 'mobile-command', capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION', phase: 17.9, domain: 'mobile-command', foundationCategory: 'mobile', priority: 11, routingReason: 'Mobile command question — MOBILE_COMMAND_RUNTIME_FOUNDATION is the mobile command session and permission authority for cloud runtime, workspace, build, verification, recovery, and monitoring links; no mobile UI, push notifications, or cloud execution.', companionCapabilities: [], detectorKey: 'mobileCommandRuntimeFoundation', keywords: ['mobile command'] },
  { routeId: 'cloud-monitoring', capabilityId: 'CLOUD_MONITORING_FOUNDATION', phase: 17.8, domain: 'cloud-monitoring', foundationCategory: 'cloud', priority: 12, routingReason: 'Cloud monitoring question — CLOUD_MONITORING_FOUNDATION is the cloud monitoring authority for health metadata, alerts, ownership, state, lifecycle, and context; no real infrastructure monitoring, cloud provider connections, or notifications.', companionCapabilities: [], detectorKey: 'cloudMonitoringFoundation', keywords: ['cloud monitoring'] },
  { routeId: 'cloud-recovery', capabilityId: 'CLOUD_RECOVERY_FOUNDATION', phase: 17.7, domain: 'cloud-recovery', foundationCategory: 'cloud', priority: 13, routingReason: 'Cloud recovery question — CLOUD_RECOVERY_FOUNDATION is the cloud recovery coordination authority for failure metadata, recovery candidates, plans, ownership, state, lifecycle, scope, and context; no recovery execution, rollback, or file mutation.', companionCapabilities: [], detectorKey: 'cloudRecoveryFoundation', keywords: ['cloud recovery'] },
  { routeId: 'cloud-verification', capabilityId: 'CLOUD_VERIFICATION_FOUNDATION', phase: 17.6, domain: 'cloud-verification', foundationCategory: 'cloud', priority: 14, routingReason: 'Cloud verification question — CLOUD_VERIFICATION_FOUNDATION is the cloud-specific verification coordination authority for registration, ownership, state, lifecycle, scope, and context; routes global verification through Unified Verification Entry; no provider execution.', companionCapabilities: [], detectorKey: 'cloudVerificationFoundation', keywords: ['cloud verification'] },
  { routeId: 'persistent-build', capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', phase: 17.5, domain: 'persistent-build', foundationCategory: 'cloud', priority: 15, routingReason: 'Persistent build question — PERSISTENT_BUILD_RUNTIME_FOUNDATION is the long-running build session authority for registration, ownership, state, lifecycle, context, progress, and resume metadata; Cloud Runtime Foundation remains runtime source of truth; Workspace Hosting Foundation remains workspace source of truth; no real builds or file mutation.', companionCapabilities: [], detectorKey: 'persistentBuildRuntimeFoundation', keywords: ['persistent build'] },
  { routeId: 'workspace-hosting', capabilityId: 'WORKSPACE_HOSTING_FOUNDATION', phase: 17.4, domain: 'workspace-hosting', foundationCategory: 'cloud', priority: 16, routingReason: 'Workspace hosting question — WORKSPACE_HOSTING_FOUNDATION is the hosted workspace authority for registration, ownership, state, lifecycle, isolation, and runtime links; Cloud Runtime Foundation remains runtime source of truth; no cloud workers or builds.', companionCapabilities: [], detectorKey: 'workspaceHostingFoundation', keywords: ['workspace hosting', 'hosted workspace'] },
  { routeId: 'cloud-runtime', capabilityId: 'CLOUD_RUNTIME_FOUNDATION', phase: 17.3, domain: 'cloud-runtime', foundationCategory: 'cloud', priority: 17, routingReason: 'Cloud runtime question — CLOUD_RUNTIME_FOUNDATION is the cloud runtime authority for registration, ownership, state, lifecycle, and history; no builds or cloud execution.', companionCapabilities: [], detectorKey: 'cloudRuntimeFoundation', keywords: ['cloud runtime'] },
  { routeId: 'unified-verification', capabilityId: 'UNIFIED_VERIFICATION_ENTRY', phase: 17.2, domain: 'unified-verification', foundationCategory: 'verification', priority: 18, routingReason: 'Unified verification question — UNIFIED_VERIFICATION_ENTRY is the single authority surface; routes to registry, orchestrator, evidence, and reporting without direct subsystem access.', companionCapabilities: [], detectorKey: 'unifiedVerificationEntry', keywords: ['unified verification'] },
  { routeId: 'verification-reporting', capabilityId: 'VERIFICATION_REPORTING_ENGINE', phase: 17.1, domain: 'verification-reporting', foundationCategory: 'verification', priority: 19, routingReason: 'Verification reporting question — VERIFICATION_REPORTING_ENGINE transforms evidence and orchestration into structured reports; no verification execution, trust decisions, or auto-fix.', companionCapabilities: [], detectorKey: 'verificationReportingEngine', keywords: ['verification report'] },
  { routeId: 'verification-evidence', capabilityId: 'VERIFICATION_EVIDENCE_ENGINE', phase: 17, domain: 'verification-evidence', foundationCategory: 'verification', priority: 20, routingReason: 'Verification evidence question — VERIFICATION_EVIDENCE_ENGINE provides evidence authority for registration, ownership, lineage, and traceability; no verification execution, trust decisions, or auto-fix.', companionCapabilities: [], detectorKey: 'verificationEvidenceEngine', keywords: ['verification evidence'] },
  { routeId: 'verification-orchestrator', capabilityId: 'VERIFICATION_ORCHESTRATOR', phase: 16.9, domain: 'verification-orchestrator', foundationCategory: 'verification', priority: 21, routingReason: 'Verification orchestrator question — VERIFICATION_ORCHESTRATOR coordinates execution planning, scheduling, and readiness; no verification execution, evidence generation, or auto-fix.', companionCapabilities: [], detectorKey: 'verificationOrchestrator', keywords: ['verification orchestrator'] },
  { routeId: 'verification-registry', capabilityId: 'VERIFICATION_REGISTRY', phase: 16.8, domain: 'verification-registry', foundationCategory: 'verification', priority: 22, routingReason: 'Verification registry question — VERIFICATION_REGISTRY defines targets, ownership, dependencies, and requirements; no verification execution, orchestration, or auto-fix.', companionCapabilities: [], detectorKey: 'verificationRegistry', keywords: ['verification registry'] },
  { routeId: 'uvl-runtime', capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME', phase: 16.7, domain: 'uvl-runtime', foundationCategory: 'verification', priority: 23, routingReason: 'UVL runtime question — UNIFIED_VERIFICATION_LAB_RUNTIME registers providers and manages verification sessions; no verification execution, evidence generation, or auto-fix.', companionCapabilities: [], detectorKey: 'unifiedVerificationLabRuntime', keywords: ['uvl', 'verification lab'] },
  { routeId: 'visual-verification', capabilityId: 'VISUAL_VERIFICATION_ENGINE', phase: 16.6, domain: 'visual-verification', foundationCategory: 'verification', priority: 24, routingReason: 'Visual verification question — VISUAL_VERIFICATION_ENGINE evaluates visual outcomes and produces verification evidence; no UI modification, interaction execution, or repairs.', companionCapabilities: [], detectorKey: 'visualVerificationEngine', keywords: ['visual verification'] },
  { routeId: 'interaction-testing', capabilityId: 'INTERACTION_TESTING_ENGINE', phase: 16.5, domain: 'interaction-testing', foundationCategory: 'verification', priority: 25, routingReason: 'Interaction testing question — INTERACTION_TESTING_ENGINE builds plans, executes simulations, and records outcomes; no correctness verdicts or quality scoring.', companionCapabilities: [], detectorKey: 'interactionTestingEngine', keywords: ['interaction testing'] },
  { routeId: 'ui-inspection', capabilityId: 'UI_INSPECTION_ENGINE', phase: 16.4, domain: 'ui-inspection', foundationCategory: 'verification', priority: 26, routingReason: 'UI inspection question — UI_INSPECTION_ENGINE inspects layout, navigation, loading, and responsive structures; no clicking, interaction testing, or visual verification.', companionCapabilities: [], detectorKey: 'uiInspectionEngine', keywords: ['ui inspection'] },
  { routeId: 'self-vision', capabilityId: 'SELF_VISION_RUNTIME', phase: 16.3, domain: 'self-vision', foundationCategory: 'verification', priority: 27, routingReason: 'Self vision runtime question — SELF_VISION_RUNTIME manages visual observation sessions, capture plans, and observation targets; no screenshot analysis or interaction testing.', companionCapabilities: [], detectorKey: 'selfVisionRuntime', keywords: ['self vision'] },
  { routeId: 'preview-intelligence', capabilityId: 'PREVIEW_INTELLIGENCE', phase: 16.2, domain: 'preview-intelligence', foundationCategory: 'verification', priority: 28, routingReason: 'Preview intelligence question — PREVIEW_INTELLIGENCE reasons about preview readiness, capabilities, limitations, and future observation plans; no browser launch or visual execution.', companionCapabilities: [], detectorKey: 'previewIntelligence', keywords: ['preview intelligence'] },
  { routeId: 'live-preview', capabilityId: 'LIVE_PREVIEW_RUNTIME', phase: 16.1, domain: 'live-preview', foundationCategory: 'verification', priority: 29, routingReason: 'Live preview question — LIVE_PREVIEW_RUNTIME represents and manages preview targets and sessions with capability tracking; no browser launch or UI inspection.', companionCapabilities: [], detectorKey: 'livePreviewRuntime', keywords: ['live preview'] },
  { routeId: 'world2-completion', capabilityId: 'WORLD2_COMPLETION_RUNTIME', phase: 15.5, domain: 'world2-completion', foundationCategory: 'world2', priority: 30, routingReason: 'Completion question — WORLD2_COMPLETION_RUNTIME prepares completion safety plans from recovery/rollback/apply context with criteria, evidence, and verification requirements; completionAllowed remains false.', companionCapabilities: [], detectorKey: 'world2CompletionRuntime', keywords: ['world2 completion'] },
  { routeId: 'world2-recovery', capabilityId: 'WORLD2_RECOVERY_RUNTIME', phase: 15.4, domain: 'world2-recovery', foundationCategory: 'world2', priority: 31, routingReason: 'Recovery question — WORLD2_RECOVERY_RUNTIME prepares recovery safety plans from rollback plans and failure context with strategy selection, escalation evaluation, and three-failure rule; recoveryAllowed remains false.', companionCapabilities: [], detectorKey: 'world2RecoveryRuntime', keywords: ['world2 recovery'] },
  { routeId: 'world2-rollback', capabilityId: 'WORLD2_ROLLBACK_RUNTIME', phase: 15.3, domain: 'world2-rollback', foundationCategory: 'world2', priority: 32, routingReason: 'Rollback question — WORLD2_ROLLBACK_RUNTIME prepares rollback safety plans from controlled apply plans with snapshot requirements and gate evaluation; rollbackAllowed remains false.', companionCapabilities: [], detectorKey: 'world2RollbackRuntime', keywords: ['world2 rollback'] },
  { routeId: 'world2-controlled-apply', capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME', phase: 15.2, domain: 'world2-controlled-apply', foundationCategory: 'world2', priority: 33, routingReason: 'Controlled apply question — WORLD2_CONTROLLED_APPLY_RUNTIME converts execution packets into governed apply plans with gate evaluation, risk classification, and approval recording; applyAllowed remains false.', companionCapabilities: [], detectorKey: 'world2ControlledApplyRuntime', keywords: ['controlled apply'] },
  { routeId: 'world2-builder-packet', capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION', phase: 15.1, domain: 'world2-builder-packet', foundationCategory: 'world2', priority: 34, routingReason: 'Builder packet execution question — WORLD2_BUILDER_PACKET_EXECUTION prepares governed execution packets from builder packets with validation, risk classification, and approval recording without apply operations.', companionCapabilities: [], detectorKey: 'world2BuilderPacketExecution', keywords: ['builder packet'] },
  { routeId: 'world2-execution-activation', capabilityId: 'WORLD2_EXECUTION_ACTIVATION', phase: 15, domain: 'world2-execution', foundationCategory: 'world2', priority: 35, routingReason: 'World 2 execution activation question — WORLD2_EXECUTION_ACTIVATION evaluates governed, isolated, simulation-first activation plans with workspace isolation, governance gates, and Phase 14 runtime chain linkage without performing real execution.', companionCapabilities: [], detectorKey: 'world2ExecutionActivation', keywords: ['world2 execution', 'execution activation'] },
  { routeId: 'runtime-verification', capabilityId: 'RUNTIME_VERIFICATION_LAYER', phase: 14.6, domain: 'runtime-verification', foundationCategory: 'execution', priority: 36, routingReason: 'Runtime verification question — RUNTIME_VERIFICATION_LAYER verifies execution, build, generation, testing, and auto-fix plans with evidence, gaps, trust assessment, and score without executing runtime actions.', companionCapabilities: [], detectorKey: 'runtimeVerificationLayer', keywords: ['runtime verification'] },
  { routeId: 'auto-fix', capabilityId: 'AUTO_FIX_RUNTIME_FOUNDATION', phase: 14.5, domain: 'auto-fix', foundationCategory: 'execution', priority: 37, routingReason: 'Auto-fix planning question — AUTO_FIX_RUNTIME_FOUNDATION plans fix proposals, alternatives, rollback, verification, and simulated results linked to failures, testing, code generation, build tasks, and execution packets without applying fixes.', companionCapabilities: [], detectorKey: 'autoFixRuntimeFoundation', keywords: ['auto-fix', 'autofix'] },
  { routeId: 'testing-runtime', capabilityId: 'TESTING_RUNTIME_FOUNDATION', phase: 14.4, domain: 'testing-runtime', foundationCategory: 'execution', priority: 38, routingReason: 'Testing planning question — TESTING_RUNTIME_FOUNDATION plans test cases, pass/fail criteria, evidence requirements, simulated results, and risks linked to code generation, build tasks, and execution packets without running tests.', companionCapabilities: [], detectorKey: 'testingRuntimeFoundation', keywords: ['testing runtime', 'test planning'] },
  { routeId: 'code-generation', capabilityId: 'CODE_GENERATION_RUNTIME_FOUNDATION', phase: 14.3, domain: 'code-generation', foundationCategory: 'execution', priority: 39, routingReason: 'Code generation planning question — CODE_GENERATION_RUNTIME_FOUNDATION proposes artifacts, file changes, strategy, risks, and validation linked to build tasks and execution packets without writing project files.', companionCapabilities: [], detectorKey: 'codeGenerationRuntimeFoundation', keywords: ['code generation'] },
  { routeId: 'build-task', capabilityId: 'BUILD_TASK_RUNTIME_FOUNDATION', phase: 14.2, domain: 'build-task', foundationCategory: 'execution', priority: 40, routingReason: 'Build task planning question — BUILD_TASK_RUNTIME_FOUNDATION plans steps, dependencies, safety gates, and verification linked to execution packets without performing execution.', companionCapabilities: [], detectorKey: 'buildTaskRuntimeFoundation', keywords: ['build task'] },
  { routeId: 'execution-runtime', capabilityId: 'EXECUTION_RUNTIME_FOUNDATION', phase: 14.1, domain: 'execution-runtime', foundationCategory: 'execution', priority: 41, routingReason: 'Execution readiness question — EXECUTION_RUNTIME_FOUNDATION evaluates readiness, blockers, dependencies, and safety boundaries without performing execution.', companionCapabilities: [], detectorKey: 'executionRuntimeFoundation', keywords: ['execution runtime', 'execution readiness'] },
  { routeId: 'failure-dependency-chains', capabilityId: 'FAILURE_VISIBILITY_ENGINE', phase: 13.4, domain: 'failure-visibility', foundationCategory: 'general', priority: 42, routingReason: 'Failure impact question — FAILURE_VISIBILITY_ENGINE shows impacted dependency chains from visible failures without auto-fix.', companionCapabilities: [], detectorKey: 'failureVisibilityDependencyChains', keywords: ['dependency chains are impacted'] },
  { routeId: 'dependency-blocked', capabilityId: 'DEPENDENCY_INTELLIGENCE', phase: 12.2, domain: 'dependency', foundationCategory: 'general', priority: 43, routingReason: 'Blocked capabilities question — DEPENDENCY_INTELLIGENCE owns dependency-graph blocked capability advisory.', companionCapabilities: [], detectorKey: 'dependencyIntelligenceBlockedCapabilities', keywords: ['capabilities are blocked'] },
  { routeId: 'learning-visibility', capabilityId: 'LEARNING_VISIBILITY_ENGINE', phase: 13.5, domain: 'learning-visibility', foundationCategory: 'general', priority: 44, routingReason: 'Learning question — LEARNING_VISIBILITY_ENGINE shows observed patterns, recurring blockers/failures/recommendations, and memory lessons without self-learning or model modification.', companionCapabilities: [], detectorKey: 'learningVisibilityEngine', keywords: ['learning visibility'] },
  { routeId: 'failure-visibility', capabilityId: 'FAILURE_VISIBILITY_ENGINE', phase: 13.4, domain: 'failure-visibility', foundationCategory: 'general', priority: 45, routingReason: 'Failure question — FAILURE_VISIBILITY_ENGINE shows failures, severity, impact, and advisory next steps without auto-fix or execution.', companionCapabilities: [], detectorKey: 'failureVisibilityEngine', keywords: ['failure visibility'] },
  { routeId: 'progress-intelligence', capabilityId: 'PROGRESS_INTELLIGENCE', phase: 13.3, domain: 'progress', foundationCategory: 'general', priority: 46, routingReason: 'Progress question — PROGRESS_INTELLIGENCE shows completion, milestones, blockers, and portfolio progress without execution.', companionCapabilities: [], detectorKey: 'progressIntelligence', keywords: ['progress intelligence'] },
  { routeId: 'reasoning-visibility', capabilityId: 'REASONING_VISIBILITY_ENGINE', phase: 13.2, domain: 'reasoning-visibility', foundationCategory: 'general', priority: 47, routingReason: 'Reasoning visibility question — REASONING_VISIBILITY_ENGINE explains evidence, sources, blockers, risks, and confidence basis without chain-of-thought.', companionCapabilities: [], detectorKey: 'reasoningVisibilityEngine', keywords: ['reasoning visibility'] },
  { routeId: 'action-visibility', capabilityId: 'ACTION_VISIBILITY_ENGINE', phase: 13.1, domain: 'action-visibility', foundationCategory: 'general', priority: 48, routingReason: 'Action visibility question — ACTION_VISIBILITY_ENGINE explains considered actions, status, priority, and source without execution.', companionCapabilities: [], detectorKey: 'actionVisibilityEngine', keywords: ['action visibility'] },
  { routeId: 'unified-decision', capabilityId: 'UNIFIED_DECISION_LAYER', phase: 11.5, domain: 'decision', foundationCategory: 'general', priority: 49, routingReason: 'Decision-oriented question — route through Unified Decision Layer for advisory build/defer/block/priority recommendations.', companionCapabilities: [], detectorKey: 'unifiedDecisionLayer', keywords: ['decision'] },
  { routeId: 'project-summarization', capabilityId: 'PROJECT_SUMMARIZATION_ENGINE', phase: 12.4, domain: 'summarization', foundationCategory: 'general', priority: 50, routingReason: 'Summarization-oriented question — PROJECT_SUMMARIZATION_ENGINE compresses all intelligence sources into unified summaries.', companionCapabilities: [], detectorKey: 'projectSummarizationEngine', keywords: ['summarization', 'summary'] },
  { routeId: 'project-history', capabilityId: 'PROJECT_HISTORY_INTELLIGENCE', phase: 12.3, domain: 'project-history', foundationCategory: 'general', priority: 51, routingReason: 'History-oriented question — PROJECT_HISTORY_INTELLIGENCE is answer authority; Timeline Intelligence owns current phase separately.', companionCapabilities: [], detectorKey: 'projectHistoryIntelligence', keywords: ['project history'] },
  { routeId: 'workspace-intelligence', capabilityId: 'WORKSPACE_INTELLIGENCE', phase: 12.1, domain: 'workspace', foundationCategory: 'general', priority: 52, routingReason: 'Workspace-oriented question — WORKSPACE_INTELLIGENCE is answer authority; Project Understanding supplements with enriched facts.', companionCapabilities: [], detectorKey: 'workspaceIntelligence', keywords: ['workspace intelligence'] },
  { routeId: 'dependency-intelligence', capabilityId: 'DEPENDENCY_INTELLIGENCE', phase: 12.2, domain: 'dependency', foundationCategory: 'general', priority: 53, routingReason: 'Dependency-oriented question — DEPENDENCY_INTELLIGENCE is answer authority; Unified Decision Layer supplements when decision signals also match.', companionCapabilities: [], detectorKey: 'dependencyIntelligence', keywords: ['dependency intelligence'] },
  { routeId: 'vault-aware', capabilityId: 'PROJECT_KNOWLEDGE_REASONING', phase: 12, domain: 'project-vault', foundationCategory: 'general', priority: 54, routingReason: 'Vault-aware project question — PROJECT_VAULT_INTELLIGENCE supplements Project Knowledge Reasoning; 11.4 remains answer authority.', companionCapabilities: [], detectorKey: 'vaultAware', keywords: ['vault', 'project vault'] },
  { routeId: 'timeline-intelligence', capabilityId: 'TIMELINE_INTELLIGENCE', phase: 11.3, domain: 'timeline', foundationCategory: 'general', priority: 55, routingReason: 'Timeline-oriented question — route through Timeline Intelligence for past/present/future understanding.', companionCapabilities: [], detectorKey: 'timelinePrimary', keywords: ['timeline'] },
] as const;

export const COMPANION_ROUTE_ENTRIES: readonly CompanionRouteEntry[] = [
  { detectorKey: 'vaultAware', companions: ['PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'PROJECT_UNDERSTANDING'] },
  { detectorKey: 'dependencyIntelligenceCompanion', companions: ['DEPENDENCY_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING'] },
  { detectorKey: 'workspaceIntelligenceCompanion', companions: ['WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'PROJECT_UNDERSTANDING'] },
  { detectorKey: 'projectHistoryIntelligenceCompanion', companions: ['PROJECT_HISTORY_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'PROJECT_UNDERSTANDING'] },
  { detectorKey: 'portfolioIntelligence', companions: ['PORTFOLIO_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'PROJECT_UNDERSTANDING', 'WORKSPACE_INTELLIGENCE'] },
  { detectorKey: 'actionVisibilityCompanion', companions: ['ACTION_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING'] },
  { detectorKey: 'reasoningVisibilityCompanion', companions: ['REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER', 'ACTION_VISIBILITY_ENGINE', 'PROJECT_KNOWLEDGE_REASONING'] },
  { detectorKey: 'cloudRuntimeFoundation', companions: ['CLOUD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'WORKSPACE_INTELLIGENCE', 'PROJECT_VAULT_INTELLIGENCE', 'EXECUTION_RUNTIME_FOUNDATION', 'WORLD2_EXECUTION_ACTIVATION', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'workspaceHostingFoundation', companions: ['WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'WORKSPACE_INTELLIGENCE', 'PROJECT_VAULT_INTELLIGENCE', 'UNIFIED_VERIFICATION_ENTRY', 'VERIFICATION_EVIDENCE_ENGINE', 'VERIFICATION_REPORTING_ENGINE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'persistentBuildRuntimeFoundation', companions: ['PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'WORKSPACE_INTELLIGENCE', 'PROJECT_VAULT_INTELLIGENCE', 'UNIFIED_VERIFICATION_ENTRY', 'VERIFICATION_EVIDENCE_ENGINE', 'VERIFICATION_REPORTING_ENGINE', 'EXECUTION_RUNTIME_FOUNDATION', 'BUILD_TASK_RUNTIME_FOUNDATION', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'mobileApprovalRuntimeFoundation', companions: ['MOBILE_APPROVAL_RUNTIME_FOUNDATION', 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', 'MOBILE_CHAT_RUNTIME_FOUNDATION', 'MOBILE_COMMAND_RUNTIME_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'autonomousBuilderFoundation', companions: ['AUTONOMOUS_BUILDER_FOUNDATION', 'MOBILE_PUSH_FOUNDATION', 'NOTIFICATION_DELIVERY_FOUNDATION', 'FOUNDER_INBOX_FOUNDATION', 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', 'CROSS_DEVICE_RUNTIME_FOUNDATION', 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', 'MOBILE_CHAT_RUNTIME_FOUNDATION', 'MOBILE_COMMAND_RUNTIME_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'mobilePushFoundation', companions: ['MOBILE_PUSH_FOUNDATION', 'NOTIFICATION_DELIVERY_FOUNDATION', 'FOUNDER_INBOX_FOUNDATION', 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', 'CROSS_DEVICE_RUNTIME_FOUNDATION', 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', 'MOBILE_CHAT_RUNTIME_FOUNDATION', 'MOBILE_COMMAND_RUNTIME_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'notificationDeliveryFoundation', companions: ['NOTIFICATION_DELIVERY_FOUNDATION', 'FOUNDER_INBOX_FOUNDATION', 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', 'CROSS_DEVICE_RUNTIME_FOUNDATION', 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', 'MOBILE_CHAT_RUNTIME_FOUNDATION', 'MOBILE_COMMAND_RUNTIME_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'founderInboxFoundation', companions: ['FOUNDER_INBOX_FOUNDATION', 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', 'CROSS_DEVICE_RUNTIME_FOUNDATION', 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', 'MOBILE_CHAT_RUNTIME_FOUNDATION', 'MOBILE_COMMAND_RUNTIME_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'founderNotificationRuntimeFoundation', companions: ['FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION', 'CROSS_DEVICE_RUNTIME_FOUNDATION', 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', 'MOBILE_CHAT_RUNTIME_FOUNDATION', 'MOBILE_COMMAND_RUNTIME_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'crossDeviceRuntimeFoundation', companions: ['CROSS_DEVICE_RUNTIME_FOUNDATION', 'MOBILE_APPROVAL_RUNTIME_FOUNDATION', 'MOBILE_PREVIEW_RUNTIME_FOUNDATION', 'MOBILE_CHAT_RUNTIME_FOUNDATION', 'MOBILE_COMMAND_RUNTIME_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'mobilePreviewRuntimeFoundation', companions: ['MOBILE_PREVIEW_RUNTIME_FOUNDATION', 'MOBILE_CHAT_RUNTIME_FOUNDATION', 'MOBILE_COMMAND_RUNTIME_FOUNDATION', 'LIVE_PREVIEW_RUNTIME', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'mobileChatRuntimeFoundation', companions: ['MOBILE_CHAT_RUNTIME_FOUNDATION', 'MOBILE_COMMAND_RUNTIME_FOUNDATION', 'CLOUD_MONITORING_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'mobileCommandRuntimeFoundation', companions: ['MOBILE_COMMAND_RUNTIME_FOUNDATION', 'CLOUD_MONITORING_FOUNDATION', 'CLOUD_RECOVERY_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'cloudMonitoringFoundation', companions: ['CLOUD_MONITORING_FOUNDATION', 'CLOUD_RECOVERY_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'cloudRecoveryFoundation', companions: ['CLOUD_RECOVERY_FOUNDATION', 'CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'cloudVerificationFoundation', companions: ['CLOUD_VERIFICATION_FOUNDATION', 'PERSISTENT_BUILD_RUNTIME_FOUNDATION', 'WORKSPACE_HOSTING_FOUNDATION', 'CLOUD_RUNTIME_FOUNDATION', 'UNIFIED_VERIFICATION_ENTRY', 'VERIFICATION_EVIDENCE_ENGINE', 'VERIFICATION_REPORTING_ENGINE', 'VERIFICATION_ORCHESTRATOR', 'VERIFICATION_REGISTRY', 'UNIFIED_VERIFICATION_LAB_RUNTIME', 'PROJECT_VAULT_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'unifiedVerificationEntry', companions: ['UNIFIED_VERIFICATION_ENTRY', 'VERIFICATION_REPORTING_ENGINE', 'VERIFICATION_EVIDENCE_ENGINE', 'VERIFICATION_ORCHESTRATOR', 'VERIFICATION_REGISTRY', 'UNIFIED_VERIFICATION_LAB_RUNTIME', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'verificationReportingEngine', companions: ['VERIFICATION_REPORTING_ENGINE', 'VERIFICATION_EVIDENCE_ENGINE', 'VERIFICATION_ORCHESTRATOR', 'VERIFICATION_REGISTRY', 'UNIFIED_VERIFICATION_LAB_RUNTIME', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'verificationEvidenceEngine', companions: ['VERIFICATION_EVIDENCE_ENGINE', 'VERIFICATION_ORCHESTRATOR', 'VERIFICATION_REGISTRY', 'UNIFIED_VERIFICATION_LAB_RUNTIME', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'verificationOrchestrator', companions: ['VERIFICATION_ORCHESTRATOR', 'VERIFICATION_REGISTRY', 'UNIFIED_VERIFICATION_LAB_RUNTIME', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'verificationRegistry', companions: ['VERIFICATION_REGISTRY', 'UNIFIED_VERIFICATION_LAB_RUNTIME', 'VISUAL_VERIFICATION_ENGINE', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'unifiedVerificationLabRuntime', companions: ['UNIFIED_VERIFICATION_LAB_RUNTIME', 'VISUAL_VERIFICATION_ENGINE', 'INTERACTION_TESTING_ENGINE', 'UI_INSPECTION_ENGINE', 'SELF_VISION_RUNTIME', 'LIVE_PREVIEW_RUNTIME', 'PREVIEW_INTELLIGENCE', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'visualVerificationEngine', companions: ['VISUAL_VERIFICATION_ENGINE', 'INTERACTION_TESTING_ENGINE', 'UI_INSPECTION_ENGINE', 'SELF_VISION_RUNTIME', 'LIVE_PREVIEW_RUNTIME', 'PREVIEW_INTELLIGENCE', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'RUNTIME_VERIFICATION_LAYER', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'interactionTestingEngine', companions: ['INTERACTION_TESTING_ENGINE', 'UI_INSPECTION_ENGINE', 'SELF_VISION_RUNTIME', 'LIVE_PREVIEW_RUNTIME', 'PREVIEW_INTELLIGENCE', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'RUNTIME_VERIFICATION_LAYER', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'uiInspectionEngine', companions: ['UI_INSPECTION_ENGINE', 'SELF_VISION_RUNTIME', 'LIVE_PREVIEW_RUNTIME', 'PREVIEW_INTELLIGENCE', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'RUNTIME_VERIFICATION_LAYER', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'selfVisionRuntime', companions: ['SELF_VISION_RUNTIME', 'LIVE_PREVIEW_RUNTIME', 'PREVIEW_INTELLIGENCE', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'RUNTIME_VERIFICATION_LAYER', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'previewIntelligence', companions: ['PREVIEW_INTELLIGENCE', 'LIVE_PREVIEW_RUNTIME', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'RUNTIME_VERIFICATION_LAYER', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'livePreviewRuntime', companions: ['LIVE_PREVIEW_RUNTIME', 'WORKSPACE_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING', 'RUNTIME_VERIFICATION_LAYER', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'world2CompletionRuntime', companions: ['WORLD2_COMPLETION_RUNTIME', 'WORLD2_RECOVERY_RUNTIME', 'WORLD2_ROLLBACK_RUNTIME', 'WORLD2_CONTROLLED_APPLY_RUNTIME', 'WORLD2_BUILDER_PACKET_EXECUTION', 'WORLD2_EXECUTION_ACTIVATION', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE'] },
  { detectorKey: 'world2RecoveryRuntime', companions: ['WORLD2_RECOVERY_RUNTIME', 'WORLD2_ROLLBACK_RUNTIME', 'WORLD2_CONTROLLED_APPLY_RUNTIME', 'WORLD2_BUILDER_PACKET_EXECUTION', 'WORLD2_EXECUTION_ACTIVATION', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE'] },
  { detectorKey: 'world2RollbackRuntime', companions: ['WORLD2_ROLLBACK_RUNTIME', 'WORLD2_CONTROLLED_APPLY_RUNTIME', 'WORLD2_BUILDER_PACKET_EXECUTION', 'WORLD2_EXECUTION_ACTIVATION', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'FAILURE_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE'] },
  { detectorKey: 'world2ControlledApplyRuntime', companions: ['WORLD2_CONTROLLED_APPLY_RUNTIME', 'WORLD2_BUILDER_PACKET_EXECUTION', 'WORLD2_EXECUTION_ACTIVATION', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'FAILURE_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE'] },
  { detectorKey: 'world2BuilderPacketExecution', companions: ['WORLD2_BUILDER_PACKET_EXECUTION', 'WORLD2_EXECUTION_ACTIVATION', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'BUILD_TASK_RUNTIME_FOUNDATION', 'CODE_GENERATION_RUNTIME_FOUNDATION', 'TESTING_RUNTIME_FOUNDATION', 'EXECUTION_RUNTIME_FOUNDATION', 'FAILURE_VISIBILITY_ENGINE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE'] },
  { detectorKey: 'world2ExecutionActivation', companions: ['WORLD2_EXECUTION_ACTIVATION', 'RUNTIME_VERIFICATION_LAYER', 'WORKSPACE_INTELLIGENCE', 'AUTO_FIX_RUNTIME_FOUNDATION', 'TESTING_RUNTIME_FOUNDATION', 'CODE_GENERATION_RUNTIME_FOUNDATION', 'BUILD_TASK_RUNTIME_FOUNDATION', 'EXECUTION_RUNTIME_FOUNDATION', 'FAILURE_VISIBILITY_ENGINE', 'LEARNING_VISIBILITY_ENGINE', 'DEPENDENCY_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE'] },
  { detectorKey: 'runtimeVerificationLayer', companions: ['RUNTIME_VERIFICATION_LAYER', 'AUTO_FIX_RUNTIME_FOUNDATION', 'TESTING_RUNTIME_FOUNDATION', 'CODE_GENERATION_RUNTIME_FOUNDATION', 'BUILD_TASK_RUNTIME_FOUNDATION', 'EXECUTION_RUNTIME_FOUNDATION', 'FAILURE_VISIBILITY_ENGINE', 'LEARNING_VISIBILITY_ENGINE', 'DEPENDENCY_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE'] },
  { detectorKey: 'autoFixRuntimeFoundation', companions: ['AUTO_FIX_RUNTIME_FOUNDATION', 'TESTING_RUNTIME_FOUNDATION', 'CODE_GENERATION_RUNTIME_FOUNDATION', 'BUILD_TASK_RUNTIME_FOUNDATION', 'EXECUTION_RUNTIME_FOUNDATION', 'FAILURE_VISIBILITY_ENGINE', 'LEARNING_VISIBILITY_ENGINE', 'DEPENDENCY_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE'] },
  { detectorKey: 'testingRuntimeFoundation', companions: ['TESTING_RUNTIME_FOUNDATION', 'CODE_GENERATION_RUNTIME_FOUNDATION', 'BUILD_TASK_RUNTIME_FOUNDATION', 'EXECUTION_RUNTIME_FOUNDATION', 'DEPENDENCY_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'FAILURE_VISIBILITY_ENGINE', 'LEARNING_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE'] },
  { detectorKey: 'codeGenerationRuntimeFoundation', companions: ['CODE_GENERATION_RUNTIME_FOUNDATION', 'BUILD_TASK_RUNTIME_FOUNDATION', 'EXECUTION_RUNTIME_FOUNDATION', 'DEPENDENCY_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'FAILURE_VISIBILITY_ENGINE', 'LEARNING_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE'] },
  { detectorKey: 'buildTaskRuntimeFoundation', companions: ['BUILD_TASK_RUNTIME_FOUNDATION', 'EXECUTION_RUNTIME_FOUNDATION', 'DEPENDENCY_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE', 'FAILURE_VISIBILITY_ENGINE', 'LEARNING_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE'] },
  { detectorKey: 'executionRuntimeFoundation', companions: ['EXECUTION_RUNTIME_FOUNDATION', 'DEPENDENCY_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'WORKSPACE_INTELLIGENCE', 'PROGRESS_INTELLIGENCE', 'FAILURE_VISIBILITY_ENGINE', 'LEARNING_VISIBILITY_ENGINE', 'ACTION_VISIBILITY_ENGINE', 'REASONING_VISIBILITY_ENGINE'] },
  { detectorKey: 'learningVisibilityEngine', companions: ['LEARNING_VISIBILITY_ENGINE', 'FAILURE_VISIBILITY_ENGINE', 'PROGRESS_INTELLIGENCE', 'REASONING_VISIBILITY_ENGINE', 'ACTION_VISIBILITY_ENGINE', 'PROJECT_HISTORY_INTELLIGENCE', 'UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'failureVisibilityEngine', companions: ['FAILURE_VISIBILITY_ENGINE', 'DEPENDENCY_INTELLIGENCE', 'PROGRESS_INTELLIGENCE', 'UNIFIED_DECISION_LAYER', 'PROJECT_KNOWLEDGE_REASONING'] },
  { detectorKey: 'progressIntelligence', companions: ['PROGRESS_INTELLIGENCE', 'PROJECT_HISTORY_INTELLIGENCE', 'PORTFOLIO_INTELLIGENCE', 'PROJECT_KNOWLEDGE_REASONING'] },
  { detectorKey: 'projectSummarizationEngine', companions: ['PROJECT_SUMMARIZATION_ENGINE', 'PROJECT_KNOWLEDGE_REASONING', 'PROJECT_UNDERSTANDING'] },
  { detectorKey: 'unifiedDecisionLayer', companions: ['UNIFIED_DECISION_LAYER'] },
  { detectorKey: 'timelineIntelligenceCompanion', companions: ['TIMELINE_INTELLIGENCE'] },
] as const;

export function getCapabilityRoutingTable(): {
  contextMap: typeof CONTEXT_CAPABILITY_MAP;
  primaryRoutes: readonly CapabilityRouteEntry[];
  companionRoutes: readonly CompanionRouteEntry[];
} {
  return {
    contextMap: CONTEXT_CAPABILITY_MAP,
    primaryRoutes: PRIMARY_ROUTE_ENTRIES,
    companionRoutes: COMPANION_ROUTE_ENTRIES,
  };
}

export function getCapabilityRouteById(routeId: string): CapabilityRouteEntry | undefined {
  return PRIMARY_ROUTE_ENTRIES.find((r) => r.routeId === routeId);
}

export function listCapabilityRoutesByDomain(domain: string): CapabilityRouteEntry[] {
  return PRIMARY_ROUTE_ENTRIES.filter((r) => r.domain === domain);
}

export function listCapabilityRoutesByPhase(phase: number): CapabilityRouteEntry[] {
  return PRIMARY_ROUTE_ENTRIES.filter((r) => r.phase === phase);
}

export function findCapabilityRoutesByKeyword(keyword: string): CapabilityRouteEntry[] {
  const lower = keyword.toLowerCase();
  return PRIMARY_ROUTE_ENTRIES.filter(
    (r) => r.keywords.some((k) => k.includes(lower)) || r.domain.includes(lower) || r.capabilityId.toLowerCase().includes(lower),
  );
}

export function getCapabilityRoutingTableStats(): {
  primaryRouteCount: number;
  companionRouteCount: number;
  contextMapEntryCount: number;
  foundationCategories: Record<FoundationCategory, number>;
} {
  const foundationCategories = {} as Record<FoundationCategory, number>;
  for (const route of PRIMARY_ROUTE_ENTRIES) {
    foundationCategories[route.foundationCategory] = (foundationCategories[route.foundationCategory] ?? 0) + 1;
  }
  return {
    primaryRouteCount: PRIMARY_ROUTE_ENTRIES.length,
    companionRouteCount: COMPANION_ROUTE_ENTRIES.length,
    contextMapEntryCount: Object.keys(CONTEXT_CAPABILITY_MAP).length,
    foundationCategories,
  };
}
