/**
 * General Question Understanding — types for Phase 11.4C routing.
 */

export const GENERAL_QUESTION_UNDERSTANDING_PASS_TOKEN =
  'DEVPULSE_V2_GENERAL_QUESTION_UNDERSTANDING_ROUTER_V1_PASS';
export const GENERAL_QUESTION_UNDERSTANDING_OWNER_MODULE =
  'devpulse_v2_general_question_understanding';

export type QuestionDimension =
  | 'PROJECT'
  | 'SYSTEM'
  | 'ROADMAP'
  | 'RISK'
  | 'DEPENDENCY'
  | 'IMPACT'
  | 'MEMORY'
  | 'ARCHITECTURE'
  | 'PLANNING'
  | 'DEVELOPMENT'
  | 'DEBUGGING'
  | 'EXECUTION'
  | 'UNKNOWN';

export type ContextNeed =
  | 'PROJECT_PROFILE'
  | 'PROJECT_FACTS'
  | 'SHARED_MEMORY'
  | 'CROSS_SYSTEM_RELATIONSHIPS'
  | 'ROADMAP_STATE'
  | 'OWNERSHIP_REGISTRY'
  | 'RISK_FACTS'
  | 'MISSING_CAPABILITIES'
  | 'BLOCKERS'
  | 'RUNTIME_STATUS'
  | 'DEVELOPMENT_KNOWLEDGE'
  | 'DEBUG_CONTEXT'
  | 'TIMELINE_STATE'
  | 'VAULT_FACTS'
  | 'DEPENDENCY_FACTS'
  | 'WORKSPACE_FACTS'
  | 'HISTORY_FACTS'
  | 'SUMMARIZATION_FACTS'
  | 'PORTFOLIO_FACTS'
  | 'ACTION_VISIBILITY_FACTS'
  | 'REASONING_VISIBILITY_FACTS'
  | 'PROGRESS_INTELLIGENCE_FACTS'
  | 'FAILURE_VISIBILITY_FACTS'
  | 'LEARNING_VISIBILITY_FACTS'
  | 'EXECUTION_RUNTIME_FACTS'
  | 'BUILD_TASK_RUNTIME_FACTS'
  | 'CODE_GENERATION_RUNTIME_FACTS'
  | 'TESTING_RUNTIME_FACTS'
  | 'AUTO_FIX_RUNTIME_FACTS'
  | 'RUNTIME_VERIFICATION_FACTS'
  | 'WORLD2_EXECUTION_ACTIVATION_FACTS'
  | 'WORLD2_BUILDER_PACKET_EXECUTION_FACTS'
  | 'WORLD2_CONTROLLED_APPLY_RUNTIME_FACTS'
  | 'WORLD2_ROLLBACK_RUNTIME_FACTS'
  | 'WORLD2_RECOVERY_RUNTIME_FACTS'
  | 'WORLD2_COMPLETION_RUNTIME_FACTS'
  | 'LIVE_PREVIEW_RUNTIME_FACTS'
  | 'PREVIEW_INTELLIGENCE_FACTS'
  | 'SELF_VISION_RUNTIME_FACTS'
  | 'UI_INSPECTION_ENGINE_FACTS'
  | 'INTERACTION_TESTING_ENGINE_FACTS'
  | 'VISUAL_VERIFICATION_ENGINE_FACTS'
  | 'UNIFIED_VERIFICATION_LAB_RUNTIME_FACTS'
  | 'VERIFICATION_REGISTRY_FACTS'
  | 'VERIFICATION_ORCHESTRATOR_FACTS'
  | 'VERIFICATION_EVIDENCE_ENGINE_FACTS'
  | 'VERIFICATION_REPORTING_ENGINE_FACTS'
  | 'UNIFIED_VERIFICATION_ENTRY_FACTS'
  | 'CLOUD_RUNTIME_FOUNDATION_FACTS'
  | 'WORKSPACE_HOSTING_FOUNDATION_FACTS'
  | 'PERSISTENT_BUILD_RUNTIME_FOUNDATION_FACTS'
  | 'CLOUD_VERIFICATION_FOUNDATION_FACTS'
  | 'CLOUD_RECOVERY_FOUNDATION_FACTS'
  | 'CLOUD_MONITORING_FOUNDATION_FACTS'
  | 'MOBILE_COMMAND_RUNTIME_FOUNDATION_FACTS'
  | 'MOBILE_CHAT_RUNTIME_FOUNDATION_FACTS'
  | 'MOBILE_PREVIEW_RUNTIME_FOUNDATION_FACTS'
  | 'MOBILE_APPROVAL_RUNTIME_FOUNDATION_FACTS';

export type ReasoningMode =
  | 'DESCRIPTIVE'
  | 'DIAGNOSTIC'
  | 'PLANNING'
  | 'RISK_ASSESSMENT'
  | 'DEPENDENCY_ANALYSIS'
  | 'IMPACT_ANALYSIS'
  | 'COMPARISON'
  | 'PRIORITIZATION'
  | 'EXPLANATION'
  | 'LIMITATION_DISCLOSURE';

export type SelectedCapability =
  | 'PROJECT_UNDERSTANDING'
  | 'PROJECT_KNOWLEDGE_REASONING'
  | 'SHARED_MEMORY_RECALL'
  | 'CROSS_SYSTEM_AWARENESS'
  | 'ROADMAP_AWARENESS'
  | 'SYSTEM_AWARENESS'
  | 'TRUST_CONTEXT'
  | 'GOVERNANCE_CONTEXT'
  | 'DEVELOPMENT_REASONING'
  | 'DEBUGGING_REASONING'
  | 'EXECUTION_REASONING'
  | 'TIMELINE_INTELLIGENCE'
  | 'UNIFIED_DECISION_LAYER'
  | 'PROJECT_VAULT_INTELLIGENCE'
  | 'DEPENDENCY_INTELLIGENCE'
  | 'WORKSPACE_INTELLIGENCE'
  | 'PROJECT_HISTORY_INTELLIGENCE'
  | 'PROJECT_SUMMARIZATION_ENGINE'
  | 'PORTFOLIO_INTELLIGENCE'
  | 'ACTION_VISIBILITY_ENGINE'
  | 'REASONING_VISIBILITY_ENGINE'
  | 'PROGRESS_INTELLIGENCE'
  | 'FAILURE_VISIBILITY_ENGINE'
  | 'LEARNING_VISIBILITY_ENGINE'
  | 'EXECUTION_RUNTIME_FOUNDATION'
  | 'BUILD_TASK_RUNTIME_FOUNDATION'
  | 'CODE_GENERATION_RUNTIME_FOUNDATION'
  | 'TESTING_RUNTIME_FOUNDATION'
  | 'AUTO_FIX_RUNTIME_FOUNDATION'
  | 'RUNTIME_VERIFICATION_LAYER'
  | 'WORLD2_EXECUTION_ACTIVATION'
  | 'WORLD2_BUILDER_PACKET_EXECUTION'
  | 'WORLD2_CONTROLLED_APPLY_RUNTIME'
  | 'WORLD2_ROLLBACK_RUNTIME'
  | 'WORLD2_RECOVERY_RUNTIME'
  | 'WORLD2_COMPLETION_RUNTIME'
  | 'LIVE_PREVIEW_RUNTIME'
  | 'PREVIEW_INTELLIGENCE'
  | 'SELF_VISION_RUNTIME'
  | 'UI_INSPECTION_ENGINE'
  | 'INTERACTION_TESTING_ENGINE'
  | 'VISUAL_VERIFICATION_ENGINE'
  | 'UNIFIED_VERIFICATION_LAB_RUNTIME'
  | 'VERIFICATION_REGISTRY'
  | 'VERIFICATION_ORCHESTRATOR'
  | 'VERIFICATION_EVIDENCE_ENGINE'
  | 'VERIFICATION_REPORTING_ENGINE'
  | 'UNIFIED_VERIFICATION_ENTRY'
  | 'CLOUD_RUNTIME_FOUNDATION'
  | 'WORKSPACE_HOSTING_FOUNDATION'
  | 'PERSISTENT_BUILD_RUNTIME_FOUNDATION'
  | 'CLOUD_VERIFICATION_FOUNDATION'
  | 'CLOUD_RECOVERY_FOUNDATION'
  | 'CLOUD_MONITORING_FOUNDATION'
  | 'MOBILE_COMMAND_RUNTIME_FOUNDATION'
  | 'MOBILE_CHAT_RUNTIME_FOUNDATION'
  | 'MOBILE_PREVIEW_RUNTIME_FOUNDATION'
  | 'MOBILE_APPROVAL_RUNTIME_FOUNDATION';

export interface QuestionRoutingPlan {
  question: string;
  dimensions: QuestionDimension[];
  contextNeeds: ContextNeed[];
  reasoningModes: ReasoningMode[];
  selectedCapabilities: SelectedCapability[];
  unavailableCapabilities: SelectedCapability[];
  primaryCapability: SelectedCapability | null;
  secondaryCapabilities: SelectedCapability[];
  confidence: 'HIGH' | 'MEDIUM' | 'LOW';
  routingReason: string;
  timestamp: number;
}

export interface GeneralQuestionRoutingDiagnostics {
  lastQuestionDimensions: string[];
  lastContextNeeds: string[];
  lastReasoningModes: string[];
  lastCapabilitiesSelected: string[];
  unavailableCapabilities: string[];
  routingConfidence: string;
  routingReason: string;
}

export interface GeneralRoutingExecutionResult {
  ownsResponse: boolean;
  responseText: string;
  usedCapabilities: SelectedCapability[];
  routingPlan: QuestionRoutingPlan;
}

export const GENERAL_QUESTION_FEED_STAGES = [
  'Understanding Question',
  'Detecting Context Needs',
  'Selecting Reasoning Mode',
  'Selecting Capabilities',
  'Gathering Relevant Facts',
  'Composing Answer',
] as const;

export const UNAVAILABLE_CAPABILITIES: SelectedCapability[] = [
  'DEVELOPMENT_REASONING',
  'DEBUGGING_REASONING',
  'EXECUTION_REASONING',
];

export const PROJECT_SEMANTIC_SIGNALS = [
  'devpulse',
  'this project',
  'weakness',
  'weak at',
  'strong at',
  'holding back',
  'furthest behind',
  'focus before',
  'execution not connected',
  'missing capability',
  'most important',
  'six months',
  'autonomous building',
  'fail as a product',
  'riskiest',
  'not be built yet',
  'maturity',
  'readiness',
  'blocker',
  'cloud runtime',
  'foundation is most important',
] as const;
