/**
 * DevPulse V2 Phase 16.7 — Unified Verification Lab public API.
 */

export {
  UNIFIED_VERIFICATION_LAB_RUNTIME_PASS_TOKEN,
  UNIFIED_VERIFICATION_LAB_RUNTIME_OWNER_MODULE,
  UVL_RUNTIME_QUESTION_SIGNALS,
  FORBIDDEN_UVL_RUNTIME_DUPLICATES,
  INITIAL_VERIFICATION_PROVIDER_TYPES,
  ALL_VERIFICATION_SESSION_STATES,
  isUvlRuntimeQuestion,
  isUvlRuntimeAdvisoryQuestion,
  isDuplicateUvlRuntimeQuestion,
  type VerificationProviderType,
  type VerificationProviderStatus,
  type VerificationSessionState,
  type VerificationRuntimeState,
  type VerificationProvider,
  type VerificationSession,
  type VerificationRuntimeReport,
  type VerificationRuntimeDiagnostics,
  type PrepareVerificationRuntimeInput,
  type PrepareVerificationRuntimeResult,
} from './types.js';

export {
  parseVerificationRuntimeQuery,
  resetVerificationRuntimeRequestCounterForTests,
  type ParsedVerificationRuntimeQuery,
} from './verification-request-parser.js';

export {
  registerProvider,
  registerInitialProviders,
  getVerificationProvider,
  getVerificationProviderByType,
  listVerificationProviders,
  buildInitialProviderDefinition,
  resetVerificationProviderRegistryForTests,
  type RegisterProviderResult,
} from './verification-provider-registry.js';

export {
  createVerificationSession,
  getVerificationSession,
  listVerificationSessions,
  updateVerificationSession,
  setVerificationSessionState,
  resetVerificationSessionManagerForTests,
  type CreateSessionResult,
} from './verification-session-manager.js';

export {
  startVerificationSession,
  completeVerificationSession,
  failVerificationSession,
  markSessionReady,
  registerProviderDefinition,
  bootstrapVerificationSessions,
  advanceSessionLifecycle,
} from './verification-lifecycle-manager.js';

export {
  evaluateVerificationRuntimeGates,
  validateVerificationRuntime,
  validateProviderRegistration,
  validateSessionUniqueness,
  type VerificationRuntimeGateReport,
  type VerificationRuntimeValidationResult,
} from './verification-runtime-validator.js';

export {
  buildVerificationRuntimeReport,
  composeVerificationRuntimeResponse,
  buildVerificationRuntimeFailureContext,
  deriveRuntimeState,
  nextVerificationRuntimeReportId,
  resetVerificationRuntimeReportCounterForTests,
  type VerificationRuntimeFailureContext,
} from './verification-runtime-report.js';

export {
  getVerificationRuntimeDiagnostics,
  updateVerificationRuntimeDiagnostics,
  resetVerificationRuntimeDiagnostics,
  uvlRuntimeKey,
} from './verification-runtime-diagnostics.js';

export {
  prepareVerificationRuntime,
  processVerificationRuntimeRequest,
  getVerificationRuntimeContext,
} from './unified-verification-lab-runtime.js';

export {
  buildUvlPanelSnapshot,
  buildVerificationRegistryPanelSnapshot,
  buildVerificationOrchestratorPanelSnapshot,
  buildVerificationEvidencePanelSnapshot,
  buildVerificationReportingPanelSnapshot,
  buildUnifiedVerificationEntryPanelSnapshot,
  buildCloudRuntimeFoundationPanelSnapshot,
  buildWorkspaceHostingFoundationPanelSnapshot,
  buildPersistentBuildRuntimeFoundationPanelSnapshot,
  buildCloudVerificationFoundationPanelSnapshot,
  buildCloudRecoveryFoundationPanelSnapshot,
  buildCloudMonitoringFoundationPanelSnapshot,
  buildMobileCommandRuntimeFoundationPanelSnapshot,
  buildMobileChatRuntimeFoundationPanelSnapshot,
  buildMobilePreviewRuntimeFoundationPanelSnapshot,
  buildMobileApprovalRuntimeFoundationPanelSnapshot,
  buildCrossDeviceRuntimeFoundationPanelSnapshot,
  buildFounderNotificationRuntimeFoundationPanelSnapshot,
  buildFounderInboxFoundationPanelSnapshot,
  buildNotificationDeliveryFoundationPanelSnapshot,
  buildMobilePushFoundationPanelSnapshot,
  buildAutonomousBuilderFoundationPanelSnapshot,
  type UvlPanelSnapshot,
  type VerificationRegistryPanelSnapshot,
  type VerificationOrchestratorPanelSnapshot,
  type VerificationEvidencePanelSnapshot,
  type VerificationReportingPanelSnapshot,
  type UnifiedVerificationEntryPanelSnapshot,
  type CloudRuntimeFoundationPanelSnapshot,
  type WorkspaceHostingFoundationPanelSnapshot,
  type PersistentBuildRuntimeFoundationPanelSnapshot,
  type CloudVerificationFoundationPanelSnapshot,
  type CloudRecoveryFoundationPanelSnapshot,
  type CloudMonitoringFoundationPanelSnapshot,
  type MobileCommandRuntimeFoundationPanelSnapshot,
  type MobileChatRuntimeFoundationPanelSnapshot,
  type MobilePreviewRuntimeFoundationPanelSnapshot,
  type MobileApprovalRuntimeFoundationPanelSnapshot,
  type CrossDeviceRuntimeFoundationPanelSnapshot,
  type FounderNotificationRuntimeFoundationPanelSnapshot,
  type AutonomousBuilderFoundationPanelSnapshot,
} from './uvl-panel-registry.js';

export function getDevPulseV2UnifiedVerificationLabRuntime(): {
  ownerModule: string;
  passToken: string;
  phase: number;
  extensionOnly: true;
} {
  return {
    ownerModule: 'devpulse_v2_unified_verification_lab_runtime',
    passToken: 'UNIFIED_VERIFICATION_LAB_RUNTIME_V1_PASS',
    phase: 16.7,
    extensionOnly: true,
  };
}

export {
  WORLD2_BUILDER_PACKET_EXECUTION_UVL_ROWS,
  WORLD2_CONTROLLED_APPLY_RUNTIME_UVL_ROWS,
  WORLD2_ROLLBACK_RUNTIME_UVL_ROWS,
  WORLD2_RECOVERY_RUNTIME_UVL_ROWS,
  WORLD2_COMPLETION_RUNTIME_UVL_ROWS,
  LIVE_PREVIEW_RUNTIME_UVL_ROWS,
  PREVIEW_INTELLIGENCE_UVL_ROWS,
  SELF_VISION_RUNTIME_UVL_ROWS,
  UI_INSPECTION_ENGINE_UVL_ROWS,
  INTERACTION_TESTING_ENGINE_UVL_ROWS,
  VISUAL_VERIFICATION_ENGINE_UVL_ROWS,
  UNIFIED_VERIFICATION_LAB_RUNTIME_UVL_ROWS,
  VERIFICATION_REGISTRY_UVL_ROWS,
  VERIFICATION_ORCHESTRATOR_UVL_ROWS,
  VERIFICATION_EVIDENCE_ENGINE_UVL_ROWS,
  VERIFICATION_REPORTING_ENGINE_UVL_ROWS,
  UNIFIED_VERIFICATION_ENTRY_UVL_ROWS,
  CLOUD_RUNTIME_FOUNDATION_UVL_ROWS,
  WORKSPACE_HOSTING_FOUNDATION_UVL_ROWS,
  PERSISTENT_BUILD_RUNTIME_FOUNDATION_UVL_ROWS,
  CLOUD_VERIFICATION_FOUNDATION_UVL_ROWS,
  CLOUD_RECOVERY_FOUNDATION_UVL_ROWS,
  CLOUD_MONITORING_FOUNDATION_UVL_ROWS,
  MOBILE_COMMAND_RUNTIME_FOUNDATION_UVL_ROWS,
  MOBILE_CHAT_RUNTIME_FOUNDATION_UVL_ROWS,
  MOBILE_PREVIEW_RUNTIME_FOUNDATION_UVL_ROWS,
  MOBILE_APPROVAL_RUNTIME_FOUNDATION_UVL_ROWS,
  CROSS_DEVICE_RUNTIME_FOUNDATION_UVL_ROWS,
  ALL_UVL_ROWS,
  listWorld2BuilderPacketExecutionUvlRows,
  listWorld2ControlledApplyRuntimeUvlRows,
  listWorld2RollbackRuntimeUvlRows,
  listWorld2RecoveryRuntimeUvlRows,
  listWorld2CompletionRuntimeUvlRows,
  listLivePreviewRuntimeUvlRows,
  listPreviewIntelligenceUvlRows,
  listSelfVisionRuntimeUvlRows,
  listUiInspectionEngineUvlRows,
  listInteractionTestingEngineUvlRows,
  listVisualVerificationEngineUvlRows,
  listUnifiedVerificationLabRuntimeUvlRows,
  listVerificationRegistryUvlRows,
  listVerificationOrchestratorUvlRows,
  listVerificationEvidenceEngineUvlRows,
  listVerificationReportingEngineUvlRows,
  listUnifiedVerificationEntryUvlRows,
  listCloudRuntimeFoundationUvlRows,
  listWorkspaceHostingFoundationUvlRows,
  listPersistentBuildRuntimeFoundationUvlRows,
  listCloudVerificationFoundationUvlRows,
  listCloudRecoveryFoundationUvlRows,
  listCloudMonitoringFoundationUvlRows,
  listMobileCommandRuntimeFoundationUvlRows,
  listMobileChatRuntimeFoundationUvlRows,
  listMobilePreviewRuntimeFoundationUvlRows,
  listMobileApprovalRuntimeFoundationUvlRows,
  listCrossDeviceRuntimeFoundationUvlRows,
  FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION_UVL_ROWS,
  listFounderNotificationRuntimeFoundationUvlRows,
  FOUNDER_INBOX_FOUNDATION_UVL_ROWS,
  listFounderInboxFoundationUvlRows,
  NOTIFICATION_DELIVERY_FOUNDATION_UVL_ROWS,
  listNotificationDeliveryFoundationUvlRows,
  MOBILE_PUSH_FOUNDATION_UVL_ROWS,
  listMobilePushFoundationUvlRows,
  AUTONOMOUS_BUILDER_FOUNDATION_UVL_ROWS,
  listAutonomousBuilderFoundationUvlRows,
  BUILD_STRATEGY_ENGINE_UVL_ROWS,
  listBuildStrategyEngineUvlRows,
  VERIFICATION_STRATEGY_CORE_UVL_ROWS,
  listVerificationStrategyCoreUvlRows,
  VERIFICATION_INTELLIGENCE_UVL_ROWS,
  listVerificationIntelligenceUvlRows,
  VERIFICATION_INTEGRATION_UVL_ROWS,
  listVerificationIntegrationUvlRows,
  AUTONOMOUS_TESTING_UVL_ROWS,
  listAutonomousTestingUvlRows,
  AUTONOMOUS_FIXING_UVL_ROWS,
  listAutonomousFixingUvlRows,
  AUTONOMOUS_VERIFICATION_UVL_ROWS,
  listAutonomousVerificationUvlRows,
  AUTONOMOUS_COMPLETION_ENGINE_UVL_ROWS,
  listAutonomousCompletionEngineUvlRows,
  MULTI_PROJECT_FOUNDATION_UVL_ROWS,
  listMultiProjectFoundationUvlRows,
  WORKSPACE_ISOLATION_EXPANSION_UVL_ROWS,
  listWorkspaceIsolationExpansionUvlRows,
  RESOURCE_ALLOCATION_UVL_ROWS,
  listResourceAllocationUvlRows,
  PARALLEL_BUILD_ORCHESTRATION_UVL_ROWS,
  listParallelBuildOrchestrationUvlRows,
  MULTI_PROJECT_VERIFICATION_UVL_ROWS,
  listMultiProjectVerificationUvlRows,
  MULTI_PROJECT_VERIFICATION_ORCHESTRATION_UVL_ROWS,
  listMultiProjectVerificationOrchestrationUvlRows,
  MULTI_PROJECT_MONITORING_UVL_ROWS,
  listMultiProjectMonitoringUvlRows,
  MISSING_CAPABILITY_ESCALATION_UVL_ROWS,
  listMissingCapabilityEscalationUvlRows,
  CAPABILITY_RESEARCH_ENGINE_UVL_ROWS,
  listCapabilityResearchEngineUvlRows,
  CAPABILITY_PLANNING_ENGINE_UVL_ROWS,
  listCapabilityPlanningEngineUvlRows,
  CAPABILITY_BUILD_ENGINE_UVL_ROWS,
  listCapabilityBuildEngineUvlRows,
  CAPABILITY_VERIFICATION_ENGINE_UVL_ROWS,
  listCapabilityVerificationEngineUvlRows,
  SELF_EVOLUTION_GOVERNANCE_UVL_ROWS,
  listSelfEvolutionGovernanceUvlRows,
  UNIFIED_TRUST_RUNTIME_UVL_ROWS,
  listUnifiedTrustRuntimeUvlRows,
  hasUvlRow,
  type UvlRow,
} from './uvl-row-registry.js';

export {
  hasCachedUvlRow,
  getCachedUvlRow,
  getCachedUvlRowsByPhase,
  getCachedUvlPanel,
  getUvlLookupCacheStats,
  clearUvlLookupCache,
  MAX_UVL_CACHE_SIZE,
} from './uvl-lookup-cache.js';
