/** Phase 25.37 — Chat Cognitive Architecture constants. */

export const CHAT_COGNITIVE_ARCHITECTURE_PASS_TOKEN =
  'CHAT_COGNITIVE_ARCHITECTURE_SELF_DIAGNOSIS_PASS';

export const CHAT_COGNITIVE_QUALITY_PASS_THRESHOLD = 70;

export const CHAT_COGNITIVE_LAUNCH_RELIABILITY_THRESHOLD = 70;

export const CHAT_COGNITIVE_SELF_EVOLUTION_FAILURE_THRESHOLD = 3;

export const GENERIC_ONBOARDING_SIGNATURE =
  'AiDevEngine helps turn software ideas into working applications';

export const INTENTS_REQUIRING_DIRECT_ANSWER = [
  'SELF_AWARENESS',
  'IDENTITY',
  'CREATOR_OR_ORIGIN',
  'TRUST',
  'LIMITATION',
  'CAPABILITY',
  'PROJECT_STATUS',
  'NEXT_ACTION',
  'VERIFICATION',
  'LAUNCH_READINESS',
  'SELF_IMPROVEMENT',
  'HUMAN_QUALITY',
] as const;
