export const AIDEVENGINE_BUILD_PROOF_V1_2_PASS_TOKEN = 'AIDEVENGINE_BUILD_PROOF_V1_2_PASS';
export const AIDEVENGINE_BUILD_PROOF_V1_2_ARTIFACT_DIR = '.aidevengine-build-proof-v1-2';
export const AIDEVENGINE_BUILD_PROOF_V1_2_REPORT_TITLE = 'AIDEVENGINE_BUILD_PROOF_V1_2_REPORT.md';
