/**
 * UVL Verification Execution V1 — bounds and pass token.
 */

export const UVL_VERIFICATION_EXECUTION_V1_PASS_TOKEN = 'UVL_VERIFICATION_EXECUTION_V1_PASS';

export const UVL_VERIFICATION_EXECUTION_V1_REPORT_TITLE = 'UVL_VERIFICATION_EXECUTION_V1_REPORT.md';

export const UVL_VERIFICATION_EXECUTION_V1_ARTIFACT_DIR = '.uvl-verification-execution-v1';

export const MIN_VERIFIED_CATEGORIES = 15;

export const MIN_VERIFICATION_COVERAGE_PERCENT = 100;

export const MIN_VERIFICATION_CONFIDENCE_SCORE = 75;

export const MAX_UVL_VERIFICATION_EXECUTION_HISTORY = 20;

export const VERIFICATION_PROBE_TIMEOUT_MS = 8_000;

export const DIST_PREVIEW_SERVER_TIMEOUT_MS = 12_000;
