/**
 * General-Purpose Code Generation V1 — bounds and pass token.
 */

export const GENERAL_PURPOSE_CODE_GENERATION_V1_PASS_TOKEN =
  'GENERAL_PURPOSE_CODE_GENERATION_V1_PASS';
export const GENERAL_PURPOSE_CODE_GENERATION_V1_FAIL_TOKEN =
  'GENERAL_PURPOSE_CODE_GENERATION_V1_FAIL';
export const GENERAL_PURPOSE_CODE_GENERATION_V1_REPORT_TITLE =
  'GENERAL_PURPOSE_CODE_GENERATION_V1_REPORT.md';
export const GENERAL_PURPOSE_CODE_GENERATION_V1_ARTIFACT_DIR =
  '.general-purpose-code-generation-v1';
export const GENERAL_PURPOSE_WORKSPACE_PREFIX = 'gpcg';
export const MIN_GENERAL_PURPOSE_PROOF_DOMAINS = 10;
export const MIN_GENERAL_PURPOSE_MATURITY_SCORE = 80;
export const MAX_GENERAL_PURPOSE_HISTORY = 20;

export const PRIOR_PASS_TOKENS = [
  'CLOUD_EXECUTION_PATH_V1_PASS',
  'PRODUCTION_READINESS_GATE_V1_PASS',
  'UVL_VERIFICATION_EXECUTION_V1_PASS',
  'REAL_BUILD_EXECUTION_PIPELINE_V1_1_PASS',
  'VALIDATION_RUNTIME_GOVERNANCE_V1_PASS',
  'AIDEVENGINE_CAPABILITY_AUDIT_V3_1_PASS',
] as const;
