/**
 * Product Evolution Reality Authority — markdown report builder.
 */

import {
  PRODUCT_EVOLUTION_REALITY_AUTHORITY_PASS_TOKEN,
  PRODUCT_EVOLUTION_REALITY_AUTHORITY_PHASE,
  PRODUCT_EVOLUTION_REALITY_AUTHORITY_REPORT_TITLE,
  PRODUCT_EVOLUTION_REALITY_CORE_QUESTION,
  SAFETY_GUARANTEES,
} from './product-evolution-reality-registry.js';
import type { ProductEvolutionRealityReport } from './product-evolution-reality-types.js';

export function buildProductEvolutionRealityReportMarkdown(
  report: ProductEvolutionRealityReport,
): string {
  const lines: string[] = [
    `# ${PRODUCT_EVOLUTION_REALITY_AUTHORITY_REPORT_TITLE}`,
    '',
    `Generated: ${report.generatedAt}`,
    '',
    '## Phase',
    '',
    PRODUCT_EVOLUTION_REALITY_AUTHORITY_PHASE,
    '',
    '## Core Question',
    '',
    PRODUCT_EVOLUTION_REALITY_CORE_QUESTION,
    '',
    '# Product Evolution Reality Authority',
    '',
    '## Evolution State',
    '',
    `**${report.productEvolutionState}**`,
    '',
    '## Overall Evolution Score',
    '',
    `${report.overallEvolutionScore}/100 (confidence: ${report.confidence}/100)`,
    '',
    '## Feedback Learning Analysis',
    '',
    `- user feedback processed: ${report.feedbackLearning.userFeedbackProcessed ? 'YES' : 'NO'}`,
    `- feature request response: ${report.feedbackLearning.featureRequestResponse ? 'YES' : 'NO'}`,
    `- support signal response: ${report.feedbackLearning.supportSignalResponse ? 'YES' : 'NO'}`,
    `- customer pain resolution: ${report.feedbackLearning.customerPainResolution ? 'YES' : 'NO'}`,
    `- feedback learning score: ${report.feedbackLearningScore}/100`,
    '',
    '## Failure Learning Analysis',
    '',
    `- bug fix learning: ${report.failureLearning.bugFixLearning ? 'YES' : 'NO'}`,
    `- incident learning: ${report.failureLearning.incidentLearning ? 'YES' : 'NO'}`,
    `- root cause learning: ${report.failureLearning.rootCauseLearning ? 'YES' : 'NO'}`,
    `- repeated failure reduction: ${report.failureLearning.repeatedFailureReduction ? 'YES' : 'NO'}`,
    `- failure learning score: ${report.failureLearningScore}/100`,
    '',
    '## Usage Learning Analysis',
    '',
    `- behavior-informed changes: ${report.usageLearning.behaviorInformedChanges ? 'YES' : 'NO'}`,
    `- usage-driven improvements: ${report.usageLearning.usageDrivenImprovements ? 'YES' : 'NO'}`,
    `- retention improvements: ${report.usageLearning.retentionImprovements ? 'YES' : 'NO'}`,
    `- engagement improvements: ${report.usageLearning.engagementImprovements ? 'YES' : 'NO'}`,
    `- usage learning score: ${report.usageLearningScore}/100`,
    '',
    '## Revenue Learning Analysis',
    '',
    `- revenue-informed decisions: ${report.revenueLearning.revenueInformedDecisions ? 'YES' : 'NO'}`,
    `- customer value improvements: ${report.revenueLearning.customerValueImprovements ? 'YES' : 'NO'}`,
    `- business model adjustments: ${report.revenueLearning.businessModelAdjustments ? 'YES' : 'NO'}`,
    `- monetization learning: ${report.revenueLearning.monetizationLearning ? 'YES' : 'NO'}`,
    `- revenue learning score: ${report.revenueLearningScore}/100`,
    '',
    '## Improvement Velocity Analysis',
    '',
    `- improvement frequency: ${report.improvementVelocity.improvementFrequency ? 'YES' : 'NO'}`,
    `- evidence-to-action speed: ${report.improvementVelocity.evidenceToActionSpeed ? 'YES' : 'NO'}`,
    `- issue resolution speed: ${report.improvementVelocity.issueResolutionSpeed ? 'YES' : 'NO'}`,
    `- adaptation responsiveness: ${report.improvementVelocity.adaptationResponsiveness ? 'YES' : 'NO'}`,
    `- improvements in last period: ${report.improvementVelocity.improvementsInLastPeriod ?? 'UNKNOWN'}`,
    `- improvement velocity score: ${report.improvementVelocityScore}/100`,
    '',
    '## Evolution Risk Analysis',
    '',
    `- evolution risk score: ${report.evolutionRiskScore}/100`,
    `- stagnation risk: ${report.evolutionRisk.stagnationRisk ? 'YES' : 'NO'}`,
    `- feedback ignoring risk: ${report.evolutionRisk.feedbackIgnoringRisk ? 'YES' : 'NO'}`,
    `- adaptation risk: ${report.evolutionRisk.adaptationRisk ? 'YES' : 'NO'}`,
    `- competitive drift risk: ${report.evolutionRisk.competitiveDriftRisk ? 'YES' : 'NO'}`,
    '',
    '## Observed Evolution Signals',
    '',
    `- feedback learning observed: ${report.feedbackLearningObserved ? 'YES' : 'NO'}`,
    `- failure learning observed: ${report.failureLearningObserved ? 'YES' : 'NO'}`,
    `- usage learning observed: ${report.usageLearningObserved ? 'YES' : 'NO'}`,
    `- revenue learning observed: ${report.revenueLearningObserved ? 'YES' : 'NO'}`,
    '',
    ...report.keyFindings.map((f) => `- ${f}`),
    '',
    '## Missing Evidence',
    '',
    ...report.missingEvidence.map((m) => `- ${m}`),
    ...(report.missingEvidence.length === 0 ? ['- none reported'] : []),
    '',
    '## Risk Signals',
    '',
    ...report.riskSignals.map((r) => `- ${r}`),
    ...(report.riskSignals.length === 0 ? ['- none identified'] : []),
    '',
    '## Recommended Actions',
    '',
    ...report.recommendedActions.map((a) => `- ${a}`),
    ...(report.recommendedActions.length === 0 ? ['- none'] : []),
    '',
    '## Final Verdict',
    '',
    report.finalVerdict,
    '',
    '## Safety',
    '',
    ...SAFETY_GUARANTEES.map((g) => `- ${g}`),
    '',
    '## Pass Token',
    '',
    PRODUCT_EVOLUTION_REALITY_AUTHORITY_PASS_TOKEN,
  ];

  return lines.join('\n');
}

export function formatProductEvolutionRealitySummary(report: ProductEvolutionRealityReport): string {
  return (
    `Product Evolution: ${report.productEvolutionState} — ` +
    `score ${report.overallEvolutionScore}/100, feedbackLearning=${report.feedbackLearningObserved}.`
  );
}
