/**
 * Real Production Generation Capability Audit V1 — production call graph (read-only).
 */

import type { ProductionCallGraphNode } from './real-production-generation-capability-types.js';

/** Deterministic production path call graph derived from the real orchestrator wiring. */
export function buildProductionGenerationCallGraph(): ProductionCallGraphNode[] {
  return [
    {
      stage: 'PROMPT',
      modulePath: 'src/one-prompt-live-preview/one-prompt-build-orchestrator.ts',
      functionName: 'runOnePromptLivePreviewBuild',
      consumesEnvelope: false,
      producesArtifacts: ['rawPrompt', 'buildDecision'],
      downstream: ['CANONICAL_CONTRACT'],
    },
    {
      stage: 'CANONICAL_CONTRACT',
      modulePath: 'src/product-faithfulness-v2/index.ts',
      functionName: 'buildCanonicalProductContract',
      consumesEnvelope: false,
      producesArtifacts: ['CanonicalProductContract'],
      downstream: ['CBGA'],
    },
    {
      stage: 'CBGA',
      modulePath: 'src/contract-bound-generation-authority-v4/contract-bound-generation-authority.ts',
      functionName: 'applyContractBoundGenerationToBuildPlan',
      consumesEnvelope: false,
      producesArtifacts: ['CbgaGenerationReport', 'ApprovedProductionBuildEnvelope', 'repaired buildPlan'],
      downstream: ['GPCA_PRE', 'BUILD_ENVELOPE'],
    },
    {
      stage: 'BUILD_ENVELOPE',
      modulePath: 'src/contract-bound-generation-authority-v4/approved-production-build-envelope.ts',
      functionName: 'buildApprovedProductionBuildEnvelope',
      consumesEnvelope: false,
      producesArtifacts: ['ApprovedProductionBuildEnvelope'],
      downstream: ['GPCA_PRE', 'MATERIALIZATION'],
    },
    {
      stage: 'GPCA_PRE',
      modulePath: 'src/generation-pipeline-compliance-authority-v1/index.ts',
      functionName: 'buildGpcaPreMaterializationReport',
      consumesEnvelope: true,
      producesArtifacts: ['GpcaComplianceReport (pre)'],
      downstream: ['MATERIALIZATION'],
    },
    {
      stage: 'PLANNING',
      modulePath: 'src/prompt-faithful-generation/index.ts',
      functionName: 'resolvePromptFaithfulBuildPlan',
      consumesEnvelope: false,
      producesArtifacts: ['ResolvedPromptFaithfulBuildPlan', 'ProfileFeatureDefinition'],
      downstream: ['PROMPT_BOUNDED_GUARD'],
    },
    {
      stage: 'PROMPT_BOUNDED_GUARD',
      modulePath: 'src/prompt-bounded-materialization/prompt-bounded-materialization-authority.ts',
      functionName: 'guardPromptBoundedMaterialization',
      consumesEnvelope: false,
      producesArtifacts: ['approvedModuleIds', 'blockedModules'],
      downstream: ['MATERIALIZATION'],
    },
    {
      stage: 'MATERIALIZATION',
      modulePath: 'src/code-generation-engine/code-generation-engine-authority.ts',
      functionName: 'materializeGeneratedApplication',
      consumesEnvelope: true,
      producesArtifacts: ['workspace files', 'registry.ts', 'routes.ts', 'FeatureAppRouter.tsx'],
      downstream: ['GPCA_POST', 'BLUEPRINT'],
    },
    {
      stage: 'BLUEPRINT',
      modulePath: 'src/universal-app-blueprint/universal-app-blueprint-authority.ts',
      functionName: 'composeGeneratedAppWorkspaceFiles',
      consumesEnvelope: true,
      producesArtifacts: ['AppShell.tsx', 'blueprint pages', 'product-surface.ts'],
      downstream: ['GPCA_POST'],
    },
    {
      stage: 'GPCA_POST',
      modulePath: 'src/generation-pipeline-compliance-authority-v1/index.ts',
      functionName: 'buildGpcaPostMaterializationReport',
      consumesEnvelope: true,
      producesArtifacts: ['GpcaComplianceReport (post)', 'rendered content audit'],
      downstream: ['WORKSPACE_STABILIZER', 'NPM_INSTALL'],
    },
    {
      stage: 'FEATURE_CONTRACT_REALITY',
      modulePath: 'src/feature-contract-reality/feature-reality-mapper.ts',
      functionName: 'buildFeatureRealityRecords',
      consumesEnvelope: false,
      producesArtifacts: ['FeatureRealityRecord[]', '.feature-contract-reality.json'],
      downstream: ['ENGINEERING_REPORT'],
    },
    {
      stage: 'NPM_BUILD',
      modulePath: 'src/one-prompt-live-preview/one-prompt-build-orchestrator.ts',
      functionName: 'runNpmBuildAttempt / runAeeBuildAutofixLoop',
      consumesEnvelope: false,
      producesArtifacts: ['compiled dist', 'build autofix patches'],
      downstream: ['PREVIEW'],
    },
    {
      stage: 'PREVIEW',
      modulePath: 'src/one-prompt-live-preview/one-prompt-build-orchestrator.ts',
      functionName: 'startGeneratedAppDevServer',
      consumesEnvelope: true,
      producesArtifacts: ['previewUrl', 'dev server'],
      downstream: ['LIVE_PREVIEW_GATE', 'INTERACTION_PROOF_ASE'],
    },
    {
      stage: 'LIVE_PREVIEW_GATE',
      modulePath: 'src/live-preview-gate/live-preview-orchestrator-bridge.ts',
      functionName: 'evaluateLivePreviewGateForOrchestrator',
      consumesEnvelope: false,
      producesArtifacts: ['LivePreviewGateResult'],
      downstream: ['INTERACTION_PROOF_ASE'],
    },
    {
      stage: 'INTERACTION_PROOF_ASE',
      modulePath: 'src/interaction-proof-engine/index.ts',
      functionName: 'assessInteractionProofReadiness',
      consumesEnvelope: false,
      producesArtifacts: ['InteractionProofPipelineResult (structural/synthetic)'],
      downstream: ['ENGINEERING_REPORT'],
    },
    {
      stage: 'INTERACTION_PROOF_PLAYWRIGHT',
      modulePath: 'src/live-preview-interaction-proof-v1/index.ts',
      functionName: 'runLivePreviewInteractionProof',
      consumesEnvelope: false,
      producesArtifacts: ['LivePreviewInteractionProofReport (behavioral when run)'],
      downstream: ['ENGINEERING_REPORT'],
    },
    {
      stage: 'REPAIR_AEO',
      modulePath: 'src/autonomous-engineering-orchestrator-v1/autonomous-engineering-orchestrator.ts',
      functionName: 'runAutonomousEngineeringOrchestrator',
      consumesEnvelope: false,
      producesArtifacts: ['AeoOrchestratorReport', 'repair routing'],
      downstream: ['EIAA', 'ENGINEERING_INTELLIGENCE'],
    },
    {
      stage: 'ENGINEERING_REPORT',
      modulePath: 'src/materialization-evidence/materialization-evidence-completion.ts',
      functionName: 'completeMaterializationEvidence',
      consumesEnvelope: false,
      producesArtifacts: ['GeneratedAppManifest', 'forensic manifest', 'engineering summary'],
      downstream: [],
    },
  ];
}
