/**
 * Builder action executor — approved in-memory actions only (Phase 24C).
 */

import type { BuilderAction, BuilderActionType } from '../autonomous-builder-execution-foundation/index.js';
import {
  MAX_WORKSPACE_VIRTUAL_FILES,
  PHASE_24C_ALLOWED_ACTION_TYPES,
  PHASE_24C_BLOCKED_ACTION_TYPES,
} from './controlled-builder-execution-engine-bounds.js';
import {
  collectControlledExecutionEvidence,
  type ControlledExecutionEvidenceType,
} from './builder-execution-evidence-collector.js';

export interface ActionExecutionOutcome {
  success: boolean;
  summary: string;
  evidenceIds: string[];
  blocked: boolean;
  blockReason: string | null;
}

const virtualFiles = new Map<string, Map<string, string>>();

export function resetVirtualWorkspaceFilesForTests(): void {
  virtualFiles.clear();
}

function workspaceFiles(workspaceId: string): Map<string, string> {
  let files = virtualFiles.get(workspaceId);
  if (!files) {
    files = new Map();
    virtualFiles.set(workspaceId, files);
  }
  return files;
}

export function isPhase24CActionAllowed(actionType: BuilderActionType): boolean {
  return (PHASE_24C_ALLOWED_ACTION_TYPES as readonly string[]).includes(actionType);
}

export function isPhase24CActionBlocked(actionType: BuilderActionType): boolean {
  return (PHASE_24C_BLOCKED_ACTION_TYPES as readonly string[]).includes(actionType);
}

function pushEvidence(
  sessionId: string,
  workspaceId: string,
  action: BuilderAction,
  evidenceType: ControlledExecutionEvidenceType,
  description: string,
): string {
  const record = collectControlledExecutionEvidence({
    sessionId,
    workspaceId,
    actionId: action.actionId,
    evidenceType,
    description,
    source: 'builder-action-executor',
  });
  return record.evidenceId;
}

export function executeApprovedBuilderAction(input: {
  sessionId: string;
  workspaceId: string;
  action: BuilderAction;
  generatedContent?: string;
}): ActionExecutionOutcome {
  const { sessionId, workspaceId, action } = input;

  if (isPhase24CActionBlocked(action.actionType)) {
    return {
      success: false,
      summary: `${action.actionType} blocked in Phase 24C — requires later authority phase`,
      evidenceIds: [],
      blocked: true,
      blockReason: action.actionType,
    };
  }

  if (!isPhase24CActionAllowed(action.actionType)) {
    return {
      success: false,
      summary: `${action.actionType} is not an approved Phase 24C action`,
      evidenceIds: [],
      blocked: true,
      blockReason: action.actionType,
    };
  }

  const evidenceIds: string[] = [];
  evidenceIds.push(
    pushEvidence(sessionId, workspaceId, action, 'ACTION_STARTED', `${action.actionType} started`),
  );

  const files = workspaceFiles(workspaceId);
  const targetPath = action.targetPath ?? `src/generated/${action.actionId}.ts`;
  const content =
    input.generatedContent ??
    `// Generated by controlled builder execution\n// ${action.payloadSummary || action.actionType}\nexport default {};\n`;

  switch (action.actionType) {
    case 'CREATE_FOLDER':
      evidenceIds.push(
        pushEvidence(
          sessionId,
          workspaceId,
          action,
          'OUTPUT_GENERATED',
          `Folder path reserved: ${targetPath}`,
        ),
      );
      break;
    case 'CREATE_FILE':
    case 'GENERATE_CODE':
    case 'GENERATE_COMPONENT':
    case 'GENERATE_SCREEN':
      if (files.size >= MAX_WORKSPACE_VIRTUAL_FILES && !files.has(targetPath)) {
        return {
          success: false,
          summary: 'Virtual workspace file limit reached',
          evidenceIds,
          blocked: false,
          blockReason: null,
        };
      }
      files.set(targetPath, content);
      evidenceIds.push(
        pushEvidence(
          sessionId,
          workspaceId,
          action,
          'FILE_CREATED',
          `Virtual file created: ${targetPath}`,
        ),
      );
      evidenceIds.push(
        pushEvidence(
          sessionId,
          workspaceId,
          action,
          'OUTPUT_GENERATED',
          `Output generated for ${action.actionType}`,
        ),
      );
      break;
    case 'MODIFY_FILE': {
      if (!files.has(targetPath)) {
        files.set(targetPath, content);
        evidenceIds.push(
          pushEvidence(
            sessionId,
            workspaceId,
            action,
            'FILE_CREATED',
            `Virtual file created during modify: ${targetPath}`,
          ),
        );
      } else {
        files.set(targetPath, `${files.get(targetPath)}\n${content}`);
        evidenceIds.push(
          pushEvidence(
            sessionId,
            workspaceId,
            action,
            'FILE_MODIFIED',
            `Virtual file modified: ${targetPath}`,
          ),
        );
      }
      break;
    }
    default:
      return {
        success: false,
        summary: `Unhandled approved action: ${action.actionType}`,
        evidenceIds,
        blocked: true,
        blockReason: action.actionType,
      };
  }

  evidenceIds.push(
    pushEvidence(
      sessionId,
      workspaceId,
      action,
      'ACTION_COMPLETED',
      `${action.actionType} completed with evidence`,
    ),
  );

  return {
    success: true,
    summary: `${action.actionType} executed in isolated workspace`,
    evidenceIds,
    blocked: false,
    blockReason: null,
  };
}

export function getVirtualWorkspaceFileCount(workspaceId: string): number {
  return workspaceFiles(workspaceId).size;
}

export function listVirtualWorkspaceFiles(workspaceId: string): string[] {
  return [...workspaceFiles(workspaceId).keys()].slice(0, 32);
}
