/**
 * Execution Readiness Gate — registry constants (V1).
 */

export const EXECUTION_READINESS_GATE_V1_PASS = 'EXECUTION_READINESS_GATE_V1_PASS';

export const EXECUTION_READINESS_GATE_OWNER_MODULE = 'execution-readiness-gate';

export const EXECUTION_READINESS_GATE_PHASE = '26.39';

export const EXECUTION_READINESS_GATE_REPORT_TITLE = 'Execution Readiness Gate Report';

export const MAX_EXECUTION_READINESS_HISTORY = 16;

export const MAX_EXECUTION_GATE_RUNTIME_MS = 8000;

export const EXECUTION_READINESS_CATEGORIES = [
  'NOT_READY',
  'NEEDS_WORK',
  'EXECUTION_CANDIDATE',
  'EXECUTION_READY',
] as const;

export const EXECUTION_GATE_DECISIONS = [
  'REJECT_EXECUTION',
  'REQUEST_REMEDIATION',
  'ALLOW_EXECUTION_PREPARATION',
  'ALLOW_EXECUTION',
] as const;

export const EXECUTION_BLOCKER_PRIORITIES = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as const;

export const EXECUTION_RISK_TYPES = [
  'UNRESOLVED_CRITICAL_GAP',
  'UNRESOLVED_HIGH_BLOCKER',
  'PLANNING_INCONSISTENCY',
  'ARCHITECTURE_INCONSISTENCY',
  'BUILD_PLAN_INCONSISTENCY',
  'ORCHESTRATION_FAILURE',
  'CONFIDENCE_INSTABILITY',
  'READINESS_ESCALATION',
  'PLANNING_GATE_REJECTION',
  'SIMULATION_UNHEALTHY',
] as const;

export const UPSTREAM_AUTHORITIES = [
  'UNIFIED_INTAKE_INTELLIGENCE',
  'PLANNING_GATE_AUTHORITY',
  'PLANNING_BRIEF_GENERATOR',
  'ARCHITECTURE_BRIEF_GENERATOR',
  'BUILD_PLAN_GENERATOR',
  'FOUNDER_TEST_AUTOMATION',
  'FOUNDER_SIMULATION_ENGINE',
  'CROSS_SYSTEM_ORCHESTRATION_PROOF',
  'REQUIREMENT_COMPLETENESS_INTELLIGENCE',
] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_EXECUTION_GATE',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MUTATION',
  'NO_EXECUTION',
  'NO_DEPLOYMENT',
  'NO_AUTONOMOUS_BUILDING',
  'EVIDENCE_BASED_DECISIONS_ONLY',
  'BOUNDED_ANALYSIS_HISTORY',
  'ADVISORY_ONLY',
] as const;

export const EXECUTION_PERMISSION_THRESHOLDS = {
  MIN_ORCHESTRATION_PROOF_FOR_EXECUTION: 80,
  MIN_READINESS_FOR_EXECUTION: 90,
  MIN_READINESS_FOR_PREPARATION: 70,
} as const;
