/**
 * Intelligence Console capability registry.
 */

export interface IntelligenceConsoleCapability {
  capabilityId: string;
  label: string;
  phase: number;
  ownerModule: string;
  extensionOnly: boolean;
}

export const INTELLIGENCE_CONSOLE_CAPABILITIES: readonly IntelligenceConsoleCapability[] = [
  {
    capabilityId: 'WORLD2_BUILDER_PACKET_EXECUTION',
    label: 'World 2 Builder Packet Execution',
    phase: 15.2,
    ownerModule: 'devpulse_v2_world2_builder_packet_execution',
    extensionOnly: true,
  },
  {
    capabilityId: 'WORLD2_CONTROLLED_APPLY_RUNTIME',
    label: 'World 2 Controlled Apply Runtime',
    phase: 15.3,
    ownerModule: 'devpulse_v2_world2_controlled_apply_runtime',
    extensionOnly: true,
  },
  {
    capabilityId: 'WORLD2_ROLLBACK_RUNTIME',
    label: 'World 2 Rollback Runtime',
    phase: 15.4,
    ownerModule: 'devpulse_v2_world2_rollback_runtime',
    extensionOnly: true,
  },
  {
    capabilityId: 'WORLD2_RECOVERY_RUNTIME',
    label: 'World 2 Recovery Runtime',
    phase: 15.5,
    ownerModule: 'devpulse_v2_world2_recovery_runtime',
    extensionOnly: true,
  },
  {
    capabilityId: 'WORLD2_COMPLETION_RUNTIME',
    label: 'World 2 Completion Runtime',
    phase: 15.6,
    ownerModule: 'devpulse_v2_world2_completion_runtime',
    extensionOnly: true,
  },
  {
    capabilityId: 'LIVE_PREVIEW_RUNTIME',
    label: 'Live Preview Runtime',
    phase: 16.1,
    ownerModule: 'devpulse_v2_live_preview_runtime',
    extensionOnly: true,
  },
  {
    capabilityId: 'PREVIEW_INTELLIGENCE',
    label: 'Preview Intelligence',
    phase: 16.2,
    ownerModule: 'devpulse_v2_preview_intelligence',
    extensionOnly: true,
  },
  {
    capabilityId: 'SELF_VISION_RUNTIME',
    label: 'Self Vision Runtime',
    phase: 16.3,
    ownerModule: 'devpulse_v2_self_vision_runtime',
    extensionOnly: true,
  },
  {
    capabilityId: 'UI_INSPECTION_ENGINE',
    label: 'UI Inspection Engine',
    phase: 16.4,
    ownerModule: 'devpulse_v2_ui_inspection_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'INTERACTION_TESTING_ENGINE',
    label: 'Interaction Testing Engine',
    phase: 16.5,
    ownerModule: 'devpulse_v2_interaction_testing_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'VISUAL_VERIFICATION_ENGINE',
    label: 'Visual Verification Engine',
    phase: 16.6,
    ownerModule: 'devpulse_v2_visual_verification_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'UNIFIED_VERIFICATION_LAB_RUNTIME',
    label: 'Unified Verification Lab Runtime',
    phase: 16.7,
    ownerModule: 'devpulse_v2_unified_verification_lab_runtime',
    extensionOnly: true,
  },
  {
    capabilityId: 'VERIFICATION_REGISTRY',
    label: 'Verification Registry',
    phase: 16.8,
    ownerModule: 'devpulse_v2_verification_registry',
    extensionOnly: true,
  },
  {
    capabilityId: 'VERIFICATION_ORCHESTRATOR',
    label: 'Verification Orchestrator',
    phase: 16.9,
    ownerModule: 'devpulse_v2_verification_orchestrator',
    extensionOnly: true,
  },
  {
    capabilityId: 'VERIFICATION_EVIDENCE_ENGINE',
    label: 'Verification Evidence Engine',
    phase: 16.10,
    ownerModule: 'devpulse_v2_verification_evidence_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'VERIFICATION_REPORTING_ENGINE',
    label: 'Verification Reporting Engine',
    phase: 16.11,
    ownerModule: 'devpulse_v2_verification_reporting_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'UNIFIED_VERIFICATION_ENTRY',
    label: 'Unified Verification Entry',
    phase: 16.12,
    ownerModule: 'devpulse_v2_unified_verification_entry',
    extensionOnly: true,
  },
  {
    capabilityId: 'CLOUD_RUNTIME_FOUNDATION',
    label: 'Cloud Runtime Foundation',
    phase: 17.1,
    ownerModule: 'devpulse_v2_cloud_runtime_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'WORKSPACE_HOSTING_FOUNDATION',
    label: 'Workspace Hosting Foundation',
    phase: 17.2,
    ownerModule: 'devpulse_v2_workspace_hosting_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'PERSISTENT_BUILD_RUNTIME_FOUNDATION',
    label: 'Persistent Build Runtime Foundation',
    phase: 17.3,
    ownerModule: 'devpulse_v2_persistent_build_runtime_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'CLOUD_VERIFICATION_FOUNDATION',
    label: 'Cloud Verification Foundation',
    phase: 17.4,
    ownerModule: 'devpulse_v2_cloud_verification_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'CLOUD_RECOVERY_FOUNDATION',
    label: 'Cloud Recovery Foundation',
    phase: 17.5,
    ownerModule: 'devpulse_v2_cloud_recovery_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'CLOUD_MONITORING_FOUNDATION',
    label: 'Cloud Monitoring Foundation',
    phase: 17.6,
    ownerModule: 'devpulse_v2_cloud_monitoring_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'MOBILE_COMMAND_RUNTIME_FOUNDATION',
    label: 'Mobile Command Runtime Foundation',
    phase: 18.1,
    ownerModule: 'devpulse_v2_mobile_command_runtime_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'MOBILE_CHAT_RUNTIME_FOUNDATION',
    label: 'Mobile Chat Runtime Foundation',
    phase: 18.2,
    ownerModule: 'devpulse_v2_mobile_chat_runtime_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'MOBILE_PREVIEW_RUNTIME_FOUNDATION',
    label: 'Mobile Preview Runtime Foundation',
    phase: 18.3,
    ownerModule: 'devpulse_v2_mobile_preview_runtime_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'MOBILE_APPROVAL_RUNTIME_FOUNDATION',
    label: 'Mobile Approval Runtime Foundation',
    phase: 18.4,
    ownerModule: 'devpulse_v2_mobile_approval_runtime_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'CROSS_DEVICE_RUNTIME_FOUNDATION',
    label: 'Cross Device Runtime Foundation',
    phase: 18.5,
    ownerModule: 'devpulse_v2_cross_device_runtime_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'FOUNDER_NOTIFICATION_RUNTIME_FOUNDATION',
    label: 'Founder Notification Runtime Foundation',
    phase: 18.6,
    ownerModule: 'devpulse_v2_founder_notification_runtime_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'FOUNDER_INBOX_FOUNDATION',
    label: 'Founder Inbox Foundation',
    phase: 18.7,
    ownerModule: 'devpulse_v2_founder_inbox_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'NOTIFICATION_DELIVERY_FOUNDATION',
    label: 'Notification Delivery Foundation',
    phase: 18.8,
    ownerModule: 'devpulse_v2_notification_delivery_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'MOBILE_PUSH_FOUNDATION',
    label: 'Mobile Push Foundation',
    phase: 18.9,
    ownerModule: 'devpulse_v2_mobile_push_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'AUTONOMOUS_TESTING',
    label: 'Autonomous Testing',
    phase: 19.4,
    ownerModule: 'devpulse_v2_autonomous_testing',
    extensionOnly: true,
  },
  {
    capabilityId: 'AUTONOMOUS_FIXING',
    label: 'Autonomous Fixing',
    phase: 19.5,
    ownerModule: 'devpulse_v2_autonomous_fixing',
    extensionOnly: true,
  },
  {
    capabilityId: 'AUTONOMOUS_VERIFICATION',
    label: 'Autonomous Verification',
    phase: 19.6,
    ownerModule: 'devpulse_v2_autonomous_verification',
    extensionOnly: true,
  },
  {
    capabilityId: 'AUTONOMOUS_COMPLETION_ENGINE',
    label: 'Autonomous Completion Engine',
    phase: 19.7,
    ownerModule: 'devpulse_v2_autonomous_completion_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'MULTI_PROJECT_FOUNDATION',
    label: 'Multi Project Foundation',
    phase: 20.1,
    ownerModule: 'devpulse_v2_multi_project_foundation',
    extensionOnly: true,
  },
  {
    capabilityId: 'WORKSPACE_ISOLATION_EXPANSION',
    label: 'Workspace Isolation Expansion',
    phase: 20.2,
    ownerModule: 'devpulse_v2_workspace_isolation_expansion',
    extensionOnly: true,
  },
  {
    capabilityId: 'RESOURCE_ALLOCATION',
    label: 'Resource Allocation',
    phase: 20.3,
    ownerModule: 'devpulse_v2_resource_allocation',
    extensionOnly: true,
  },
  {
    capabilityId: 'PARALLEL_BUILD_ORCHESTRATION',
    label: 'Parallel Build Orchestration',
    phase: 20.4,
    ownerModule: 'devpulse_v2_parallel_build_orchestration',
    extensionOnly: true,
  },
  {
    capabilityId: 'MULTI_PROJECT_VERIFICATION',
    label: 'Multi Project Verification',
    phase: 20.5,
    ownerModule: 'devpulse_v2_multi_project_verification',
    extensionOnly: true,
  },
  {
    capabilityId: 'MULTI_PROJECT_VERIFICATION_ORCHESTRATION',
    label: 'Multi Project Verification Orchestration',
    phase: 20.51,
    ownerModule: 'devpulse_v2_multi_project_verification_orchestration',
    extensionOnly: true,
  },
  {
    capabilityId: 'MULTI_PROJECT_MONITORING',
    label: 'Multi Project Monitoring',
    phase: 20.6,
    ownerModule: 'devpulse_v2_multi_project_monitoring',
    extensionOnly: true,
  },
  {
    capabilityId: 'MISSING_CAPABILITY_ESCALATION',
    label: 'Missing Capability Escalation',
    phase: 21.1,
    ownerModule: 'devpulse_v2_missing_capability_escalation',
    extensionOnly: true,
  },
  {
    capabilityId: 'CAPABILITY_RESEARCH_ENGINE',
    label: 'Capability Research Engine',
    phase: 21.2,
    ownerModule: 'devpulse_v2_capability_research_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'CAPABILITY_PLANNING_ENGINE',
    label: 'Capability Planning Engine',
    phase: 21.3,
    ownerModule: 'devpulse_v2_capability_planning_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'CAPABILITY_BUILD_ENGINE',
    label: 'Capability Build Engine',
    phase: 21.4,
    ownerModule: 'devpulse_v2_capability_build_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'CAPABILITY_VERIFICATION_ENGINE',
    label: 'Capability Verification Engine',
    phase: 21.5,
    ownerModule: 'devpulse_v2_capability_verification_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'SELF_EVOLUTION_GOVERNANCE',
    label: 'Self Evolution Governance',
    phase: 21.6,
    ownerModule: 'devpulse_v2_self_evolution_governance',
    extensionOnly: true,
  },
  {
    capabilityId: 'UNIFIED_TRUST_RUNTIME',
    label: 'Unified Trust Runtime',
    phase: 22.1,
    ownerModule: 'devpulse_v2_unified_trust_runtime',
    extensionOnly: true,
  },
  {
    capabilityId: 'EVIDENCE_INTELLIGENCE',
    label: 'Evidence Intelligence',
    phase: 22.2,
    ownerModule: 'devpulse_v2_evidence_intelligence',
    extensionOnly: true,
  },
  {
    capabilityId: 'REALITY_VERIFICATION_EXPANSION',
    label: 'Reality Verification Expansion',
    phase: 22.3,
    ownerModule: 'devpulse_v2_reality_verification_expansion',
    extensionOnly: true,
  },
  {
    capabilityId: 'COMPLETION_TRUTH_ENGINE',
    label: 'Completion Truth Engine',
    phase: 22.4,
    ownerModule: 'devpulse_v2_completion_truth_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'PREDICTION_TRUST_LAYER',
    label: 'Prediction Trust Layer',
    phase: 22.5,
    ownerModule: 'devpulse_v2_prediction_trust_layer',
    extensionOnly: true,
  },
  {
    capabilityId: 'UNIFIED_TRUST_SCORE',
    label: 'Unified Trust Score',
    phase: 22.6,
    ownerModule: 'devpulse_v2_unified_trust_score',
    extensionOnly: true,
  },
  {
    capabilityId: 'RELIABILITY_HARDENING',
    label: 'Reliability Hardening',
    phase: 23.1,
    ownerModule: 'devpulse_v2_reliability_hardening',
    extensionOnly: true,
  },
  {
    capabilityId: 'PERFORMANCE_HARDENING',
    label: 'Performance Hardening',
    phase: 23.2,
    ownerModule: 'devpulse_v2_performance_hardening',
    extensionOnly: true,
  },
  {
    capabilityId: 'SECURITY_HARDENING',
    label: 'Security Hardening',
    phase: 23.3,
    ownerModule: 'devpulse_v2_security_hardening',
    extensionOnly: true,
  },
  {
    capabilityId: 'PRIVACY_HARDENING',
    label: 'Privacy Hardening',
    phase: 23.4,
    ownerModule: 'devpulse_v2_privacy_hardening',
    extensionOnly: true,
  },
  {
    capabilityId: 'RECOVERY_HARDENING',
    label: 'Recovery Hardening',
    phase: 23.5,
    ownerModule: 'devpulse_v2_recovery_hardening',
    extensionOnly: true,
  },
  {
    capabilityId: 'SCALE_HARDENING',
    label: 'Scale Hardening',
    phase: 23.6,
    ownerModule: 'devpulse_v2_scale_hardening',
    extensionOnly: true,
  },
  {
    capabilityId: 'SELF_DOCUMENTATION',
    label: 'Self Documentation',
    phase: 24.1,
    ownerModule: 'devpulse_v2_self_documentation',
    extensionOnly: true,
  },
  {
    capabilityId: 'FOUNDER_GUIDES',
    label: 'Founder Guides',
    phase: 24.2,
    ownerModule: 'devpulse_v2_founder_guides',
    extensionOnly: true,
  },
  {
    capabilityId: 'USER_GUIDES',
    label: 'User Guides',
    phase: 24.3,
    ownerModule: 'devpulse_v2_user_guides',
    extensionOnly: true,
  },
  {
    capabilityId: 'ARCHITECTURE_DOCUMENTATION',
    label: 'Architecture Documentation',
    phase: 24.4,
    ownerModule: 'devpulse_v2_architecture_documentation',
    extensionOnly: true,
  },
  {
    capabilityId: 'API_DOCUMENTATION',
    label: 'API Documentation',
    phase: 24.5,
    ownerModule: 'devpulse_v2_api_documentation',
    extensionOnly: true,
  },
  {
    capabilityId: 'INTERACTIVE_EXPLANATIONS',
    label: 'Interactive Explanations',
    phase: 24.6,
    ownerModule: 'devpulse_v2_interactive_explanations',
    extensionOnly: true,
  },
  {
    capabilityId: 'VERIFICATION_INTEGRATION',
    label: 'Verification Integration',
    phase: 19.32,
    ownerModule: 'devpulse_v2_verification_integration',
    extensionOnly: true,
  },
  {
    capabilityId: 'VERIFICATION_INTELLIGENCE',
    label: 'Verification Intelligence',
    phase: 19.31,
    ownerModule: 'devpulse_v2_verification_intelligence',
    extensionOnly: true,
  },
  {
    capabilityId: 'VERIFICATION_STRATEGY_CORE',
    label: 'Verification Strategy Core',
    phase: 19.3,
    ownerModule: 'devpulse_v2_verification_strategy_core',
    extensionOnly: true,
  },
  {
    capabilityId: 'BUILD_STRATEGY_ENGINE',
    label: 'Build Strategy Engine',
    phase: 19.2,
    ownerModule: 'devpulse_v2_build_strategy_engine',
    extensionOnly: true,
  },
  {
    capabilityId: 'AUTONOMOUS_BUILDER_FOUNDATION',
    label: 'Autonomous Builder Foundation',
    phase: 19.1,
    ownerModule: 'devpulse_v2_autonomous_builder_foundation',
    extensionOnly: true,
  },
] as const;

export function isIntelligenceConsoleCapability(capabilityId: string): boolean {
  return INTELLIGENCE_CONSOLE_CAPABILITIES.some((c) => c.capabilityId === capabilityId);
}
