/**
 * Controlled-to-real-file execution bridge — maps 24C actions to 24D file ops (Phase 24D).
 */

import type { BuilderAction, BuilderActionType } from '../autonomous-builder-execution-foundation/index.js';
import {
  createRealFileOperation,
  isRealFileOperationBlocked,
  type RealFileOperation,
  type RealFileOperationType,
} from './real-file-operation-model.js';

const GENERATE_DEFAULT_CONTENT =
  '// Generated by real file workspace execution (Phase 24D)\nexport default {};\n';

const BRIDGE_MAP: Partial<Record<BuilderActionType, RealFileOperationType>> = {
  CREATE_FOLDER: 'CREATE_FOLDER',
  CREATE_FILE: 'CREATE_FILE',
  MODIFY_FILE: 'MODIFY_FILE',
  GENERATE_CODE: 'CREATE_FILE',
  GENERATE_COMPONENT: 'CREATE_FILE',
  GENERATE_SCREEN: 'CREATE_FILE',
};

const BLOCKED_24C_ACTIONS: BuilderActionType[] = [
  'DELETE_FILE',
  'RUN_COMMAND',
  'INSTALL_DEPENDENCY',
];

export function mapControlledActionToRealFileOperation(action: BuilderAction): RealFileOperation | null {
  if (BLOCKED_24C_ACTIONS.includes(action.actionType)) {
    return createRealFileOperation({
      workspaceId: action.workspaceId,
      relativePath: action.targetPath ?? 'blocked.txt',
      operationType: action.actionType === 'DELETE_FILE' ? 'DELETE_FILE' : 'RUN_COMMAND',
      requestedBy: action.requestedBy,
      sourceActionId: action.actionId,
    });
  }

  const mapped = BRIDGE_MAP[action.actionType];
  if (!mapped) return null;

  const relativePath =
    action.targetPath ??
    (mapped === 'CREATE_FOLDER' ? 'src/generated' : `src/generated/${action.actionId}.tsx`);

  const operationType =
    action.actionType === 'MODIFY_FILE' && mapped === 'CREATE_FILE' ? 'MODIFY_FILE' : mapped;

  return createRealFileOperation({
    workspaceId: action.workspaceId,
    relativePath,
    operationType,
    requestedBy: action.requestedBy,
    sourceActionId: action.actionId,
    payload:
      operationType === 'CREATE_FOLDER'
        ? undefined
        : `${GENERATE_DEFAULT_CONTENT}// ${action.payloadSummary || action.actionType}\n`,
  });
}

export function listBridgeableControlledActionTypes(): BuilderActionType[] {
  return Object.keys(BRIDGE_MAP) as BuilderActionType[];
}

export function isControlledActionBridgeBlocked(actionType: BuilderActionType): boolean {
  return BLOCKED_24C_ACTIONS.includes(actionType) || isRealFileOperationBlocked(actionType);
}
