/**
 * AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_1 — bounds and pass tokens.
 */

export const AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_1_PASS_TOKEN =
  'AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_1_PASS';

export const AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_1_ARTIFACT_DIR =
  '.aidevengine-multi-domain-build-proof-v1-1';

export const AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_1_REPORT_TITLE =
  'AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_1_REPORT.md';

export const MULTI_DOMAIN_V1_1_BASELINE_ARTIFACT_DIR =
  '.aidevengine-multi-domain-build-proof-v1';
