/**
 * Intake Alignment Engine — registry constants (V1).
 */

export const MULTI_SOURCE_INTAKE_ALIGNMENT_REPAIR_V1_PASS =
  'MULTI_SOURCE_INTAKE_ALIGNMENT_REPAIR_V1_PASS';

export const INTAKE_ALIGNMENT_ENGINE_OWNER_MODULE = 'intake-alignment-engine';

export const INTAKE_ALIGNMENT_ENGINE_PHASE = '26.34';

export const INTAKE_ALIGNMENT_REPORT_TITLE = 'Multi-Source Intake Alignment Report';

export const MAX_INTAKE_ALIGNMENT_HISTORY = 32;

export const ALIGNMENT_CATEGORIES = [
  'CONFLICTED',
  'PARTIAL_ALIGNMENT',
  'HIGH_ALIGNMENT',
  'STRONG_ALIGNMENT',
] as const;

export const CONFLICT_CLASSIFICATIONS = ['REAL_CONFLICT', 'FALSE_CONFLICT'] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_INTELLIGENCE',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MODIFICATION',
  'NO_AUTONOMOUS_EXECUTION',
  'EVIDENCE_BASED_ALIGNMENT_ONLY',
  'NO_FAKE_CONFIDENCE_INFLATION',
  'BOUNDED_ANALYSIS_HISTORY',
] as const;
