/**
 * Revenue Reality Authority — markdown report builder.
 */

import {
  REVENUE_REALITY_AUTHORITY_PASS_TOKEN,
  REVENUE_REALITY_AUTHORITY_PHASE,
  REVENUE_REALITY_AUTHORITY_REPORT_TITLE,
  REVENUE_REALITY_CORE_QUESTION,
  SAFETY_GUARANTEES,
} from './revenue-reality-registry.js';
import type { RevenueRealityReport } from './revenue-reality-types.js';

export function buildRevenueRealityReportMarkdown(report: RevenueRealityReport): string {
  const lines: string[] = [
    `# ${REVENUE_REALITY_AUTHORITY_REPORT_TITLE}`,
    '',
    `Generated: ${report.generatedAt}`,
    '',
    '## Phase',
    '',
    REVENUE_REALITY_AUTHORITY_PHASE,
    '',
    '## Core Question',
    '',
    REVENUE_REALITY_CORE_QUESTION,
    '',
    '# Revenue Reality Authority',
    '',
    '## Revenue State',
    '',
    `**${report.revenueRealityState}**`,
    '',
    '## Overall Revenue Score',
    '',
    `${report.overallRevenueScore}/100 (confidence: ${report.confidence}/100)`,
    '',
    '## Revenue Analysis',
    '',
    `- revenue observed: ${report.revenue.revenueObserved ? 'YES' : 'NO'}`,
    `- transaction evidence: ${report.revenue.transactionEvidence ? 'YES' : 'NO'}`,
    `- recurring revenue: ${report.revenue.recurringRevenue ? 'YES' : 'NO'}`,
    `- revenue growth: ${report.revenue.revenueGrowth ? 'YES' : 'NO'}`,
    `- revenue amount (cents): ${report.revenue.revenueAmountCents ?? 'UNKNOWN'}`,
    `- trend: ${report.revenue.trend}`,
    `- revenue score: ${report.revenueScore}/100`,
    '',
    '## Customer Value Analysis',
    '',
    `- paying customers: ${report.customerValue.payingCustomers ? 'YES' : 'NO'}`,
    `- paying customer count: ${report.customerValue.payingCustomerCount ?? 'UNKNOWN'}`,
    `- repeat customers: ${report.customerValue.repeatCustomers ? 'YES' : 'NO'}`,
    `- customer retention: ${report.customerValue.customerRetention ? 'YES' : 'NO'}`,
    `- value exchange: ${report.customerValue.valueExchange ? 'YES' : 'NO'}`,
    `- customer value score: ${report.customerValueScore}/100`,
    '',
    '## Conversion Analysis',
    '',
    `- conversion evidence: ${report.conversion.conversionEvidence ? 'YES' : 'NO'}`,
    `- free-to-paid signals: ${report.conversion.freeToPaidSignals ? 'YES' : 'NO'}`,
    `- purchase completion: ${report.conversion.purchaseCompletion ? 'YES' : 'NO'}`,
    `- conversion score: ${report.conversionScore}/100`,
    '',
    '## Revenue Stability Analysis',
    '',
    `- recurring revenue signals: ${report.revenueStability.recurringRevenueSignals ? 'YES' : 'NO'}`,
    `- revenue consistency: ${report.revenueStability.revenueConsistency ? 'YES' : 'NO'}`,
    `- concentration risk: ${report.revenueStability.revenueConcentrationRisk ? 'YES' : 'NO'}`,
    `- revenue predictability: ${report.revenueStability.revenuePredictability ? 'YES' : 'NO'}`,
    `- stability score: ${report.revenueStabilityScore}/100`,
    '',
    '## Business Risk Analysis',
    '',
    `- business risk score: ${report.businessRiskScore}/100`,
    `- customer churn risk: ${report.businessRisk.customerChurnRisk ? 'YES' : 'NO'}`,
    `- revenue fragility: ${report.businessRisk.revenueFragility ? 'YES' : 'NO'}`,
    `- single-customer risk: ${report.businessRisk.singleCustomerRisk ? 'YES' : 'NO'}`,
    `- sustainability risk: ${report.businessRisk.revenueSustainabilityRisk ? 'YES' : 'NO'}`,
    '',
    '## Observed Revenue Signals',
    '',
    `- revenue observed: ${report.revenueObserved ? 'YES' : 'NO'}`,
    `- paying customers observed: ${report.payingCustomersObserved ? 'YES' : 'NO'}`,
    `- repeat revenue observed: ${report.repeatRevenueObserved ? 'YES' : 'NO'}`,
    '',
    ...report.keyFindings.map((f) => `- ${f}`),
    '',
    '## Missing Evidence',
    '',
    ...report.missingEvidence.map((m) => `- ${m}`),
    ...(report.missingEvidence.length === 0 ? ['- none reported'] : []),
    '',
    '## Risk Signals',
    '',
    ...report.riskSignals.map((r) => `- ${r}`),
    ...(report.riskSignals.length === 0 ? ['- none identified'] : []),
    '',
    '## Recommended Actions',
    '',
    ...report.recommendedActions.map((a) => `- ${a}`),
    ...(report.recommendedActions.length === 0 ? ['- none'] : []),
    '',
    '## Final Verdict',
    '',
    report.finalVerdict,
    '',
    '## Safety',
    '',
    ...SAFETY_GUARANTEES.map((g) => `- ${g}`),
    '',
    '## Pass Token',
    '',
    REVENUE_REALITY_AUTHORITY_PASS_TOKEN,
  ];

  return lines.join('\n');
}

export function formatRevenueRealitySummary(report: RevenueRealityReport): string {
  return (
    `Revenue Reality: ${report.revenueRealityState} — ` +
    `score ${report.overallRevenueScore}/100, revenueObserved=${report.revenueObserved}.`
  );
}
