/**
 * Connected Launch Readiness Proof — markdown report builder.
 */

import {
  CONNECTED_LAUNCH_READINESS_PROOF_CORE_QUESTION,
  CONNECTED_LAUNCH_READINESS_PROOF_PASS_TOKEN,
  CONNECTED_LAUNCH_READINESS_PROOF_PHASE,
  CONNECTED_LAUNCH_READINESS_PROOF_REPORT_TITLE,
  SAFETY_GUARANTEES,
} from './connected-launch-readiness-proof-registry.js';
import type { LaunchReadinessProofReport } from './connected-launch-readiness-proof-types.js';

export function buildLaunchReadinessProofReportMarkdown(
  report: LaunchReadinessProofReport,
): string {
  const lines: string[] = [
    `# ${CONNECTED_LAUNCH_READINESS_PROOF_REPORT_TITLE}`,
    '',
    `Generated: ${report.generatedAt}`,
    '',
    '## Core Question',
    '',
    CONNECTED_LAUNCH_READINESS_PROOF_CORE_QUESTION,
    '',
    '## Phase',
    '',
    CONNECTED_LAUNCH_READINESS_PROOF_PHASE,
    '',
    '## CONNECTED LAUNCH READINESS PROOF',
    '',
    `**Launch proof level:** ${report.launchProofLevel}`,
    `**Launch state:** ${report.launchState}`,
    `**Execution chain connected (through VERIFY):** ${report.executionChainConnected ? 'YES' : 'NO'}`,
    `**Verification proven:** ${report.verificationProven ? 'YES' : 'NO'}`,
    '',
    '## Launch State',
    '',
    `- state: **${report.launchState}**`,
    `- readiness score: ${report.readiness.readinessScore}/100`,
    '',
    '## Launch Proof Level',
    '',
    `- proof level: **${report.launchProofLevel}**`,
    '',
    '## Launch Blockers',
    '',
    `- critical: ${report.blockers.criticalCount}`,
    `- high: ${report.blockers.highCount}`,
    `- medium: ${report.blockers.mediumCount}`,
    `- low: ${report.blockers.lowCount}`,
    '',
    ...report.blockers.blockers.map(
      (b) => `- [${b.severity}] ${b.message} (${b.sourceAuthority})`,
    ),
    ...(report.blockers.blockers.length === 0 ? ['- none'] : []),
    '',
    '## Launch Risks',
    '',
    `- risk level: **${report.risk.riskLevel}**`,
    `- confidence: ${report.risk.confidence}%`,
    '',
    ...report.risk.riskFactors.map((f) => `- ${f}`),
    ...(report.risk.riskFactors.length === 0 ? ['- none identified'] : []),
    '',
    '## Acceptance Analysis',
    '',
    `- acceptance state: **${report.acceptance.acceptanceState}**`,
    `- confidence: ${report.acceptance.confidence}%`,
    '',
    ...report.acceptance.acceptanceReasons.map((r) => `- ${r}`),
    '',
    '## Readiness Analysis',
    '',
    `- readiness: **${report.readiness.readinessState}**`,
    `- score: ${report.readiness.readinessScore}/100`,
    '',
    '## Simulation Analysis',
    '',
    `- coverage: ${report.simulation.simulationCoverage} source(s)`,
    `- simulation score: ${report.simulation.simulationScore}/100`,
    '',
    ...report.simulation.topFailures.map((f) => `- ${f}`),
    ...(report.simulation.topFailures.length === 0 ? ['- no simulation failures recorded'] : []),
    '',
    '## Claim vs Reality Analysis',
    '',
    `- score: ${report.claimReality.score}/100`,
    `- critical violations: ${report.claimReality.criticalViolations}`,
    '',
    ...report.claimReality.violations.map(
      (v) => `- [${v.severity}] ${v.claim} → ${v.reality}`,
    ),
    ...(report.claimReality.violations.length === 0 ? ['- no violations'] : []),
    '',
    '## Manifest Evidence',
    '',
    `- manifest exists: ${report.manifest.manifestExists}`,
    `- execution linked: ${report.manifest.executionLinked}`,
    `- verification linked: ${report.manifest.verificationLinked}`,
    `- launch linked: ${report.manifest.launchLinked}`,
    `- traceability score: ${report.manifest.traceabilityScore}/100`,
    '',
    '## Linkage Analysis',
    '',
    `- launch linkage connected: ${report.linkage.launchLinkageConnected}`,
    `- traceability score: ${report.linkage.traceabilityScore}/100`,
    '',
    '## First Broken Launch Link',
    '',
    report.linkage.firstBrokenLaunchLink ?? 'none',
    '',
    '## Founder Questions',
    '',
    `- Are we launch ready? **${report.founderQuestions.areWeLaunchReady ? 'YES' : 'NO'}**`,
    '',
    '### Why Not',
    '',
    ...report.founderQuestions.whyNot.map((w) => `- ${w}`),
    ...(report.founderQuestions.whyNot.length === 0 ? ['- n/a'] : []),
    '',
    '## Recommended Fixes',
    '',
    report.recommendedFix,
    '',
    ...report.recommendedNextActions.map((a) => `- ${a}`),
    '',
    '## Missing Evidence',
    '',
    ...report.missingEvidence.map((m) => `- ${m}`),
    ...(report.missingEvidence.length === 0 ? ['- none'] : []),
    '',
    '## Safety Guarantees',
    '',
    ...SAFETY_GUARANTEES.map((g) => `- ${g}`),
    '',
    '---',
    '',
    CONNECTED_LAUNCH_READINESS_PROOF_PASS_TOKEN,
  ];

  return lines.join('\n');
}

export function formatLaunchReadinessProofSummary(report: LaunchReadinessProofReport): string {
  const blockerNote =
    report.blockers.criticalCount > 0
      ? ` ${report.blockers.criticalCount} critical blocker(s).`
      : '';
  return (
    `Launch proof ${report.launchProofLevel} — state ${report.launchState}; ` +
    `execution ${report.executionChainConnected ? 'connected' : 'disconnected'}; ` +
    `verification ${report.verificationProven ? 'proven' : 'not proven'}.${blockerNote}`
  );
}
