/**
 * AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1 — bounds and pass tokens.
 */

export const AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_PASS_TOKEN =
  'AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_PASS';

export const AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_ARTIFACT_DIR =
  '.aidevengine-multi-domain-build-proof-v1';

export const AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_REPORT_TITLE =
  'AIDEVENGINE_MULTI_DOMAIN_BUILD_PROOF_V1_REPORT.md';

export const MULTI_DOMAIN_LAUNCH_READY_MIN_COUNT = 4;

export const MULTI_DOMAIN_SCENARIO_COUNT = 5;
