/**
 * Universal Business Rule Engine V1 — B1 CRUD integration.
 *
 * Generates the per-module business-rule module and augments the B1 service
 * so create/update/delete invoke B6 enforcement before persistence. B1 keeps
 * repositories, services, and persistence; B6 owns rule evaluation.
 */

import { moduleIdToPascalCase } from '../universal-crud-generation-engine/universal-crud-types.js';
import type {
  UniversalBusinessRuleDescriptor,
  UniversalBusinessRuleMaterializationInput,
} from './universal-business-rule-types.js';

export function generateModuleBusinessRulesSource(
  descriptors: readonly UniversalBusinessRuleDescriptor[],
  input: UniversalBusinessRuleMaterializationInput,
): string {
  const pascal = moduleIdToPascalCase(input.moduleId);
  const moduleId = input.moduleId;
  const scopeId = `runtime-${moduleId}__${moduleId}`.toLowerCase().replace(/[^a-z0-9_]+/g, '_');
  const constName = `${pascal.toUpperCase()}_BUSINESS_RULES`;

  const runtimeDescriptors = descriptors.map((d) => ({
    ruleId: d.ruleId,
    label: d.label,
    ruleKind: d.ruleKind,
    moduleId: d.moduleId,
    fieldId: d.fieldId,
    inputDefinitions: d.inputDefinitions,
    outputType: d.outputType,
    expression: d.expression,
    dependencies: d.dependencies,
    nullPolicy: d.nullPolicy,
    precisionPolicy: d.precisionPolicy,
    roundingPolicy: d.roundingPolicy,
    divisionByZeroPolicy: d.divisionByZeroPolicy,
    enforcementPoints: d.enforcementPoints,
    severity: d.severity,
    errorCode: d.errorCode,
    userFeedback: d.userFeedback,
    provenance: d.provenance,
    supportClassification: d.supportClassification,
    blockedReason: d.blockedReason,
    version: d.version,
  }));

  return `/** Universal business rules — ${input.moduleDisplayName} (generated by UNIVERSAL_BUSINESS_RULE_ENGINE_V1) */
import { useEffect, useMemo } from 'react';
import type { BusinessRuleDescriptor } from '../../universal-business-rule-runtime/expression-model';
import {
  evaluateRuleDescriptor,
  isExecutableRule,
  type RuleInputBag,
} from '../../universal-business-rule-runtime/evaluator';
import { enforceBusinessRules, type EnforcementOutcome } from '../../universal-business-rule-runtime/enforcement';
import {
  getMemoizedRuleResult,
  memoizeRuleResult,
  invalidateDependentRules,
} from '../../universal-business-rule-runtime/memoization';
import type { BusinessRuleResult } from '../../universal-business-rule-runtime/result-model';
import { dispatchRuntimeEvent } from '../../universal-runtime-state/store';
import type { ${pascal}Entity } from './${moduleId}.types';

export const ${constName}: BusinessRuleDescriptor[] = ${JSON.stringify(runtimeDescriptors, null, 2)};

const RULE_SCOPE_ID = '${scopeId}';
const RULE_PROVENANCE = 'UNIVERSAL_BUSINESS_RULE_ENGINE_V1';

/** Service-boundary enforcement — throws BusinessRuleViolationError on ERROR-severity violations. */
export function enforce${pascal}BusinessRules(enforcementPoint: string, inputs: RuleInputBag): EnforcementOutcome {
  return enforceBusinessRules(${constName}, enforcementPoint, inputs);
}

let relatedLinkCounter: (recordId: string) => number = () => 0;

/** B4 relationship runtime registers the real link counter so delete constraints use actual link data. */
export function register${pascal}RelatedLinkCounter(counter: (recordId: string) => number): void {
  relatedLinkCounter = counter;
}

export function get${pascal}RelatedLinkCount(recordId: string): number {
  return relatedLinkCounter(recordId);
}

/** Derived record count computed from the actual record collection — never a static literal. */
export function compute${pascal}RecordCount(records: ${pascal}Entity[]): number {
  const rule = ${constName}.find((d) => d.ruleKind === 'AGGREGATION' && d.errorCode === 'rule_record_count');
  if (!rule) return records.length;
  const result = evaluateRuleDescriptor(rule, { records: records.map((r) => r.id) });
  return result.status === 'VALUE' && typeof result.value === 'number' ? result.value : records.length;
}

/** Action eligibility evaluated by rule — also re-enforced at the execution boundary. */
export function evaluate${pascal}ActionEligibility(selectionCount: number): boolean {
  const rule = ${constName}.find((d) => d.ruleKind === 'ACTION_ELIGIBILITY' && d.errorCode === 'rule_selection_required');
  if (!rule) return true;
  return evaluateRuleDescriptor(rule, { selectionCount }).status === 'PASSED';
}

/** Workflow guard evaluation delegated from B3-generated state machines. */
export function evaluate${pascal}WorkflowCompletionGuard(requiredStepsComplete: boolean[]): boolean {
  const rule = ${constName}.find((d) => d.ruleKind === 'WORKFLOW_GUARD');
  if (!rule) return true;
  return evaluateRuleDescriptor(rule, { requiredStepsComplete }).status === 'PASSED';
}

/** Relationship delete constraint delegated from B4 lifecycle policies. */
export function evaluate${pascal}DeleteConstraint(recordId: string): BusinessRuleResult | null {
  const rule = ${constName}.find((d) => d.ruleKind === 'RELATIONSHIP_RULE' && d.enforcementPoints.includes('SERVICE_DELETE'));
  if (!rule) return null;
  return evaluateRuleDescriptor(rule, { relatedLinkCount: get${pascal}RelatedLinkCount(recordId) });
}

function statusToRuntimeEvent(status: string): string {
  switch (status) {
    case 'PASSED':
    case 'VALUE':
      return 'rule/evaluation-success';
    case 'FAILED':
    case 'ERROR':
      return 'rule/evaluation-failure';
    case 'BLOCKED':
      return 'rule/blocked';
    case 'INVALID':
      return 'rule/invalid';
    default:
      return 'rule/evaluation-success';
  }
}

export interface ${pascal}BusinessRuleState {
  recordCount: number;
  actionEligible: boolean;
  results: BusinessRuleResult[];
}

/**
 * Runtime rule evaluation hook. B6 evaluates; B5 owns the observable runtime
 * rule state via dispatched rule events. Memoized results are invalidated when
 * the record collection (dependency) changes.
 */
export function use${pascal}BusinessRules(records: ${pascal}Entity[], selectionCount: number): ${pascal}BusinessRuleState {
  const results = useMemo(() => {
    const inputs: RuleInputBag = {
      label: '',
      records: records.map((r) => r.id),
      selectionCount,
      requiredStepsComplete: [],
      relatedLinkCount: 0,
    };
    // Dependency change → invalidate stale memoized results before recomputation.
    for (const descriptor of ${constName}) {
      if (descriptor.dependencies.some((dep) => dep.startsWith('collection:') || dep.startsWith('runtime:'))) {
        invalidateDependentRules(descriptor.ruleId, ${constName});
      }
    }
    return ${constName}.filter(
      (d) => isExecutableRule(d) && d.enforcementPoints.includes('DERIVED_STATE') && d.inputDefinitions.every((def) => def.optional || def.name in inputs),
    ).map((d) => {
      const memoized = getMemoizedRuleResult(d, inputs);
      if (memoized) return memoized;
      const result = evaluateRuleDescriptor(d, inputs);
      memoizeRuleResult(d, inputs, result);
      return result;
    });
  }, [records, selectionCount]);

  useEffect(() => {
    for (const result of results) {
      dispatchRuntimeEvent({
        type: statusToRuntimeEvent(result.status) as never,
        scopeId: RULE_SCOPE_ID,
        payload: { ruleId: result.ruleId, status: result.status, value: result.value, explanation: result.explanation, version: result.version },
        timestamp: new Date().toISOString(),
        provenance: RULE_PROVENANCE,
      });
    }
  }, [results]);

  const recordCount = compute${pascal}RecordCount(records);
  const actionEligible = evaluate${pascal}ActionEligibility(selectionCount);
  return { recordCount, actionEligible, results };
}
`;
}

/**
 * Augments the B1-generated CRUD service so business rules run at the service
 * boundary before persistence. UI validation alone can never bypass rules.
 */
export function augmentCrudServiceWithBusinessRules(serviceSource: string, moduleId: string): string {
  const pascal = moduleIdToPascalCase(moduleId);
  if (serviceSource.includes(`enforce${pascal}BusinessRules`)) return serviceSource;

  let augmented = serviceSource;

  const importAnchor = `import { validate${pascal}FormInput } from './${moduleId}.validation';`;
  if (augmented.includes(importAnchor)) {
    augmented = augmented.replace(
      importAnchor,
      `${importAnchor}\nimport { enforce${pascal}BusinessRules, get${pascal}RelatedLinkCount } from './${moduleId}.business-rules';`,
    );
  }

  const createAnchor = `export function create${pascal}Record(input: ${pascal}FormInput): ${pascal}Entity {
  const validation = validate${pascal}FormInput(input);
  if (!validation.valid) {
    throw new Error(validation.errors.join('; '));
  }`;
  if (augmented.includes(createAnchor)) {
    augmented = augmented.replace(
      createAnchor,
      `${createAnchor}
  enforce${pascal}BusinessRules('SERVICE_CREATE', { label: input.label });`,
    );
  }

  const updateAnchor = `export function update${pascal}Record(id: string, input: ${pascal}FormInput): ${pascal}Entity {
  const validation = validate${pascal}FormInput(input);
  if (!validation.valid) {
    throw new Error(validation.errors.join('; '));
  }`;
  if (augmented.includes(updateAnchor)) {
    augmented = augmented.replace(
      updateAnchor,
      `${updateAnchor}
  enforce${pascal}BusinessRules('SERVICE_UPDATE', { label: input.label });`,
    );
  }

  const deleteAnchor = `export function delete${pascal}Record(id: string): boolean {
  return delete${pascal}Entity(id);
}`;
  if (augmented.includes(deleteAnchor)) {
    augmented = augmented.replace(
      deleteAnchor,
      `export function delete${pascal}Record(id: string): boolean {
  enforce${pascal}BusinessRules('SERVICE_DELETE', { relatedLinkCount: get${pascal}RelatedLinkCount(id) });
  return delete${pascal}Entity(id);
}`,
    );
  }

  return augmented;
}
