/**
 * Architecture Brief Generator — registry constants (V1).
 */

export const ARCHITECTURE_BRIEF_GENERATOR_V1_PASS = 'ARCHITECTURE_BRIEF_GENERATOR_V1_PASS';

export const ARCHITECTURE_BRIEF_GENERATOR_OWNER_MODULE = 'architecture-brief-generator';

export const ARCHITECTURE_BRIEF_GENERATOR_PHASE = '26.31';

export const ARCHITECTURE_BRIEF_GENERATOR_REPORT_TITLE = 'Architecture Brief Generator Report';

export const MAX_ARCHITECTURE_BRIEF_HISTORY = 32;

export const ARCHITECTURE_BRIEF_QUALITY_LEVELS = [
  'INSUFFICIENT',
  'PARTIAL',
  'COMPLETE',
  'HIGH_CONFIDENCE',
] as const;

export const ARCHITECTURE_BRIEF_READINESS_LEVELS = [
  'NOT_READY',
  'ARCHITECTURE_DRAFT_READY',
  'ARCHITECTURE_READY',
] as const;

export const ARCHITECTURE_RISK_TYPES = [
  'UNCLEAR_OWNERSHIP',
  'UNCLEAR_PERMISSIONS',
  'UNCLEAR_WORKFLOWS',
  'UNCLEAR_INTEGRATIONS',
  'SCALING_AMBIGUITY',
] as const;

export const ALLOWED_GATE_DECISIONS_FOR_ARCHITECTURE = [
  'ALLOW_LIMITED_PLANNING',
  'ALLOW_FULL_PLANNING',
] as const;

export const SAFETY_GUARANTEES = [
  'READ_ONLY_ARCHITECTURE_PREPARATION',
  'NO_ARCHITECTURE_IMPLEMENTATION',
  'NO_CODE_GENERATION',
  'NO_PROJECT_MODIFICATION',
  'NO_AUTONOMOUS_EXECUTION',
  'GATE_ENFORCED_GENERATION',
  'PLANNING_BRIEF_REQUIRED',
  'EVIDENCE_BASED_OUTPUTS_ONLY',
  'BOUNDED_BRIEF_HISTORY',
] as const;
